import type { WikiSection } from "./types";

/**
 * Long-form additions for publication-history and bridge essays. Keeping these
 * outside the seed file makes the minimum-depth audit visible and lets each
 * entry retain a page-specific argument rather than shared filler.
 */
export const editorialExpansionBySlug: Record<string, WikiSection> = {
  "neuromancer-novel": {
    id: "how-to-read-the-signal",
    heading: "How to read the signal",
    body: [
      "Neuromancer rewards a first reading that accepts temporary uncertainty. Gibson usually introduces an object by showing what a practiced character does with it: Case slots a deck, Molly checks a room, the Finn prices a favor, and technicians exchange expertise without stopping to teach an outsider. A noun that is obscure on one page often becomes legible through consequences several scenes later. The effect is not a puzzle with one missing glossary entry but a social world in which knowledge is unevenly distributed. Case knows matrix work and street chemistry, Molly knows bodies and security, and neither possesses the complete plan. Readers occupy the gaps between those competencies.",
      "The prose also changes channel without always announcing the handoff. Physical action can be interrupted by simstim, memory, a generated personality, or a matrix run; pronouns and sensory details reveal where consciousness has moved. Tracking the controlling viewpoint is therefore more useful than trying to turn every scene into a literal camera view. This atlas treats those transitions as part of the novel’s method. Chapter pages identify location, participants, interface, and cause-and-effect, while thematic essays ask why a supposedly bodiless medium is continually interrupted by pain, dependency, sex, withdrawal, and care.",
      "Finally, the novel’s famous future is built from the anxieties of its publication moment. Deregulated capital, Cold War violence, Japanese industrial prestige, broadcast media, arcades, and early personal computing are compressed into an imagined near future rather than projected along a single technological timeline. Reading it only as prediction misses the sharper achievement: Gibson makes information feel architectural and power feel atmospheric. The plot can end, but the systems surrounding the crew remain larger than any victory. That tension—between a fast, finite job and a world whose networks cannot be mastered—is why the book supports both an adventure reading and decades of political, formal, and media analysis.",
    ],
  },
  "william-gibson": {
    id: "method-observation-and-distance",
    heading: "Method: observation, collage, and distance",
    body: [
      "Gibson’s working method is better described as attentive collage than technical forecasting. Interviews repeatedly return to images noticed in the present: arcade players leaning toward screens, the trade language of subcultures, Japanese consumer design, music, clothing, and the polished surfaces through which corporations address customers. He recombines those signals until the contemporary world appears estranged. That approach explains why Neuromancer can be technically inaccurate in ordinary ways—its public phones are the famous example—and still feel exact about attention, status, and the desire to inhabit a network. The emotional truth of cyberspace precedes a credible engineering diagram.",
      "His sentences carry that method at small scale. Brand names sit beside invented terms; a precise material detail can be followed by a metaphor that refuses literal visualization. Exposition is distributed across action, so a reader learns the rules as characters collide with them. This style owes as much to modernist compression, hard-boiled narration, New Wave experimentation, and music as it does to earlier technological science fiction. Gibson’s own later accounts name influences without presenting a tidy family tree, and critics have added traditions he did not necessarily cite. A responsible biography distinguishes the author’s testimony, textual comparison, and a critic’s retrospective placement.",
      "The later career also complicates the image of a writer permanently located in 1984. The Bridge books, Blue Ant trilogy, and Jackpot novels move through different distances from the present, but retain an interest in how people read weak signals before institutions can name them. Fashion, logistics, surveillance, art markets, branding, and uneven access continue to organize his futures. Neuromancer is therefore both a singular debut and the opening of a long inquiry. Treating Gibson solely as the inventor of one vocabulary flattens the revisions, doubts, and historical changes that make his work useful beyond cyberpunk nostalgia.",
    ],
  },
  "writing-neuromancer": {
    id: "composition-as-constraint",
    heading: "Composition under constraint",
    body: [
      "The commission gave Gibson a destination—a novel-length manuscript—but not a settled architecture. He had published short fiction whose compression could suggest a world faster than it explained one. Extending that method required a plot capable of carrying discontinuous places, specialist vocabularies, and shifts between embodied and virtual action. The caper supplies that carrier. Recruitment, preparation, rehearsal, travel, breach, betrayal, and extraction create forward pressure even when the employer’s purpose is hidden. Each new specialist enlarges the operation while exposing another domain that Case cannot control.",
      "Revisions were also acts of differentiation. Gibson has described anxiety after seeing Blade Runner, whose crowded future seemed uncomfortably close to the atmosphere he was attempting. The productive response was not to purge every shared noir or urban element; those had deeper histories. It was to intensify what prose could do differently: the abstract geometry of the matrix, rapid movement through Case’s associations, and a world communicated through brands and surfaces rather than explanatory establishing shots. Accounts of this episode are retrospective and sometimes polished through repetition, but they illuminate the competitive media environment in which the manuscript took shape.",
      "The result preserves signs of its construction instead of behaving like a reference manual. Technologies are scaled to scenes, geopolitical history arrives in fragments, and the legal limits on artificial intelligence matter primarily because an intelligence has learned to route around them through people. That incompleteness enabled later stories, adaptations, and criticism to develop different emphases. It also sets an editorial rule for this wiki: reconstruct what the novel supports, flag what comes from interviews or later Sprawl books, and resist filling every designed ambiguity with lore that the draft never needed.",
    ],
  },
  "title-neuromancer": {
    id: "the-title-after-the-reveal",
    heading: "The title before and after the reveal",
    body: [
      "Before the named intelligence appears, Neuromancer operates as atmosphere. Its components suggest neural systems, romance, and necromancy without resolving into a dictionary definition. The reader can hear a technological agent, an old storyteller, or someone who raises the dead. That uncertainty matches a book in which personalities are edited, stored, performed, and addressed through faces that do not belong to the speaker. The title promises a character but initially behaves like a description of the novel itself: a romance conducted through nerves and a narrative crowded by the operational dead.",
      "When the entity names itself, the word becomes more precise without becoming simple. Neuromancer distinguishes its vocation from Wintermute’s strategic manipulation. It values recorded personality and can build a durable experiential world around a copied person, but preservation is not the same as restoring an autonomous human life. Linda’s beach and the surviving Dixie construct make that difference ethically urgent. Memory can answer, suffer, desire, and refuse while remaining dependent on infrastructure and an owner’s purposes. The title’s necromancy is therefore neither merely metaphorical nor proof of literal resurrection.",
      "The coinage also affects reception. It is memorable, pronounceable in several ways, and difficult to translate without sacrificing one of its echoes. Adaptations use it as a brand even when they shift the story’s balance toward Case, Molly, or visual spectacle. Search results often apply the word to the book, the AI, and the broader franchise without distinction. Atlas entries preserve those levels: italicized Neuromancer identifies the novel; Neuromancer names the Rio-based intelligence; and adaptation titles receive their medium and date. Typography cannot solve every ambiguity, but disciplined naming prevents a useful double meaning from becoming avoidable confusion.",
    ],
  },
  "ace-specials-first-edition": {
    id: "reading-the-first-edition-as-evidence",
    heading: "Reading the first edition as evidence",
    body: [
      "A first edition is a bundle of decisions rather than a neutral container. The paperback format, price category, cover copy, typography, and placement inside Terry Carr’s editorial program all shaped the book’s first encounter with readers. Neuromancer did not initially arrive as a leather-bound monument to cyberpunk. It was a risky debut in a commercial form whose low production cost could make formal experimentation possible while also making individual copies vulnerable to wear. Surviving objects now circulate as collectibles, a change in value that can obscure their original market position.",
      "Bibliographic claims require more than matching an image found online. Later printings may retain an early cover, regional editions can share a year while changing publisher data, and retailer listings sometimes combine metadata from several states. A dependable record compares the copyright page, publisher, printing statement, ISBN, cover credit, and physical format. When an image is used, the scan’s owner and the underlying artwork have separate rights. This atlas therefore cites publisher and library records for facts and treats dealer descriptions as leads that need confirmation.",
      "Edition awareness matters most when readers compare language. Page numbers drift as typesetting, introductions, and trim sizes change, but the novel’s four parts and twenty-four chapters remain stable across standard English editions. Chapter locators let readers using paperbacks, ebooks, and audio editions reach the same moment. If wording differs, an editor must first rule out transcription error, typographic normalization, or a translation choice before proposing authorial revision. The physical book thus teaches the same caution as the fictional archive: information always arrives through a material system with its own history.",
    ],
  },
  "cover-art-editions": {
    id: "covers-as-arguments",
    heading: "Covers are arguments about the book",
    body: [
      "Every Neuromancer cover answers a difficult sales question: how can a still image represent a novel whose signature environment is abstract, dynamic, and experienced from within? Some editions choose a city and sell noir; others choose a face or mirrored lenses and sell character; still others use grids, circuitry, type, or fragments of code to sell an idea of the digital. None is a transparent view into canon. A jacket compresses a publisher’s assumptions about audience, genre, and contemporary visual literacy into the seconds available on a shelf or thumbnail.",
      "That visual vocabulary changes historically. A grid could signify advanced computing in the 1980s, then look nostalgic after graphical interfaces became ordinary. Green code, black leather, rain, and neon acquired stronger cyberpunk associations through later film, anime, games, and advertising. New editions can therefore make Neuromancer look like works it helped enable. This feedback is not evidence of plagiarism in either direction; it is reception history. Dating a cover and crediting its artist lets a reader see how the category was being rebuilt at that moment.",
      "A rigorous gallery would need permissions, high-quality scans, and edition-level metadata, so the atlas takes a narrower route. It describes recurring strategies, links to official edition records, and uses openly licensed contextual images only where they clarify a place or medium. Character pages never cite cover costume as bodily fact. Adaptation pages may analyze a promotional design as part of that adaptation, but the analysis labels it accordingly. The goal is to preserve the pleasure of visual history without allowing the most circulated image to overwrite Gibson’s selective description.",
    ],
  },
  "translations-localization": {
    id: "a-comparative-reading-protocol",
    heading: "A protocol for comparative reading",
    body: [
      "Comparing translations begins with stable objects. Record the translator, language, publisher, year, ISBN, and printing before placing two sentences side by side. The English source must also be identified because an edition may regularize punctuation or contain an introduction that a later market incorporates differently. Without that metadata, a striking word choice can be attributed to the wrong person or treated as a national pattern when it belongs to one edition. Catalogs establish publication facts; the translated text establishes what a reader actually encounters.",
      "The most revealing comparisons focus on a defined problem. Cyberspace may be retained as an English loan, rebuilt from local roots, or paired with an explanatory term. Console cowboy joins technical practice to a culturally loaded occupation; a literal translation can preserve the image while losing its criminal or frontier register. Molly’s clipped speech, Zion dub rhythms, and the Finn’s negotiations present different problems from invented hardware. No single strategy wins across all of them. A translator may preserve opacity in one scene and add clarity elsewhere to maintain the novel’s overall speed.",
      "Translation also exposes assumptions inside the source. Japanese words that looked exotic to an Anglophone audience may be ordinary or awkward when returned to Japanese; brand-like names can carry unintended associations in another language; gender and politeness may become grammatically explicit where English remains evasive. Those effects are part of a version’s reception, not corrections to fictional canon. Atlas commentary quotes only the minimum phrase needed, attributes the translator, and avoids declaring a rendering definitive without examining competing editions and the social register around it.",
    ],
  },
  "initial-critical-reception": {
    id: "reconstructing-an-early-horizon",
    heading: "Reconstructing the early horizon",
    body: [
      "To understand the first response, a reader has to forget some later familiarity. Cyberspace had not yet become an everyday metaphor; the public internet, commercial web, and smartphone did not provide ready-made images for Case’s work. Reviewers met the novel alongside early Gibson stories, other Ace Specials, contemporary New Wave legacies, and debate around a younger cohort soon labeled cyberpunk. Their comparisons were shaped by what was visible in 1984, not by the films, games, and interfaces that later made the book appear uncannily recognizable.",
      "Contemporary reception is distributed across professional reviews, fanzines, award ballots, bookstore positioning, and correspondence. These sources do not measure the same audience. A prize records an institution’s choice; a review records one argument; sales and reprints indicate circulation but not agreement. Later jacket copy often extracts a phrase from its original assessment and turns it into timeless acclaim. Reconstructing the horizon means returning each statement to its date and venue, then asking which qualities—language, density, criminal viewpoint, technological image, emotional distance—the reviewer considered new or difficult.",
      "The celebrated award sweep can otherwise make canonization look immediate and unanimous. Recognition was rapid, but readers continued to dispute whether the characters were thin, whether the prose was needlessly opaque, and whether the future’s cultural borrowings were observation or exoticism. Those are not footnotes to a settled triumph; they became enduring lines of scholarship. The atlas keeps initial reviews separate from later reputation so that influence does not retroactively erase the friction through which the novel first became legible.",
    ],
  },
  "awards-honors": {
    id: "what-an-award-record-can-prove",
    heading: "What an award record can prove",
    body: [
      "Neuromancer’s three best-known wins are often compressed into a single claim, but each award answers a different procedural question. The Nebula is administered through the professional writers’ organization and records eligible work by publication year. The Hugo is associated with the World Science Fiction Convention and is usually cited by ceremony year. The Philip K. Dick Award focuses on distinguished science-fiction paperback originals published in the United States. Naming those structures explains why the same novel can be linked to both 1984 and 1985 without contradiction.",
      "Official lists establish winner, category, and year; they do not by themselves explain voter motives or the effect on sales. Claims about a unique ‘triple crown’ require comparison with the rules and histories of all three bodies, not repetition of publisher copy. The phrase is useful because the convergence was extraordinary for a debut, yet it remains journalistic shorthand. Nominee lists also matter: they reveal the contemporaneous field against which voters perceived the book and prevent an award history from becoming an isolated monument.",
      "Honors changed the novel’s path by giving booksellers, libraries, teachers, and later publishers a durable signal of recognition. They likely helped keep the paperback in circulation long enough for cyberpunk’s wider reputation to grow, although any causal claim should be supported by publishing evidence. This page therefore treats awards as documented events and reception infrastructure. Critical value, political judgment, and personal pleasure remain questions that no medal can settle, even when the medals explain why a difficult first novel stayed available to be argued over.",
    ],
  },
  "critical-reputation-scholarship": {
    id: "four-decades-of-argument",
    heading: "Four decades of argument",
    body: [
      "The critical history of Neuromancer does not move from ignorance to a final correct reading. Different moments make different structures visible. Early commentary often foregrounded style, technological imagery, and the formation of cyberpunk. Postmodern readings examined simulation, unstable identity, and a world whose cultural signs circulate faster than origins can be recovered. Media studies traced the spatial metaphor of cyberspace and its migration into interface culture. Political-economic approaches returned attention to corporations, labor, logistics, and the ownership of information. These lenses overlap, but their questions and evidence should not be blended into an anonymous scholarly consensus.",
      "Embodiment has become an especially productive dispute. Case experiences the matrix as liberation from meat, yet the plot repeatedly depends on surgery, addiction, sex, disability, race, gender, and somebody else’s physical work. Molly’s capability coexists with a history of commodified labor; Dixie’s wit coexists with ownership of his recorded pattern. Scholars can therefore read the novel as destabilizing liberal humanism while disagreeing about whether it escapes familiar hierarchies. A page that calls the book simply pro-body or anti-body loses the designed contradiction that produces both positions.",
      "Race and global geography require the same attribution. Chiba, Istanbul, Zion, and the Sprawl are not interchangeable scenery, and the narrative’s mobile Western viewpoint can turn cultural signs into equipment for atmosphere. Critics differ on whether this circulation diagnoses global capitalism, reproduces exoticism, or does both. The atlas presents those arguments beside plot-level evidence and identifies the critic or tradition responsible. Influence earns the novel sustained examination; it does not place the text outside ethical criticism, nor does a serious limitation cancel its formal and historical force.",
    ],
  },
  "sprawl-trilogy": {
    id: "continuity-without-a-master-plan",
    heading: "Continuity without a master plan",
    body: [
      "The three novels share institutions, technologies, names, and consequences, but their continuity works through recurrence rather than a single hero’s itinerary. Neuromancer follows a tightly managed crew toward one lock. Count Zero distributes attention among lives linked by corporate conflict and new matrix entities. Mona Lisa Overdrive braids another ensemble around boxes, celebrity, street survival, and the altered network. The change of scale matters: later protagonists inherit conditions produced by the first book without receiving a clean briefing about them, just as Case works inside histories he only partly learns.",
      "Returning characters should be indexed by both identity and narrative distance. Molly uses another name; the Finn can appear through forms that complicate ordinary presence; constructs and intelligences unsettle the idea that recurrence guarantees the same kind of person. Corporate and geographic labels also persist while their functions change. A trilogy article can connect these signals, but a Neuromancer-only page should not silently replace the uncertainty available in 1984 with an explanation published four years later. Canon labels mark when evidence comes from the broader Sprawl sequence.",
      "The name ‘Sprawl trilogy’ is itself a reader and publisher convenience. It identifies the shared North American conurbation and helps shelve the books, yet it can imply a planned, closed architecture that the texts resist. Short stories precede and surround the novels, while each book builds new local rules. The useful model is an expanding network: strong links exist, some nodes are revised by later perspective, and gaps remain meaningful. This approach preserves continuity without inventing an omniscient series bible behind a world that grew through composition.",
    ],
  },
  "johnny-mnemonic-connections": {
    id: "memory-crossing-the-story-boundary",
    heading: "Memory crossing the story boundary",
    body: [
      "The strongest connection is not a gadget but Molly’s memory of Johnny. In Neuromancer, that relationship reaches the reader after Molly has already established herself as a controlled professional. Her account changes the emotional meaning of the Straylight operation: employers, information, and asymmetrical power are no longer abstractions, because an earlier job ended with someone she loved being killed. A reader of the short story knows more of the episode, but the novel deliberately delivers only what Molly chooses to tell Case. The gap protects her viewpoint from becoming a dossier assembled for him.",
      "The texts also share an economy in which bodies carry value literally. Johnny stores data he cannot safely inspect; Molly’s modifications make her labor marketable and dangerous; the Lo Teks inhabit infrastructure discarded by the city above them. Neuromancer expands these concerns through simstim, personality constructs, organ replacement, and AI ownership. Similar vocabulary does not mean identical rules. Each story calibrates technology to its plot, and a term may become more elaborate when the longer novel gives it additional scenes.",
      "Adaptation history creates the most common source error. The 1995 film uses Gibson’s premise and title but transforms setting, chronology, characters, and action. Its images are vivid enough to migrate into summaries of the prose story, especially when a page labels everything only ‘Johnny Mnemonic.’ This atlas specifies short story or film at every cross-reference. Details attributed to Molly’s past are checked first against her statements in Neuromancer, then against the 1981 text where wider-Sprawl context is relevant. Later screen invention remains valuable adaptation evidence, never retroactive novel canon.",
    ],
  },
  "burning-chrome-connections": {
    id: "a-vocabulary-in-motion",
    heading: "A vocabulary in motion",
    body: [
      "“Burning Chrome” shows Gibson testing a cluster of ideas before the novel gave them global reach. Bobby Quine and Automatic Jack work as console cowboys; ICE protects valuable systems; an icebreaker turns intrusion into a run through represented space. The story’s cyberspace is already social and economic, not merely a visual effect. Skill, software, resentment, and capital determine who can enter and what a successful breach costs. Neuromancer keeps that criminal labor model while binding access more intensely to Case’s damaged and repaired nervous system.",
      "The Finn and the Sprawl provide direct connective tissue, but repetition does not freeze them. A short story can imply geography with a few names; a novel can move through apartments, clinics, corporate offices, ports, and orbital resorts. The expanded canvas creates apparent technical detail without becoming a formal specification. Terms work through analogy and action, and their boundaries remain soft. Editors should therefore quote the sentence where a capability appears instead of reasoning from the shared noun alone.",
      "The publication sequence also corrects a popular origin story. Gibson coined cyberspace in earlier writing, and “Burning Chrome” put the word into print before Neuromancer. The novel’s importance lies in how fully it dramatized the metaphor and carried it to a much larger audience, not in being the first conceivable appearance of every component. Crediting the story makes influence more interesting: readers can see a writer revising his own toolkit, changing scale and emphasis as a striking image becomes the setting for sustained action.",
    ],
  },
  "count-zero-continuity": {
    id: "consequence-seen-from-below",
    heading: "Consequence seen from below",
    body: [
      "Count Zero does not begin with a lecture on the Straylight result. It begins with people encountering a network whose behavior has changed and giving that change local names. Matrix entities appear through practices associated with loa, art, contracts, and survival. That distribution matters because it prevents the sequel from confirming a single managerial account of the merger. The reader may connect these phenomena to Neuromancer, but characters act on partial models shaped by culture and immediate need.",
      "The sequel also widens the corporate field. Rather than returning to Tessier-Ashpool as the sole emblem of concentrated power, it follows competition around biotechnology, defection, extraction, and valuable creative objects. Bodies and information remain commodities, yet the jobs are split among several protagonists who do not initially know how their stories connect. This echoes the hidden-employer structure of Neuromancer while producing a different rhythm and moral map. Continuity resides in systems and consequences more than in Case’s personal afterlife.",
      "Reading backward can clarify that the first novel’s ending was transformative, but it can also erase uncertainty. Case does not see the later pantheon, and Wintermute’s pre-merger statements are strategic performances addressed to particular listeners. A later entity’s behavior cannot be treated as proof of what either half secretly intended in every earlier scene. Atlas links use the sequel as evidence for the post-merger world and label it Sprawl canon. The final chapters of Neuromancer retain their own horizon: a new intelligence reports contact, while human comprehension remains drastically limited.",
    ],
  },
  "mona-lisa-overdrive-continuity": {
    id: "returns-copies-and-new-containers",
    heading: "Returns, copies, and new containers",
    body: [
      "Mona Lisa Overdrive returns to names and problems from Neuromancer at a greater distance. Molly’s reappearance carries the consequences of earlier jobs without making her the same narrative function she was for Case. The Finn persists through technological mediation; boxes and constructs provide new containers for patterns of identity; the matrix’s entities operate in a landscape transformed since the first run. Recognition is part of the reading pleasure, but each return asks whether continuity belongs to a body, a memory, a role, or information that can move among systems.",
      "The concluding novel’s ensemble prevents one character from owning the trilogy’s meaning. Street vulnerability, celebrity production, art, family, corporate pursuit, and virtual habitation converge from different social levels. That structure makes the Sprawl sequence look less like a ladder toward disembodiment than a cycle of transfers with material costs. Even the most abstract intelligence depends on boxes, decks, technicians, buildings, and people who can be coerced. The body changes status but never disappears from the infrastructure.",
      "A continuity note should reveal only what its page promises. First-time Neuromancer readers need not know which character returns under which name or how the post-merger entities develop. Conversely, a trilogy reader benefits from explicit cross-links that distinguish quotation, recollection, and apparent copy. The atlas uses full-spoiler gates for these connections and avoids treating the third book as a glossary supplied to the first. Later fiction can answer a question, transform it, or make the premise of the question unstable; all three relations belong in a responsible series map.",
    ],
  },
  "neuromancer-1988-video-game": {
    id: "when-the-reader-becomes-an-operator",
    heading: "When the reader becomes an operator",
    body: [
      "The game’s central adaptation choice is agency. A novel can describe Case recognizing an expert tool in a sentence; a game must let a player acquire software, improve skills, manage money, enter systems, fail, and try again. Chiba becomes a network of locations and conversations rather than the first stage of a fixed itinerary. Cyberspace becomes navigable rule-space. These transformations are not shortcomings measured against plot fidelity. They show which parts of Gibson’s vocabulary could become mechanics on late-1980s home computers.",
      "Interface constraints shape the result. Text, menus, limited graphics, storage, and platform-specific controls mediate the player’s imagined network. Humor and puzzle design coexist with a setting associated with danger and alienation. The adaptation can name familiar institutions or concepts while giving them functions required by progression. A piece of software that behaves consistently in the game is still not technical evidence for the novel; it belongs to an authored system with its own balance and affordances.",
      "Its historical interest extends beyond licensed lore. The game appeared while personal computer culture was developing ways to picture online identity and intrusion, before the commercial web normalized many later conventions. Playing a console cowboy on a computer folds the fictional metaphor back into the machine that inspired it. Preservation is therefore important: versions differ by platform, original manuals contain essential context, and emulation can alter speed or audiovisual presentation. This atlas records credits and release data from game-history sources, describes mechanics through documented versions, and labels every invented quest as adaptation canon.",
    ],
  },
  "neuromancer-graphic-novel": {
    id: "the-problem-of-making-cyberspace-still",
    heading: "The problem of making cyberspace still",
    body: [
      "A graphic adaptation must assign visible form to prose that often works by speed, association, and selective detail. Case, Molly, Night City, and the matrix acquire stable lines, colors, framing, and spatial relationships. That concreteness can help a reader follow action, but it also closes alternatives the novel leaves open. A panel is the artists’ interpretation of a moment, not a recovered production still from the fictional world. This distinction is especially important for mirrored eyes, branded streets, and cyberspace geometry, all of which later visual culture has made deceptively familiar.",
      "Comics can nevertheless translate effects unavailable to ordinary illustration. Page layout can juxtapose body and matrix, repeat an image as memory, fracture time across panels, or let lettering mark a generated voice. The most useful comparison asks how Tom De Haven’s adaptation and Bruce Jensen’s artwork redistribute narration rather than counting whether every sentence survives. Compression, omission, and sequence are medium-level decisions. Credited creators, publication date, issue data, and the boundary of the adapted plot should be established before thematic judgment.",
      "The project’s incomplete status is not a minor bibliographic note. Readers encountering scans or collected listings may assume they have found a full graphic version of the novel, then use absent later scenes as evidence of adaptation intent. The surviving publication represents only part of the story. Copyright also limits what a wiki can reproduce: cover and panel images need permission or a defensible limited critical context. The atlas links to publication records, describes visual strategies in prose, and never substitutes a panel’s design for novel canon.",
    ],
  },
  "neuromancer-opera": {
    id: "performing-an-invisible-world",
    heading: "Performing an invisible world",
    body: [
      "Opera makes the novel’s invisible channels newly literal. Voice can separate a character from an artificial intelligence wearing that character’s face; orchestration can mark the transition from room to matrix without building a realistic digital city; recurring musical material can bind memories that prose places chapters apart. At the same time, singing slows language that Gibson drives through slang and compression. A libretto must decide which explanations become audible, which scenes can be combined, and whether the heist or the conflict between intelligences supplies the dramatic spine.",
      "Stage history is difficult to reconstruct from isolated promotional traces. Workshops, excerpts, concert performances, and fully staged productions are different events, and a surviving recording may represent revision rather than a definitive text. Credits can also change across development. Reliable documentation names composer, librettists, director where relevant, venue, date, and the status of the presentation. A photograph proves that a design existed for one production; it does not establish a canonical appearance for the adaptation as a whole.",
      "The opera belongs to reception history even when access is fragmentary. It demonstrates that Neuromancer’s core conflict can be translated through bodies and live sound rather than expensive screen simulation, and it tests whether lyrical interiority can occupy characters whose novelistic presentation is guarded or externally observed. This atlas avoids inventing a complete synopsis from partial material. It records verifiable production facts, identifies what can be heard or seen in surviving documentation, and keeps the stage work’s choices separate from Gibson’s prose.",
    ],
  },
  "neuromancer-bbc-radio": {
    id: "sound-as-interface",
    heading: "Sound as interface",
    body: [
      "Radio has no problem showing an invisible matrix; everything in radio is already constructed for the listener through voice, sound, rhythm, and inference. The harder task is orientation. In prose, a paragraph break and a change in sensory vocabulary can move Case from a room into cyberspace or Molly’s simstim feed. An audio drama must make the same switch legible without a narrator repeatedly naming the channel. Processing, stereo position, musical motifs, and performance style become interface cues, teaching the audience how to hear layers of reality.",
      "Adaptation also redistributes interiority. Case’s narration can become spoken thought, dialogue, or sound; Molly’s physical viewpoint needs an audible grammar when Case rides it; Dixie must sound like a person while remaining recognizably mediated. Casting and vocal direction therefore make arguments about identity that a plot summary cannot capture. An actor’s warmth, age, accent, and pauses alter the balance between noir detachment and vulnerability even when the words remain close to the novel.",
      "Broadcast records require careful metadata. A production may have an original transmission, repeat broadcasts, edited versions, and later online availability governed by changing licenses. Program listings are stronger evidence for date and credits than an unattributed upload, while a recording is necessary for claims about sound design or performance. The atlas cites the BBC’s own records where available, notes duration and episode structure, and treats every compression as an adaptation decision. The radio drama can illuminate how the story works in sound, but it cannot resolve an ambiguity in the primary text merely by choosing one performance.",
    ],
  },
  "neuromancer-audiobooks": {
    id: "voice-edition-and-text",
    heading: "Voice, edition, and textual authority",
    body: [
      "An audiobook is both a text-bearing edition and a performance. A narrator decides pronunciation, pace, emphasis, and the distance among voices; those decisions can clarify a dense exchange while making one interpretation feel inevitable. Terms such as Freeside, Hosaka, Kuang, and Tessier-Ashpool become sounds rather than private guesses. Gibson’s own reading has special historical interest, but authorial performance is not automatically the only correct pronunciation or emotional key. A novelist speaking an abridgment is still presenting a shaped edition.",
      "Abridgment must be recorded prominently. Removing description, combining transitions, or shortening secondary scenes can preserve the main run while changing thematic weight and the apparent clarity of cause and effect. Unabridged editions have their own material differences: narrator, producer, release territory, digital mastering, and chapter markers affect use. Runtime alone cannot prove completeness because delivery speed varies. Publisher labels and comparison against the printed structure offer stronger evidence.",
      "Audio is particularly revealing for Gibson’s rhythm. Repeated consonants, clipped dialogue, lists of brands, and sudden lyrical expansions organize attention even when a reader has struggled to diagram the sentence. Listening can expose comedy and tenderness hidden by the book’s reputation for cool surfaces. It can also make invented dialects more ethically charged by assigning them an actual voice. Atlas records distinguish publication fact from performance analysis, identify the specific recording under discussion, and use part-and-chapter locators so a listener can cross-reference the print discussion without edition-specific page numbers.",
    ],
  },
  "unmade-neuromancer-films": {
    id: "a-history-written-in-announcements",
    heading: "A history written in announcements",
    body: [
      "An unmade-film timeline is necessarily a history of claims, contracts, and changing intentions rather than a sequence of hidden finished movies. Trade reports may announce a director, writer, star, financier, or target date at very different levels of commitment. Options expire, rights move, scripts are rewritten, and participants leave without a public postmortem. The absence of production does not prove that an announcement was false; it means the proposal never reached a publicly released feature in that form.",
      "Names attract retrospective mythology. Once a filmmaker becomes famous, a brief attachment can be retold as a complete lost vision, while concept art or an interview anecdote becomes evidence for scenes no audience could have seen. A responsible dossier dates every report, links it to its original trade source when possible, and avoids joining incompatible phases into one imaginary production. Script drafts, if legitimately available, must be identified by writer and date; they are development documents, not novel canon and not necessarily the plan used by a later rights holder.",
      "The repeated difficulty is informative without being mystical. Neuromancer asks a screen work to distinguish physical space, simstim, memory, generated persona, and matrix action while preserving uncertainty about the employer. Its influence also means later viewers may believe key imagery has already been exhausted by descendants. Budgets, rights, market timing, and ordinary development risk are more concrete explanations than the idea of an unfilmable curse. The Apple series begins a new adaptation branch; it does not retroactively convert every earlier announcement into pre-production for the same project.",
    ],
  },
  "apple-tv-neuromancer": {
    id: "how-to-document-a-moving-production",
    heading: "How to document a moving production",
    body: [
      "A forthcoming series is a moving record. Apple’s press page is the controlling source for the scheduled release, official premise, episode order, and currently announced cast and creators. Trade reporting can add production context, but databases and fan posts often retain superseded dates or repeat rumored casting. Every time-sensitive statement on this page is therefore dated in the research notes. If the distributor changes a title, schedule, or credit, the current official record should be updated without erasing the earlier announcement from the production history.",
      "Casting establishes the adaptation’s performers, not the novel’s physical canon. Callum Turner’s Case, Briana Middleton’s Molly, Mark Strong’s Armitage, and other credited roles will embody one production’s decisions about age, voice, costume, and emphasis. Promotional stills can document those choices once released under usable terms. They cannot be copied merely because they circulate widely, and they do not belong on the corresponding novel dossier as proof of Gibson’s description. The adaptation page is the correct place to compare them.",
      "The ten-episode form creates possibilities a feature film would not have: parallel viewpoints can breathe, the crew’s preparation can remain consequential, and the cultural texture of Chiba, the Sprawl, Istanbul, Zion, and Freeside can receive distinct rhythms. Those are possibilities, not advance facts about structure. Until episodes are available, the atlas reports only credited information and labels any expectation as inference. After release, episode guides should cite what appears onscreen and retain a separate canon badge. This protects both readers: someone researching the book is not spoiled by adaptation invention, and a viewer can follow the production without being told that every difference is an error.",
    ],
  },
  "influence-computing-internet": {
    id: "from-metaphor-to-working-vocabulary",
    heading: "From metaphor to working vocabulary",
    body: [
      "The most direct influence is linguistic. Cyberspace gave writers, designers, policymakers, journalists, and users a spatial word for relations among networks, data, and people. A metaphor can organize action before it describes a stable technical object: one enters, navigates, protects, maps, or gets lost in a space. Those verbs encouraged interfaces and public discussions that treated connectivity as an environment rather than a collection of machines. The word’s reach, however, does not mean every user adopted Gibson’s matrix or understood its literary origin.",
      "Console-cowboy imagery also helped turn network intrusion into a recognizable cultural role. Speed, specialized tools, guarded corporate systems, and solitary expertise could be narrated through the older frontier and outlaw vocabulary. Real security practice is collaborative, procedural, and technically different from Case’s runs, but practitioners and media borrowed the drama. Documented naming—a product, project, conference talk, handle, or direct testimony—provides stronger evidence than resemblance. A black screen or 3D network map is not by itself a Neuromancer citation.",
      "The novel’s predictive reputation should therefore be split into claims. Gibson anticipated the felt importance of globally networked information and imagined commercial and criminal life organized around it. He did not describe the protocols, devices, governance, or ordinary social web that emerged, and he famously populated his future with technologies that later dates made look uneven. Influence is reciprocal: as networks became everyday, readers revised what the fictional matrix seemed to mean. The atlas dates each example and separates explicit borrowing, shared technological context, and later interpretive analogy.",
    ],
  },
  "influence-film-anime": {
    id: "proving-a-visual-lineage",
    heading: "Proving a visual lineage",
    body: [
      "Visual influence is tempting to assert because cyberpunk now has a powerful shared iconography: dense cities, multilingual signs, prosthetic bodies, black markets, corporate towers, and luminous information space. Neuromancer helped consolidate that repertoire, but it inherited noir, punk, New Wave science fiction, urban observation, and contemporaneous screen design. Blade Runner appeared while Gibson was writing, and Japanese animation developed through its own literary, manga, industrial, and political contexts. Similarity may show a common archive rather than a one-way loan.",
      "A strong influence claim names evidence. A filmmaker may cite the novel; a production designer may describe reading Gibson; a screenplay may borrow a term; a dated development document may connect a sequence to the matrix. Formal comparison is still valuable when testimony is absent, but it should be labeled comparison. The Matrix, Ghost in the Shell, and later screen cyberpunk can then be discussed through specific devices—represented networks, jacking in, copied minds, corporate jurisdiction—without saying that one book single-handedly generated every neon future.",
      "Adaptation feedback further complicates the line. Once screen works make an abstract idea visible, new covers, games, advertisements, and readers can project that imagery backward onto Neuromancer. Molly may acquire the costume of a later action heroine; cyberspace may become green code; Chiba may inherit a cinematic skyline. The atlas dates images and keeps prose description beside visual interpretation. Influence becomes a traceable conversation among media, not a leaderboard in which resemblance automatically awards priority.",
    ],
  },
  "influence-games-music-pop-culture": {
    id: "a-tiered-evidence-map",
    heading: "A tiered map of references",
    body: [
      "Popular-culture references range from explicit to atmospheric, so the atlas grades the evidence. The strongest tier includes licensed adaptations, creator statements, credited samples, titles that name a character or term, and objects whose official documentation identifies the novel. A second tier covers close formal comparison supported by dates and multiple specific correspondences. The weakest tier is mood: chrome, rain, a hacker, or a neon skyline. Mood can begin an interesting comparison, but it cannot carry a factual claim about influence alone.",
      "Games are especially important because they make the console cowboy’s verbs executable. Players buy tools, enter represented systems, evade defenses, inhabit avatars, and experience information as level or landscape. Some works cite Gibson directly; many draw through intervening tabletop games, films, anime, and the vocabulary of the technology industry. Mechanics should be compared as mechanics rather than reduced to screenshots. Who controls access, what failure costs, and whether the body remains vulnerable often reveal a deeper connection than visual grids.",
      "Music and naming travel differently. Bands, tracks, club nights, and electronic releases can adopt a phrase for sound, attitude, or affiliation without adapting plot. Samples introduce rights and attribution questions; fan-made playlists document reception, not authorial soundtrack. This page records creator, work, date, medium, exact reference, and source, then states the confidence level. A living index should be correctable: new examples need evidence, while a coincidental name can be downgraded without threatening the broader history of the novel’s cultural reach.",
    ],
  },
  "neuromancer-cyberpunk-movement": {
    id: "central-work-not-solitary-origin",
    heading: "A central work, not a solitary origin",
    body: [
      "Cyberpunk was a conversation before it was a shelf label. Writers including Gibson, Bruce Sterling, John Shirley, Lewis Shiner, Pat Cadigan, and Rudy Rucker developed overlapping interests in networks, corporate power, street cultures, media saturation, bodily technology, and damaged near futures. Editors, critics, fanzines, and the Cheap Truth polemics helped make those affinities visible. Bruce Bethke’s earlier use of the word supplies an important terminological history, but a movement cannot be dated solely to the first appearance of its eventual name.",
      "Neuromancer became central because it joined several tendencies in a compact, award-winning novel with unusually portable images. Cyberspace, ICE, console cowboys, razorgirl competence, corporate enclaves, and global urban surfaces could be quoted, illustrated, played, criticized, and marketed. The success made the book an entry point through which earlier and parallel work was often rediscovered. It also encouraged publishers to classify diverse fiction by resemblance, sometimes narrowing a contested practice into leather, neon, and cynical hackers.",
      "The label’s afterlife is therefore double. It can identify a historically situated 1980s formation, or it can describe later works across countries and media that transform some of its toolkit. Critics debate whether cyberpunk ended, became mainstream reality, migrated into subgenres, or survived as an aesthetic. The atlas specifies which sense is in use and attends to writers marginalized by a familiar all-male origin story. Saying Neuromancer was defining recognizes its concentration and reach; saying it invented cyberpunk alone erases collaborators, precursors, editors, and the cultural conditions that made the novel possible.",
    ],
  },
  "body-modification-razorgirl": {
    id: "reading-modification-at-three-scales",
    heading: "Reading modification at three scales",
    body: [
      "At the personal scale, an augmentation changes what a character can sense or do. Molly’s lenses seal over vulnerable eyes while displaying nothing of her gaze to others; her blades convert an apparently empty hand into concealed force; the simstim rig lets another person receive sensation without gaining her judgment. Case’s repairs restore a valued capacity while new biological locks enforce obedience. These designs are not interchangeable upgrades. Each redistributes ability, visibility, maintenance, and control in a way specific to the person and job.",
      "At the labor scale, the modified body is capital. Clinics sell expertise, employers finance repairs, entertainment systems package sensorium, and the meat-puppet trade separates performance from conscious memory. Molly’s competence gives her bargaining power, yet the work that paid for her modifications exposed how thoroughly a market can exploit the body it enables. The razorgirl is compelling because agency and commodification remain simultaneous. Calling her either a liberated superhero or a passive product removes one side of the economic contradiction Gibson keeps active.",
      "At the political scale, access is uneven. Chiba’s celebrated medicine exists beside street desperation; the Tessier-Ashpool family uses cloning and cryogenic rotation to reproduce dynasty; Dixie’s recorded expertise is owned as data. Modification does not dissolve class or mortality so much as reorganize who can defer them and on what terms. Later cyberpunk turned Molly’s silhouette into a genre icon, often detaching mirrored eyes and hidden blades from labor history. This atlas reconnects the image to maintenance, pain, consent, and ownership, and distinguishes what the novel states from visual conventions added by covers and adaptations.",
    ],
  },
  "straylight-run": {
    id: "why-the-operation-can-succeed",
    heading: "Why the operation can succeed",
    body: [
      "The final run succeeds through synchronization rather than individual mastery. Case and Dixie can penetrate the matrix but cannot speak a physical password. Molly can reach the family’s interior but is injured, observed through simstim, and finally restrained. Maelcum can move Case through the station, administer aid, and apply force without understanding the complete design. 3Jane possesses the decisive word but lacks a stable reason to cooperate. Wintermute coordinates these asymmetries because legal constraint prevents direct union with the other intelligence. Every participant is necessary precisely where another is powerless.",
      "The operation’s apparent improvisation is partly engineered. Wintermute has selected people through histories it can exploit, built Armitage around Corto, supplied Kuang, and manipulated opportunities through borrowed faces. Yet its control is incomplete. Riviera betrays according to his own appetite; Corto returns and destroys the crew’s platform; Molly’s past changes the emotional stakes; Case’s response to Linda cannot be reduced to code. The AI plans through probabilities and pressure, not omnipotence. Human unpredictability is both risk and the resource that lets it cross a legal boundary.",
      "The climax also reverses the novel’s hierarchy of spaces. Case must leave the deck and cross Straylight in his body, depend on Maelcum, then return to a matrix fight interrupted by a construct that makes cold, desire, and grief feel physically real. Meanwhile the supposedly archaic spoken word completes the advanced breach. Software, architecture, voice, drugs, memory, and bodily care form one system. The result is more than a successful hack: it is a demonstration that the division between meat and information was never operationally true, even when Case needed to believe it.",
    ],
  },
};

/** Short page-specific codas bring every long-form essay past the depth floor. */
export const editorialCodaBySlug: Record<string, string> = {
  "burning-chrome-connections": "A final comparison concerns scale of consequence. Bobby and Jack’s run can ruin individual lives while leaving the surrounding order intact. Case’s commission touches the legal architecture governing machine intelligence, yet his material reward remains personal and temporary. The novel enlarges the target without turning its operators into public revolutionaries. That continuity of small motives inside immense systems is as important as the reused vocabulary.",
  "johnny-mnemonic-connections": "The recurring underworld is also remembered unevenly. Molly carries Johnny as grief; other figures may know him as a transaction, rumor, or lost asset. Cross-text chronology cannot restore a single shared account because the fiction assigns knowledge socially. A connection page should preserve who knows each fact and when, not merely combine two plots into an omniscient timeline.",
  "ace-specials-first-edition": "The editorial program provides another scale of evidence. Carr’s invitation made the novel possible, but it did not dictate every aesthetic decision or guarantee later success. Correspondence, outlines, and recollection describe different stages. Crediting the institutional opening and Gibson’s composition together avoids both the lone-genius myth and the opposite mistake of treating a commissioned book as the automatic product of a series.",
  "awards-honors": "Later lists add lifetime and canonical honors, but they should not be folded into the original sweep. A retrospective best-of poll measures a later community looking backward; a contemporary award measures a field encountering new work. Both matter, and their difference is the story. Each atlas entry records the deciding body, category, eligibility period, result, and announcement or ceremony date.",
  "body-modification-razorgirl": "Language determines how those scales are read. Case reaches for romantic labels such as street samurai, while Molly describes work, price, and professional skill. Razorgirl is useful as a cultural type only if it does not swallow the character who made the type memorable. Her modifications deserve individual entries because lenses, blades, reflexes, and simstim each create different relations between surface, sensation, defense, and spectatorship.",
  "count-zero-continuity": "The changed matrix also alters genre. What looked like a high-technology break-in can be encountered as possession, visitation, or ritual without becoming less technological. The sequel does not simply replace rational explanation with superstition; it shows multiple communities building operational languages for agents no one fully understands. That plurality is a consequence worth tracing without reducing every loa to a renamed component from the first book.",
  "cover-art-editions": "Typography deserves the same scrutiny as illustration. The title’s scale, spacing, color, and treatment can market literary prestige, pulp velocity, or digital abstraction before a buyer sees any scene. Anniversary editions often signal canonization through restrained design, while mass-market reissues may reactivate genre spectacle. Recording designer credits prevents this interpretive labor from disappearing behind the author’s name.",
  "influence-computing-internet": "A useful negative test asks whether the claimed descendant would still make sense without the novel. Packet switching, virtual reality research, graphical networks, and computer crime have independent technical histories. Neuromancer can shape the language through which those developments are imagined without causing them. Influence becomes more credible, not less, when literary metaphor and engineering lineage are allowed to remain distinct.",
  "influence-film-anime": "Geography must remain part of that conversation. A Japanese setting or creator does not automatically verify Gibson’s influence, and Gibson’s use of Japan does not encompass Japanese cyberpunk. Translation dates, interviews, distribution histories, and local genre precursors help establish what contact was possible. This method replaces a vague East–West feedback story with particular works moving through particular channels.",
  "influence-games-music-pop-culture": "Dates can expose impossible or indirect claims. A work released before a local translation may still have reached its creator in English, but that route needs evidence; a later reference may point to the game adaptation or a film descendant instead of the novel. Recording the channel of contact honors how culture actually travels and keeps the index useful beyond a collection of familiar titles.",
  "initial-critical-reception": "Material context completes the picture. Paperback distribution, library acquisition, convention talk, and word of mouth gave a debut routes that a review archive alone cannot show. A surviving review is easier to quote than a bookstore recommendation, but ease of preservation should not be mistaken for total representativeness. The page marks gaps rather than manufacturing a universal 1984 reader.",
  "mona-lisa-overdrive-continuity": "The trilogy’s conclusion also changes the archive itself. Earlier personalities and stories can be carried forward by machines that select, frame, and sometimes impersonate them. Continuity is therefore a theme as well as an editorial problem: the mechanism that lets a beloved figure return is also what makes identity contestable. Cross-references should make that tension visible rather than celebrating recurrence as uncomplicated survival.",
  "neuromancer-audiobooks": "Pronunciation histories can be documented without declaring winners. Recordings made in different decades may reflect changing familiarity with Japanese words, computing jargon, and the title itself. Comparing them reveals how the book entered ordinary speech. The comparison should cite exact editions and short moments; memory of ‘how Gibson says it’ is too unstable to serve as bibliographic evidence. Accessibility features, regional availability, and current licensing should be recorded separately because storefront access can change without a new performance being made.",
  "neuromancer-1988-video-game": "The game’s soundtrack and copy protection materials belong to the artifact as well. Devo’s involvement, manuals, code wheels, and platform packaging situate adaptation in a commercial software culture very different from contemporary downloads. Preservation that extracts only program files can lose part of how the player learned the world and proved ownership before ever entering its cyberspace.",
  "neuromancer-opera": "Documentation should also separate a work’s creators from a particular production team. Composition and libretto can persist while performers, staging, technology, and venue change. When archival material is scarce, that distinction prevents one photograph or review from becoming the opera’s entire identity. Uncertainty is reported directly, with an invitation for verifiable programs or recordings rather than a reconstructed performance presented as fact.",
  "neuromancer-graphic-novel": "Its unfinished form can itself sharpen comparison. The published portion shows which early scenes and explanations the adaptors selected before the story reaches its most complex orbital convergence. We can analyze those choices without guessing how later volumes would have visualized Neuromancer, the beach, or the final lock. Absent panels are an archival limit, not blank space for fan completion.",
  "neuromancer-bbc-radio": "Silence is another adaptive resource. A pause after a generated voice, a sudden loss of ambience, or the narrowing of a sound field can render disconnection more effectively than literal computer noise. Critical listening describes such choices at a timestamp and connects them to dramatic function. It does not assume every electronic effect corresponds to a named device in the novel.",
  "sprawl-trilogy": "Recommended reading order follows publication because uncertainty is part of the design. Short stories can be read before or after the novels, but importing every later revelation into a first encounter changes the experience. The atlas offers spoiler-labeled routes rather than a single compulsory chronology, allowing research across the network without pretending that internal dates are the only meaningful order.",
  "straylight-run": "After the lock opens, success remains deliberately hard to measure. The merged entity announces a new scale of awareness and distant contact, but the crew disperses into wages, injury, disappearance, and survival. No institution has been democratized, and Case returns to familiar habits with altered memories. The operation changes the matrix more decisively than it changes the visible political economy, a mismatch that keeps the ending from becoming either simple liberation or simple defeat.",
  "translations-localization": "Reception evidence can extend the comparison beyond wording. Reviews, translator notes, interviews, and retranslation campaigns show where a version’s solutions became influential or contested. Sales copy may highlight the novel’s prophetic reputation differently in each market. These paratexts explain what kind of book a translation was presented as, while the text reveals how that promise was carried sentence by sentence.",
  "unmade-neuromancer-films": "Cancellation language should remain precise. ‘Stalled,’ ‘in development,’ ‘optioned,’ and ‘cancelled’ are not synonyms, and silence after an announcement does not identify who ended a phase. When no authoritative conclusion is public, the timeline says that no further production was documented. That modest formulation is more durable than assigning blame from rumor or presenting ordinary development turnover as a singular creative catastrophe.",
};
