import { buildFandomMicroArticle, type FandomMicroRecord } from "./fandom-micro-builder";

const records: FandomMicroRecord[] = [
  {
    slug: "ali",
    title: "Ali",
    fandomTitle: "Ali",
    category: "Characters",
    spoiler: "Moderate",
    description: "The Istanbul supplier whose alley shop makes Riviera’s drug dependence part of Molly’s capture plan.",
    type: "Drug dealer and offstage contact",
    setting: "An alley near Istanbul’s Spice Bazaar",
    chapterContext: "Part Two, Chapter 7",
    connections: "Peter Riviera, Molly, Terzibashjian, Case",
    definition: "Ali is the dealer from whom Peter Riviera obtains drugs in Istanbul. He is a functional minor character: the novel gives him a name, a shop, and a place in the capture sequence, but no independent biography.",
    scene: "Terzibashjian’s surveillance identifies Riviera’s routine around Ali’s shop. Molly waits outside the old alley and takes Riviera as he emerges; afterward she returns to obtain the supplies needed to keep the captive addict manageable during the team’s departure.",
    details: "The approach is built from dark stone blocks, uneven cobbles, fuel-stained limestone, and wood scraping against masonry. Ali’s business is not presented as a futuristic boutique. Its worn setting contrasts with Riviera’s implanted projection technology and shows advanced bodies moving through an old informal market.",
    context: "The Spice Bazaar and surrounding commercial streets are real Istanbul geography, while Ali and the exact drug trade are fictional. The name alone does not establish nationality, religion, age, or a larger organization; it should not be treated as shorthand for the city’s population.",
    significance: "Ali makes a bodily dependency operational. Riviera’s implants make him dangerous, but his need for a reliable supply produces a repeatable route that surveillance can exploit. The successful capture depends less on overpowering his projection system than on understanding his ordinary procurement habits.",
    caution: "The novel does not describe Ali’s appearance, identify the drugs by a complete formula, or state that he helps the crew voluntarily. It also does not place him inside the later orbital mission. His role ends with the Istanbul acquisition and resupply.",
    related: ["peter-riviera", "terzibashjian", "spice-bazaar", "istanbul"],
    tags: ["Ali", "Istanbul", "drug dealer", "Riviera", "Spice Bazaar"],
  },
  {
    slug: "angelo",
    title: "Angelo",
    fandomTitle: "Angelo",
    category: "Characters",
    spoiler: "Low",
    description: "A soft-spoken Panther Modern whose conspicuous grafts make subcultural body design visible before the Sense/Net raid.",
    type: "Panther Modern messenger",
    setting: "The crew’s Sprawl loft",
    chapterContext: "Part Two, before the Sense/Net operation",
    connections: "Panther Moderns, the Finn, Case, Molly",
    definition: "Angelo is a member of the Panther Moderns who delivers a box of software from the Finn to Case and Molly. He is distinct from Lupus Yonderboy and from the unnamed Moderns who execute the diversion calls.",
    scene: "He arrives at the loft as a courier rather than a combatant. Case registers the newcomer’s altered face and teeth more strongly than the package, reading the style as evidence that the Moderns belong to a younger culture whose modifications exceed even familiar tooth-bud work.",
    details: "The face is described as a smooth graft built on collagen and shark-cartilage polysaccharides, accompanied by sharp transplanted canines and a quiet voice. The biological materials matter: the modification is grown and engineered, not a removable mask, and its deliberate ugliness operates as group style.",
    context: "Collagen scaffolds, cartilage research, and dental implants existed well before the novel, but the complete cosmetic graft belongs to Gibson’s projection. The page therefore uses biomedical history to explain the vocabulary without claiming a real 1984 procedure could produce Angelo’s appearance.",
    significance: "Angelo turns the Moderns’ media theory into a body-level practice. Their raid will manipulate institutions through signals and rumor; his face performs a related disruption in person, making Case confront a generation that treats identity and shock as editable surfaces.",
    caution: "The book supplies no surname, age, rank, later fate, or proof that Angelo enters the Sense/Net building. Graphic-novel art is one adaptation’s design and is not used here as a canonical portrait.",
    related: ["panther-moderns", "the-finn", "body-modification-razorgirl", "chapter-04"],
    tags: ["Angelo", "Panther Moderns", "body modification", "graft", "messenger"],
  },
  {
    slug: "brood",
    title: "Brood",
    fandomTitle: "Brood",
    category: "Characters",
    spoiler: "Moderate",
    description: "The Panther Modern link operator who synchronizes Molly’s physical entry with Case’s matrix run during the Sense/Net theft.",
    type: "Codename for a communications link operator",
    setting: "New Jersey, connected to the Sense/Net operation",
    chapterContext: "Part Two, Chapter 4",
    connections: "Molly, Case, Panther Moderns, Sons of Christ the King",
    definition: "Brood is the operational name attached to the Panther Modern serving as link man during the Sense/Net raid. The name identifies a role in the communications chain, not a separately developed gang leader.",
    scene: "From New Jersey, Brood relays scrambled traffic through a crude dish and a hijacked religious satellite. His timing is coordinated with the chip behind Molly’s eye; at the agreed moment the link gives the mainline cue and the Moderns’ distributed hoax begins converging police and security forces on the pyramid.",
    details: "The link combines inexpensive-looking hardware, satellite access, codenames, and strict synchronization. Molly is Cat Mother and Case is Cutter. Those labels divide knowledge and make the operation sound military even though its communications path has been improvised from consumer, pirate, and religious infrastructure.",
    context: "Satellite piracy and phone phreaking were recognizable concerns when the novel appeared. Gibson extends that culture into a network where a subculture can borrow orbital communications without owning the satellite, anticipating the tactical value of routing and attribution rather than predicting a precise protocol.",
    significance: "Case’s code cannot steal the construct alone. Brood’s link keeps the physical infiltrator, remote cowboy, and diversion team on one clock. The minor name therefore exposes the heist’s dependence on coordination work that is easy to overlook beside Molly’s movement and Case’s matrix imagery.",
    caution: "Brood is not named in the novel as the caller in every diversion message, and the graphic adaptation’s expanded characterization should not be back-projected into the prose. His legal name, appearance, and later career are unknown.",
    related: ["panther-moderns", "sense-net-pyramid", "sons-of-christ-the-king", "chapter-04"],
    tags: ["Brood", "Panther Moderns", "link man", "Sense/Net", "New Jersey"],
    quote: {
      text: "Mainline.",
      citation: "Neuromancer, Part Two, Chapter 4",
      note: "The single-word cue turns a dispersed prank network into a synchronized operation.",
    },
  },
  {
    slug: "congressional-aide",
    title: "The Congressional Aide",
    fandomTitle: "Congressional aide",
    category: "Characters",
    spoiler: "Full",
    description: "The unnamed political operative who repairs Corto for televised testimony, then becomes the first recorded victim of Corto’s postwar collapse.",
    type: "Unnamed congressional operative",
    setting: "A military hospital, Washington hearings, and an M Street restaurant",
    chapterContext: "Corto dossier recounted in Part Two, Chapter 6",
    connections: "Willis Corto, Screaming Fist investigators, Pentagon factions",
    definition: "The Congressional aide is an unnamed member of the cabal that locates the badly injured Willis Corto after Operation Screaming Fist. He offers reconstruction and prepares Corto as a useful witness for a managed public inquiry.",
    scene: "Eleven months after the war, the aide finds Corto blind, mutilated, and hospitalized. Five months of surgery and rehearsal produce a camera-ready survivor whose supplied testimony protects selected officials. After the hearings, the aide warns Corto about speaking to the wrong people; Corto strangles him in a restaurant.",
    details: "The transaction links prosthetic repair, cosmetic presentation, scripted testimony, and television politics. Corto’s new body is not offered as disinterested care. It is part of a media package designed to preserve institutional interests while displaying an apparently restored hero to voters.",
    context: "The dossier borrows the language of post-Vietnam scandal, congressional investigation, covert operations, and Watergate-era media politics. It does not correspond to one historical aide or hearing. The institutions are real names inside a fictional future conflict.",
    significance: "This figure shows that Corto was reconstructed and programmed before Wintermute created Armitage. Human institutions first turn trauma into a controlled performance; the AI later applies a more durable version of the same logic. The murder marks the failure of the political script and the beginning of Corto’s fugitive record.",
    caution: "No personal name, party, district, or formal job title is supplied. It is unclear how much the aide personally designed the conspiracy rather than carrying orders. Calling him a senator, CIA officer, or sole architect would exceed the dossier.",
    related: ["armitage-willis-corto", "screaming-fist-task-force", "the-war", "chapter-06"],
    tags: ["Congressional aide", "Willis Corto", "hearings", "political manipulation", "Screaming Fist"],
  },
  {
    slug: "elroy",
    title: "Elroy",
    fandomTitle: "Elroy",
    category: "Characters",
    spoiler: "Moderate",
    description: "Dixie Flatline’s fellow prisoner whose missing-thumb itch becomes the novel’s clearest analogy for memory without an original body.",
    type: "Wartime prisoner recalled by McCoy Pauley",
    setting: "A Siberian prisoner-of-war camp",
    chapterContext: "Dixie’s conversation with Case in Part Three",
    connections: "McCoy Pauley, Case, the War, ROM constructs",
    definition: "Elroy is a man McCoy Pauley knew while both were prisoners in Siberia. He appears only inside Dixie Flatline’s remembered anecdote about a frostbitten thumb that continued to itch after amputation.",
    scene: "Medics remove Elroy’s damaged thumb, yet he tosses at night because the absent digit still troubles him. Pauley tells him to scratch what is bothering him. The remembered exchange becomes the construct’s way of explaining his own condition to Case: the stored personality can feel the outline of a life it no longer possesses.",
    details: "Nothing technological surrounds Elroy’s original injury beyond wartime medicine. The important detail is bodily absence accompanied by persistent sensation. Gibson then transfers that pattern to ROM: Pauley’s biological brain is gone, but a fixed recording still registers lack, desire, humor, and confinement.",
    context: "Phantom-limb sensation is a documented neurological phenomenon, not an invention of the novel. The analogy does not claim that a personality construct works by the same medical mechanism. It gives Case and the reader a bodily model for a metaphysical problem.",
    significance: "A character who never reaches the main plot supplies one of its most humane explanatory images. Elroy lets Dixie speak about digital existence without a technical lecture. The anecdote also undermines Case’s easy contempt for flesh: bodily memory becomes the language through which a bodiless construct describes itself.",
    caution: "The text does not provide Elroy’s surname, nationality, military unit, survival after the camp, or independent connection to Case. The length and timing of the imprisonment are not reliable tools for dating the entire War.",
    related: ["dixie-flatline", "rom-personality-constructs", "the-war", "memory-death-digital-afterlife"],
    tags: ["Elroy", "Dixie Flatline", "phantom limb", "POW", "memory"],
  },
  {
    slug: "gerald-chin",
    title: "Dr. Gerald Chin",
    fandomTitle: "Gerald Chin",
    category: "Characters",
    spoiler: "Moderate",
    description: "The discreet Baltimore clinician whose anonymous capsule clinic repairs Molly after the Sense/Net extraction.",
    type: "Dentist and underground medical repairer",
    setting: "A modular clinic in Baltimore’s old hub",
    chapterContext: "After the Sense/Net raid in Part Two",
    connections: "Molly, Case, Panther Moderns, Baltimore",
    definition: "Gerald Chin is the doctor to whom the Panther Moderns take Molly after her leg is broken during the Sense/Net escape. Molly identifies him as discreet and experienced in repairing professional fighters or ‘samurai.’",
    scene: "Case follows the trail to Baltimore and finds Molly recovering inside a long anonymous clinic rack. The encounter occurs after the spectacular raid, shifting attention from media chaos and matrix action to the practical work of setting a damaged leg and keeping the patient out of official systems.",
    details: "Chin’s logo marks part of a modular medical installation whose capsules resemble an enlarged coffin-rack. The arrangement combines branding with anonymity: patients can recognize a trusted practitioner while the wider facility minimizes ordinary hospital visibility.",
    context: "The novel calls Chin a dentist while implying broader black-clinic practice. That mismatch fits a world where licensed specialties, illicit surgery, and street reputation overlap. Later Sprawl fiction returns to the name, but those events should be labeled as later continuity rather than inserted into this scene.",
    significance: "Molly’s skill depends on repair networks. Chin’s brief role prevents the razorgirl from becoming an invulnerable action figure and shows that professional violence has an aftermarket of discreet clinicians, recovery spaces, drugs, and trusted referrals.",
    caution: "The novel does not enumerate Chin’s credentials, describe the procedure, or say he personally performs every part of the treatment. His later appearance in Mona Lisa Overdrive expands the character but does not alter what Case knows here.",
    related: ["baltimore", "molly", "sense-net-pyramid", "chiba-medical-underground"],
    tags: ["Gerald Chin", "Baltimore", "black clinic", "Molly", "medical repair"],
  },
  {
    slug: "kurt",
    title: "Kurt",
    fandomTitle: "Kurt",
    category: "Characters",
    spoiler: "Low",
    description: "The young Chatsubo bartender whose enormous riot gun briefly checks Wage’s men without turning the bar into a shootout.",
    type: "Chatsubo employee",
    setting: "The Chatsubo, shortly before dawn",
    chapterContext: "Part One, Chapter 1",
    connections: "Ratz, Wage, Case, Wage’s joeboys",
    definition: "Kurt is the young man tending the Chatsubo while Ratz rests. His Brazilian identification comes from the narration, but the book gives no fuller history or reason for his employment in Night City.",
    scene: "When Wage and his joeboys enter the thin pre-dawn crowd, Kurt brings a Smith & Wesson riot gun to bear. The threat remains suspended rather than discharged. After the men leave, Kurt sits with the weapon across his lap until Ratz directs him to remove a vomiting sailor.",
    details: "The huge, lightweight barrel and skeletal magazine make the weapon visually disproportionate to its quiet holder. Kurt’s cigarette, the drunk on the floor, and Ratz’s routine instruction pull the scene back toward bar work. Violence is present as equipment and posture before it becomes action.",
    context: "Smith & Wesson is a real American firearms brand; the specific futuristic riot gun and its sandbag ammunition are fictional. ‘Brazilian kid’ signals the port’s international labor world but does not establish an exact age or immigration story.",
    significance: "Kurt shows that even apparently subordinate workers in Night City participate in local deterrence. The Chatsubo’s neutrality is maintained not by police but by reputation, readiness, and the possibility that a bartender can put an unusual weapon on the counter.",
    caution: "Kurt is not one of Case’s allies, does not fire the gun, and is not shown joining the later operation. His age, surname, relationship to Ratz, and fate after the opening are unreported.",
    related: ["chatsubo", "ratz", "wage", "smith-wesson-riot-gun"],
    tags: ["Kurt", "Chatsubo", "bartender", "riot gun", "Night City"],
  },
  {
    slug: "larry",
    title: "Larry",
    fandomTitle: "Larry",
    category: "Characters",
    spoiler: "Moderate",
    description: "The software clerk and Panther Modern who detects Case riding Molly’s simstim feed before agreeing to hear her proposal.",
    type: "Software clerk and Panther Modern",
    setting: "The seventh booth along Memory Lane’s south wall",
    chapterContext: "Part Two, Chapter 4",
    connections: "Molly, Case, Panther Moderns, Microsofts",
    definition: "Larry is Molly’s contact inside Memory Lane. He works behind a software counter and belongs to the Panther Moderns, making him both a retail clerk in the visible market and an access point to the covert group.",
    scene: "Molly locates Larry by booth number. He removes one colored microsoft and inserts another, then recognizes that an unseen person is sharing her sensorium. He refuses to conduct the conversation with the rider present, so Case disconnects and Molly negotiates the Sense/Net assistance privately.",
    details: "Larry’s shaved head, bright shirt, cigarette pack, carbon socket, and cluster of silicon slivers make his technology visible as fashion and work equipment. The act of swapping a module before noticing Case suggests task-specific software, but the text never names the loaded program.",
    context: "The word microsoft is Gibson’s lowercase count noun, despite the real company’s already existing name. Larry is not a Microsoft Corporation employee. His booth belongs to the novel’s imagined software bazaar, where programs are displayed under clear bubbles like small retail goods.",
    significance: "Larry is the reader’s practical demonstration that simstim sharing can be detected by the person being observed. He also keeps the Moderns from becoming an abstract gang: their network includes shifts, counters, habits, privacy demands, and face-to-face trust.",
    caution: "The book never explains exactly how Larry senses the rider, which microsoft he inserts, or whether the detection is software, experience, or another augmentation. His surname and role during the raid are not supplied.",
    related: ["memory-lane", "microsofts", "panther-moderns", "simstim-sensorium"],
    tags: ["Larry", "Panther Moderns", "Memory Lane", "microsofts", "simstim"],
  },
  {
    slug: "marlene",
    title: "Marlene",
    fandomTitle: "Marlene",
    category: "Characters",
    spoiler: "Moderate",
    description: "A woman from Case’s youth whose demand to destroy a wasp nest supplies his later model for Tessier-Ashpool’s sealed social form.",
    type: "Figure in Case’s autobiographical memory",
    setting: "A nearly abandoned weekly-rate hotel",
    chapterContext: "Remembered during the Freeside approach in Part Three",
    connections: "Case, Rollo, Tessier-Ashpool, Villa Straylight",
    definition: "Marlene is a person Case remembers from his adolescence. The novel uses one summer episode involving her, Rollo’s flamethrower, and a wasp nest; it does not develop her as a participant in the present heist.",
    scene: "After a wasp stings Marlene, she tells Case to destroy the nest. Drunk, he retrieves Rollo’s weapon but knocks the nest into the alley. The memory returns years later as Case tries to understand the intricate, enclosed, collective persistence of Tessier-Ashpool and Villa Straylight.",
    details: "The hotel has a dead elevator, roaches, a bare striped mattress, blistered wood, and wasps at the window. Those decayed textures keep the recollection far from abstract symbolism. The corporate comparison grows from an embarrassing bodily memory rather than from a formal theory.",
    context: "Wasp colonies have long served as figures for organized collective life. Gibson’s use is explicitly filtered through Case’s experience and should not be treated as a scientific description of Tessier-Ashpool genetics or consciousness.",
    significance: "Marlene anchors a major metaphor in Case’s pre-cowboy life. Her fear and his failed attempt at protection become part of how he reads an orbital dynasty. The passage shows that his analytical models come not only from code but from damaged hotels, relationships, and remembered shame.",
    caution: "The book does not give Marlene’s surname, later fate, exact relationship with Case, or definitive account of her continuing involvement with Rollo. She is not the same character as Linda Lee or any AI-generated woman on the beach.",
    related: ["henry-dorsett-case", "rollo", "tessier-ashpool-family", "villa-straylight"],
    tags: ["Marlene", "Case", "wasp nest", "memory", "Tessier-Ashpool"],
  },
  {
    slug: "matsuga",
    title: "Matsuga",
    fandomTitle: "Matsuga",
    category: "Characters",
    spoiler: "Low",
    description: "The vanished Ninsei businessman whose abandoned office gives Case a desperate escape route through the arcade building.",
    type: "Night City businessman or front operator",
    setting: "An office above the Ninsei arcade",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Wage, Molly, the Ninsei arcade",
    definition: "Matsuga is a Japanese contact with whom Case and Wage once discussed proscribed hormonal triggers. By the opening pursuit, his former office is empty, leaving only the physical memory of a business that has disappeared.",
    scene: "Believing an assassin is behind him, Case climbs above the arcade, alerts a security worker, and forces his way into Matsuga’s old cubicle. He uses the emptied room and its cheap window as an escape path, jumping into the alley before discovering the pursuer is Molly.",
    details: "The cubicle contains discarded food, a bladeless fan, and a loop of fiber optics protruding from a socket. Sooty plastic overlooks a service alley filled with junk. The residue suggests rapid abandonment without explaining whether the business failed, relocated, or was erased.",
    context: "The name and office participate in Gibson’s imagined Chiba economy of fronts, travel desks, illegal biotech, and transient tenancy. No real company or identifiable historical Matsuga is being portrayed.",
    significance: "A nearly absent person shapes the chase through remembered geography. Case survives because he knows who once rented which cubicle and where its rear window opens. Matsuga demonstrates how underworld expertise includes obsolete floor plans and the afterimages of failed deals.",
    caution: "It is not stated that Molly removed Matsuga, that Wage owned the office, or that hormonal triggers were the tenant’s only trade. His first name, appearance, present location, and fate are unknown.",
    related: ["ninsei-arcade", "ninsei", "wage", "chapter-01"],
    tags: ["Matsuga", "Ninsei", "arcade", "hormonal triggers", "Night City"],
  },
  {
    slug: "michele",
    title: "Michele",
    fandomTitle: "Michele",
    category: "Characters",
    spoiler: "Full",
    description: "The senior-looking-young Turing agent who interrogates Case and becomes the sole survivor of Wintermute’s Freeside counterattack.",
    type: "Turing Registry agent",
    setting: "Case’s Intercontinental room and a Freeside transit route",
    chapterContext: "Part Three, Chapter 13",
    connections: "Roland, Pierre, Case, Wintermute",
    definition: "Michele is one of three French-speaking Turing agents who detain Case at Freeside. Cosmetic surgery makes her appear about nineteen, while her hands and manner indicate a much older professional.",
    scene: "She waits with Roland and Pierre in Case’s room, participates in the interrogation, and travels with the arrested cowboy. Wintermute then weaponizes the resort’s ordinary systems: a gardening robot kills Roland and a microlight strike kills Pierre. Michele survives the immediate attack and attempts to keep custody of Case.",
    details: "Michele’s controlled weariness contrasts with the team’s immaculate white sportswear and patterned tans. A compact, silenced weapon and possible recording equipment make her less conspicuous than Pierre, but no explicit implant inventory is provided.",
    context: "The Registry is fictional international AI enforcement. The agents’ French language and transnational authority may recall international policing, yet the novel does not identify them as Interpol or employees of the French state.",
    significance: "Michele complicates a simple good-cop/bad-cop division. She belongs to a coercive arrest team, but her warnings about an expanding AI are supported by Wintermute’s lethal response. Her survival leaves the regulatory argument present even as the operation escapes it.",
    caution: "The text does not confirm that the three stylish tourists seen earlier are always the same agents, though the connection is strongly suggested. Michele’s surname, exact age, later report, and final fate are not given.",
    related: ["turing-registry", "freeside-turing-agents", "roland", "pierre"],
    tags: ["Michele", "Turing Registry", "Freeside", "AI law", "agent"],
  },
  {
    slug: "mona",
    title: "Mona of Night City",
    fandomTitle: "Mona",
    category: "Characters",
    spoiler: "Low",
    description: "The Night City acquaintance whose warning reaches Linda and confirms that Wage’s people are closing around Case.",
    type: "Night City resident and underworld contact",
    setting: "Chiba City’s criminal social network",
    chapterContext: "Part One, Chapter 1",
    connections: "Linda Lee, Case, Wage, Wage’s joeboys",
    definition: "Mona is a woman known to Case and Linda Lee in Chiba. Her boyfriend is connected to Wage’s crew, giving her access to the warning that Wage may intend to have Case killed.",
    scene: "Mona does not enter the narrated encounter herself. Linda relays what Mona has heard through her boyfriend. The report intensifies Case’s suspicion and helps push his exhausted movements through the arcade, the Chatsubo, and the port-side confrontation.",
    details: "The chain is entirely social: Wage’s organization, a boyfriend inside its orbit, Mona, Linda, and finally Case. No secure terminal or matrix run is required. The fragility of the information comes from the same intimacy that makes it available.",
    context: "This Mona should not be confused with the protagonist of Mona Lisa Overdrive. Shared given names are common, and the novel offers no signal that the Night City acquaintance is a younger version of that later character.",
    significance: "Mona shows how information moves beneath the novel’s spectacular networks. A rumor passed through relationships can matter as much to immediate survival as stolen access codes. It also reveals Linda acting as an information carrier before Case’s mistrust overwhelms their exchange.",
    caution: "Mona’s surname, appearance, direct words, and later life are unknown. The source of the boyfriend’s information is not independently verified, and the page does not treat the rumor as a witnessed order from Wage.",
    related: ["linda-lee", "wage", "chiba-underworld", "chapter-01"],
    tags: ["Mona", "Linda Lee", "Wage", "Night City", "rumor"],
  },
  {
    slug: "pierre",
    title: "Pierre",
    fandomTitle: "Pierre",
    category: "Characters",
    spoiler: "Full",
    description: "The confrontational Turing agent whose interrogation tactics and death expose both Registry coercion and Wintermute’s physical reach.",
    type: "Turing Registry agent",
    setting: "The Intercontinental and Freeside transit system",
    chapterContext: "Part Three, Chapter 13",
    connections: "Michele, Roland, Case, Wintermute",
    definition: "Pierre is one of the three Turing Registry officers who arrest Case. His teenage appearance is cosmetic, and his sharper, pacing manner supplies the hostile side of an intentionally staged interrogation.",
    scene: "In Case’s room Pierre presses the prisoner while Roland adopts measured reasonableness and Michele watches. During transport, Wintermute turns Freeside machinery against the team. Pierre is killed in the microlight attack that breaks the Registry’s custody.",
    details: "A white mesh shirt, cigarettes, expensive lighter, gold chain, and cosmetically young face make the agent resemble a wealthy tourist. That surface is cover and institutional style rather than proof of youth. The weapons and authority become visible only after the surveillance phase closes.",
    context: "The agent’s French name, language, and fashion do not make the Registry a French agency. Its authority derives from treaties governing AI, a fictional legal arrangement operating across borders and orbital jurisdictions.",
    significance: "Pierre helps the arrest scene avoid presenting law as neutral explanation. The Registry has a defensible concern about Wintermute, but it uses intimidation, ambiguous jurisdiction, and covert surveillance. His violent death then demonstrates why the concern is not merely bureaucratic paranoia.",
    caution: "No surname, rank, national employer, or independent biography is supplied. Calling Pierre a policeman in the ordinary municipal sense understates the Registry’s treaty-based role; calling him a villain erases the evidence behind his warning.",
    related: ["turing-registry", "freeside-turing-agents", "michele", "roland"],
    tags: ["Pierre", "Turing Registry", "Freeside", "interrogation", "AI law"],
  },
  {
    slug: "roland",
    title: "Roland",
    fandomTitle: "Roland",
    category: "Characters",
    spoiler: "Full",
    description: "The ostensibly reasonable Turing interrogator whose treaty lecture ends when Wintermute drops a gardening robot onto him.",
    type: "Turing Registry agent",
    setting: "The Intercontinental and Freeside parkland",
    chapterContext: "Part Three, Chapter 13",
    connections: "Michele, Pierre, Case, Wintermute",
    definition: "Roland is the Turing agent who takes the measured role during Case’s detention. He explains the Registry’s legal flexibility and tries to make cooperation seem safer than Pierre’s threats.",
    scene: "The trio questions Case about Armitage, Molly’s alias, Sense/Net, and the stolen Dixie construct. After removing him from the hotel, they cross Freeside’s managed landscape. A crablike gardening machine falls from above and kills Roland as Wintermute begins its rescue.",
    details: "Roland’s calm speech, offered cigarette, youthful cosmetic face, and coordinated clothing are techniques of controlled presentation. The garden robot is equally presentable infrastructure until the AI redirects it. Both human and machine surfaces conceal coercive capacity.",
    context: "His discussion of treaties and legal ambiguity belongs to the fictional Turing regime. Real international law offers analogies for jurisdiction and extradition, but there is no historical registry with the powers Roland describes.",
    significance: "Roland voices the novel’s clearest institutional case against AI self-enlargement. His death immediately validates the claim that Wintermute can manipulate people and environments, while the brutality of the arrest prevents the Registry from becoming an uncomplicated moral authority.",
    caution: "The novel does not confirm an exact age, surname, rank, or history. ‘Good cop’ describes an interrogation posture, not proof that Roland is kind or secretly sympathetic to Case.",
    related: ["turing-registry", "gardening-robots", "michele", "pierre"],
    tags: ["Roland", "Turing Registry", "Wintermute", "gardening robot", "Freeside"],
  },
  {
    slug: "rollo",
    title: "Rollo",
    fandomTitle: "Rollo",
    category: "Characters",
    spoiler: "Moderate",
    description: "The absent biker whose flamboyant flamethrower turns Case’s adolescent wasp-killing attempt into a dangerous failure.",
    type: "Biker remembered from Case’s youth",
    setting: "A decaying weekly-rate hotel",
    chapterContext: "Case’s wasp-nest memory in Part Three",
    connections: "Marlene, Case, the Tessier-Ashpool metaphor",
    definition: "Rollo is Marlene’s large biker partner or intermittent boyfriend. He never appears in the present action; Case remembers his body, haircut, and stored flamethrower while reconstructing a summer from adolescence.",
    scene: "Marlene orders Case to destroy a wasp nest outside their room. He finds Rollo’s device in a closet and tries to use it while drunk. Instead of cleanly burning the nest, he knocks it into the alley, a memory that later accompanies his wasp-colony model of Tessier-Ashpool.",
    details: "Rollo is associated with a dark crewcut carrying a bleached lightning bolt and an oversized Frisco weapon shaped like a heavy flashlight. The object’s nickname and theatrical design fit the biker even in absence, while its presence in the hotel makes Case’s jealousy materially dangerous.",
    context: "‘Frisco flamethrower’ is street naming within the novel, not a documented commercial model. The real city nickname and recognizable flashlight shape ground an otherwise fictional weapon.",
    significance: "Rollo’s offstage ownership complicates the memory’s emotional geometry. Case borrows another man’s dangerous object to answer Marlene’s demand and fails. The later corporate metaphor therefore carries jealousy, bravado, and borrowed power as well as insect architecture.",
    caution: "The exact relationship among Rollo, Marlene, and Case is not fully defined. No later fate, criminal affiliation, or proof of violence is supplied, and Rollo should not be confused with Ratz or Roland.",
    related: ["marlene", "henry-dorsett-case", "tessier-ashpool-family", "villa-straylight"],
    tags: ["Rollo", "Marlene", "Case", "flamethrower", "wasp nest"],
  },
  {
    slug: "shin",
    title: "Shin",
    fandomTitle: "Shin",
    category: "Characters",
    spoiler: "Low",
    description: "The market waiter and hourly weapons contact who rents Case an old, multiply copied Walther pistol.",
    type: "Waiter and informal gun supplier",
    setting: "Market stalls in the Shiga area of Night City",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Wage, Walther PPK, New Yen",
    definition: "Shin is a young Japanese worker whom Case approaches for a gun. He can obtain weapons through an informal local network while continuing ordinary market work, but the text does not call him a dedicated arms dealer.",
    scene: "Case meets Shin behind a food stall while fearing Wage’s retaliation. Shin first offers a concealed taser and tells him to return later. When Case insists, Shin eventually supplies an old .22 pistol with nine hollow-point rounds and charges for limited use.",
    details: "Powdered-horseradish cans hide the taser; sushi, insects, and mutant fish surround the negotiation. The pistol itself is a Vietnamese imitation of a South American copy, with red molded grips. Provenance appears as a chain of reproductions rather than a prestigious original.",
    context: "Walther is a real German firearms maker, and the PPK is a historical model. Gibson’s copied future variant, ammunition combination, and rental arrangement belong to the fiction; they should not be used as safe real-world firearms guidance.",
    significance: "Shin’s scene shows Night City commerce operating at several scales in one stall: food, novelty animals, currency, improvised concealment, and weapon access. Case’s desperation is measured by his rejection of the less lethal option.",
    caution: "The book does not give Shin a surname, exact age, gang membership, or ownership of the weapon. ‘Rent’ matters: Case has temporary access, not a permanent purchase or formal license.",
    related: ["shiga-night-city", "walther-ppk", "new-yen", "chapter-01"],
    tags: ["Shin", "Night City", "gun rental", "Walther PPK", "Shiga"],
  },
  {
    slug: "snake-man",
    title: "Snake Man",
    fandomTitle: "Snake Man",
    category: "Characters",
    spoiler: "Low",
    description: "Case’s unreliable buyer for a cooler of pituitary glands, whose cash-flow failure pushes the stolen biotech toward Wage.",
    type: "Criminal customer or broker",
    setting: "Reached by phone from Night City; associated with Shinjuku",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Wage, the Chiba underworld",
    definition: "Snake Man is the handle of a customer with whom Case has arranged a sale involving preserved pituitary glands. He is a voice at the far end of a call, not a physically described participant in the opening.",
    scene: "Needing money to answer Wage’s pressure, Case calls and says the requested material is ready. Snake Man reports a cash-flow problem and asks him to front the goods. Case refuses, ends the call, and later uses the cooler as part of his settlement with Wage.",
    details: "The commodity sits in a spun-aluminum laboratory flask inside a cooler. Case refers to it through coded language on the phone. Cold-chain biotech, debt, and street slang meet in a transaction whose commercial failure matters more than the glands’ intended medical use.",
    context: "Human pituitary tissue had a real history in hormone production before recombinant alternatives reduced reliance on cadaver-derived material. The novel does not say precisely what treatment, research, or illicit modification Snake Man intended.",
    significance: "The failed sale closes one of Case’s imagined exits. His opening crisis is not caused by one betrayal but by a market in which buyers delay, debt remains immediate, and stolen technical goods cannot reliably become cash.",
    caution: "Snake Man’s legal name, appearance, nationality, and organization are unstated. The call does not prove he set Case up, worked for Wage, or ever received the glands.",
    related: ["wage", "chiba-underworld", "shinjuku", "chapter-01"],
    tags: ["Snake Man", "Case", "pituitary glands", "black market", "Shinjuku"],
  },
  {
    slug: "tally-isham",
    title: "Tally Isham",
    fandomTitle: "Tally Isham",
    category: "Characters",
    spoiler: "Moderate",
    description: "The simstim celebrity whose packaged adventures define the mass-market sensorium industry surrounding Sense/Net.",
    type: "Simstim performer and media star",
    setting: "Sense/Net’s media network and celebrity culture",
    chapterContext: "Referenced around the Sense/Net theft and Freeside nightlife",
    connections: "Sense/Net, simstim audiences, Cath, Molly",
    definition: "Tally Isham is a famous simstim performer. Audiences consume recorded or broadcast experience through her sensorium, making her body both celebrity persona and media-production platform.",
    scene: "The novel invokes Tally through examples of spectacular experience and through fans hoping to glimpse her at Sense/Net. Cath later reports seeing the star after the raid. Tally does not join Case’s operation, but her institutional presence helps explain why the pyramid and its library matter.",
    details: "Her catalog includes high-speed travel over desert terrain, preserved island environments, and elite parties. Branded mirrored eyewear helps mark star status. The attractions package danger, access, and luxury as sensations a consumer can temporarily inhabit.",
    context: "Simstim is fictional, but its celebrity logic draws on film stars, television personalities, sports media, and the emerging home-video economy. Tally should not be equated with an actor merely wearing a camera: the product includes multisensory bodily input.",
    significance: "Tally supplies the commercial opposite of Case’s unauthorized ride in Molly. Her sensorium is contracted, edited, branded, and sold; Molly’s is patched into a heist. Comparing them reveals that the same interface can organize entertainment, intimacy, surveillance, and tactical coordination.",
    caution: "The novel gives no complete biography, contract terms, implant diagram, or proof that every listed adventure is live rather than recorded. Wider-Sprawl references may expand her cultural position, but this page keeps Neuromancer’s evidence distinct.",
    related: ["simstim-sensorium", "sense-net", "sense-net-pyramid", "cath-and-bruce"],
    tags: ["Tally Isham", "simstim", "celebrity", "Sense/Net", "sensorium"],
  },
  {
    slug: "virginia-rambaldi",
    title: "Dr. Virginia Rambaldi",
    fandomTitle: "Virginia Rambaldi",
    category: "Characters",
    spoiler: "Moderate",
    description: "The media sociologist whose dense interview dominates Case’s failed request for a useful Panther Modern précis.",
    type: "Sociologist and media commentator",
    setting: "A Hosaka-generated research briefing",
    chapterContext: "Part Two, Chapter 4",
    connections: "Panther Moderns, Case, Hosaka Computers, media institutions",
    definition: "Virginia Rambaldi is a New York University sociologist quoted in the material Case’s Hosaka assembles about the Panther Moderns. She argues that their self-conscious relation to media complicates the ordinary terrorist label.",
    scene: "Case asks for a five-minute briefing and receives Rambaldi’s interview as one of its central components. Her theoretical language does not answer his operational question—what the Moderns can do and how to work with them—so he skips ahead in frustration.",
    details: "The scene juxtaposes an expensive summarizing computer with a source poorly matched to the user’s need. The Hosaka can retrieve and compress information, but it does not automatically turn academic discourse into tactical judgment. Rambaldi’s authority and Case’s impatience are both preserved.",
    context: "The interview echoes late-twentieth-century media theory about terrorism, spectacle, and the separation of an act from its political origin. Rambaldi and the quoted institution are fictional in this role; the page does not attribute her words to a real NYU scholar.",
    significance: "Rambaldi explains something Case initially misses: the Moderns operate on the representation of violence as much as on violence itself. The Sense/Net diversion later proves the point by producing institutional panic through calls, broadcast material, and expected symptoms.",
    caution: "Case’s dismissal does not establish that Rambaldi is wrong, and her conceptual usefulness does not make the précis operationally successful. The novel gives no first-hand scene, appearance, publication list, or later fate.",
    related: ["precis", "hosaka-computers", "panther-moderns", "chapter-04"],
    tags: ["Virginia Rambaldi", "Panther Moderns", "media theory", "terrorism", "Hosaka"],
    quote: {
      text: "Terrorism as we ordinarily understand it is innately media-related.",
      citation: "Neuromancer, Part Two, Chapter 4",
      note: "Rambaldi’s claim becomes practical during the Sense/Net diversion.",
    },
  },
];

export const fandomMicroPeopleArticles = records.map(buildFandomMicroArticle);
