import { buildFandomMicroArticle, type FandomMicroRecord } from "./fandom-micro-builder";

const records: FandomMicroRecord[] = [
  {
    slug: "akai-transdermal-unit",
    title: "Akai Transdermal Inducer",
    fandomTitle: "Akai",
    category: "Technology",
    spoiler: "Moderate",
    description: "The branded medical unit connected to Molly’s transparent cast after the Sense/Net escape.",
    type: "Transdermal induction and recovery device",
    setting: "Gerald Chin’s Baltimore clinic",
    chapterContext: "After the Sense/Net raid in Part Two",
    connections: "Molly, Gerald Chin, dermatrodes, Sense/Net",
    definition: "Akai is the brand on a transdermal inducer placed beside Molly during treatment. Fine red leads run from the unit to input trodes beneath the transparent micropore cast around her damaged leg.",
    scene: "Case finds the apparatus when he reaches Molly in Baltimore. The device belongs to the aftermath of the heist rather than to the break-in itself: it supports the quiet, technical period in which her broken leg is repaired and the crew reassesses Wintermute.",
    details: "A separate box, visible leads, trodes, and a transparent cast make the recovery system legible without a medical lecture. ‘Transdermal’ here should not be confused with the drug-releasing derms used elsewhere; the connected inducer appears to deliver or monitor treatment through the skin interface.",
    context: "Akai was a real Japanese electronics manufacturer known for audio and video equipment. The novel extends the brand into medical electronics. The later history of the company does not determine whether Gibson’s imagined future trademark continues under new ownership.",
    significance: "The branded device makes advanced medicine feel purchased and assembled rather than miraculous. Molly’s body is sustained by an ecosystem of firms, clinics, consumables, and contacts, undercutting the fantasy that her modifications make repair unnecessary.",
    caution: "The text does not state voltage, waveform, exact therapeutic mechanism, or whether Akai manufactures the cast and trodes as well as the inducer. Calling it a bone regenerator or nerve-splicing machine would go beyond the scene.",
    related: ["gerald-chin", "baltimore", "dermatrodes", "derms-dermadisks"],
    tags: ["Akai", "transdermal inducer", "Molly", "medical technology", "Baltimore"],
  },
  {
    slug: "arab-horse-cloning",
    title: "Arab Horse Reconstruction",
    fandomTitle: "Arabs",
    category: "Technology",
    spoiler: "Low",
    description: "The Finn’s joke about scientists rebuilding extinct horses with contaminated DNA, a tiny clue to the novel’s biotechnology and prejudice.",
    type: "Reported cloning project and underworld anecdote",
    setting: "Discussed in Istanbul’s Spice Bazaar",
    chapterContext: "Part Two, Chapter 7",
    connections: "The Finn, extinct horses, the preserved bazaar specimen",
    definition: "The novel reports, through the Finn, that Arab scientists tried to reconstruct horses from DNA after extinction. His punch line claims the results croak because frog material entered the reconstruction.",
    scene: "A preserved horse displayed near the bazaar excites the Finn, who has never treated the extinct animal as ordinary. He answers the sight with a story that mixes biotechnology, rumor, and a deliberately crude joke.",
    details: "The specimen is touched by generations of passersby while the reconstructed animals remain offstage. No laboratory, scientist, genome, or living hybrid is shown. Everything about the project reaches readers through a criminal technician’s comic retelling.",
    context: "Cloning and recombinant-DNA research were major public topics by 1984, while later de-extinction proposals made the premise more familiar. Frogs became a popular shorthand for filling genomic gaps, but the novel predates many modern versions of that trope.",
    significance: "The anecdote expands ecological catastrophe in a few lines. Extinction has become market spectacle and technical repair project, yet the information comes packaged as ethnic stereotype and barroom humor. Scientific ambition and cultural bias are inseparable in the telling.",
    caution: "Fandom turns ‘the Arabs’ into a stable ethnic actor and treats the frog explanation as obvious fact. The novel supplies the Finn’s claim, not an authoritative report. The project’s country, success rate, and actual method are unknown.",
    related: ["the-finn", "spice-bazaar", "cloning-vatgrown-humans", "japan-orientalism-globalization"],
    tags: ["horse extinction", "cloning", "Finn", "Arab scientists", "biotechnology"],
    quote: {
      text: "They always croak.",
      citation: "Neuromancer, Part Two, Chapter 7",
      note: "The Finn reduces an uncertain reconstruction story to a punch line.",
    },
  },
  {
    slug: "bank-chip",
    title: "Bank Chips",
    fandomTitle: "Bank chip",
    category: "Technology",
    spoiler: "Moderate",
    description: "Portable credentials that join identity, payment, and service access in Freeside’s cashless resort economy.",
    type: "Personal banking and payment credential",
    setting: "Freeside and wider Sprawl commerce",
    chapterContext: "Part Three",
    connections: "Case, Intercontinental, Freeside nightclub, New Yen",
    definition: "A bank chip is a portable credential used to charge purchases or services to an account. On Freeside, readers encounter dark glass plates that accept the chip with minimal visible ceremony.",
    scene: "Case uses his chip for service at the Intercontinental and later encounters a reader at the underground nightclub and puppet parlor. The same form of access moves from ordinary hospitality to highly private sexual transactions.",
    details: "The chip is carried, pressed to a reader, and associated with personal funds. The novel does not clearly separate account token, identity record, and credit instrument; that ambiguity may be the point in a world where financial access functions as practical identity.",
    context: "Smart cards and bank cards existed in experimental and commercial forms before 1984. Gibson extrapolates them into compact ubiquitous credentials without specifying modern contactless protocols, cryptographic standards, or blockchain systems.",
    significance: "The bank chip makes Freeside frictionless only for those with an account. Access to food, rooms, and bodies passes through the same interface, revealing how the resort converts private desire into an auditable service category.",
    caution: "The text does not prove the chip stores money locally, continuously broadcasts identity, or works exactly like a present-day debit card. Wider-Sprawl examples involving false identities should be labeled separately.",
    related: ["intercontinental-freeside", "freeside-hospitality-nightlife", "new-yen", "corporate-sovereignty"],
    tags: ["bank chip", "payment", "Freeside", "identity", "finance"],
  },
  {
    slug: "bell-europa",
    title: "Bell Europa",
    fandomTitle: "Bell Europa",
    category: "Organizations",
    spoiler: "Moderate",
    description: "The telecommunications company whose perpetually stolen codes give Case a route from Copenhagen’s pirate board into London.",
    type: "Telecommunications provider",
    setting: "European matrix grids",
    chapterContext: "Part Two, Chapters 5–6",
    connections: "Case, Dixie Flatline, Copenhagen grid, London database",
    definition: "Bell Europa is a communications company whose access codes are repeatedly copied and posted in a low-security academic grid. Case uses one as an intermediate credential while reaching Armitage’s private archive.",
    scene: "Dixie leads Case to the Copenhagen board, Case obtains a current code, enters Bell’s system, switches to a standard phone route, and works through the digits needed for London. The path is an accumulation of ordinary weaknesses rather than one dramatic breach.",
    details: "Bell reads the board and changes compromised codes; pirates steal the replacements and post them again. The repeated cycle shows an institution capable of response but unable to repair the social process that leaks credentials.",
    context: "The name evokes the historical Bell telecommunications system and its international descendants. Bell Europa is fictional; it should not be treated as a confirmed future form of one present European carrier.",
    significance: "The company is connective tissue between public academic space and private military history. Its vulnerability makes global communications useful to hackers while its routine countermeasures turn piracy into maintenance work rather than a once-only triumph.",
    caution: "Case does not destroy Bell Europa or prove total access to its network. The code opens a route for a particular call, and the novel gives no headquarters, ownership chart, or full service territory.",
    related: ["copenhagen-grid", "london-grid", "dixie-flatline", "chapter-06"],
    tags: ["Bell Europa", "telecommunications", "access codes", "Copenhagen", "matrix"],
  },
  {
    slug: "betaphenethylamine",
    title: "Betaphenethylamine (‘Beta’)",
    fandomTitle: "Betaphenethylamine",
    category: "Technology",
    spoiler: "Moderate",
    description: "The powerful stimulant Case takes on Freeside after his modified metabolism blocks familiar drugs.",
    type: "Fictionalized or unspecified phenethylamine stimulant",
    setting: "Freeside",
    chapterContext: "Part Three, Chapters 11–12",
    connections: "Case, Cath, Riviera’s performance, biomedical controls",
    definition: "Beta is the street name used for betaphenethylamine, a stimulant that still affects Case despite the metabolic modifications installed with his new pancreas and liver tissue.",
    scene: "Case obtains the drug through Freeside’s nightlife and takes it before Riviera’s performance. Its extreme somatic rush, followed by strain and disorientation, shapes his response to The Doll and his later wandering beneath the artificial sky.",
    details: "The prose renders impact through teeth, bones, light, static, sexual energy, and altered bodily precision rather than through dosage tables. Case later conceals the cause from Armitage by calling his condition an allergic reaction.",
    context: "Phenethylamine names a real chemical family that includes many stimulants, but the novel’s compound identity and effects do not map cleanly to a safe real drug. Online attempts to identify a single modern substance remain speculative.",
    significance: "Beta shows that biomedical control produces substitution rather than abstinence. The crew has engineered Case against familiar drugs, yet a new market supplies an alternative, exposing the limits of coercion through metabolism.",
    caution: "This page is literary explanation, not dosing or chemistry guidance. The novel does not state purity, dose, route with laboratory precision, or confirm every mechanism suggested by the long subjective description.",
    related: ["case-biomedical-controls", "addiction-dependency", "chapter-11", "chapter-12"],
    tags: ["betaphenethylamine", "Beta", "Case", "stimulant", "Freeside"],
    quote: {
      text: "It hit him like an express train.",
      citation: "Neuromancer, Part Three, Chapter 11",
      note: "The simile begins an intensely bodily account of the stimulant’s onset.",
    },
  },
  {
    slug: "bockris-systems",
    title: "Bockris Systems GmbH",
    fandomTitle: "Bockris Systems",
    category: "Organizations",
    spoiler: "Full",
    description: "The Frankfurt subsidiary named in the coded transfer accompanying Kuang Grade Mark Eleven.",
    type: "Tessier-Ashpool-linked systems company",
    setting: "Frankfurt; represented through a transmission to orbit",
    chapterContext: "Part Three, before the Straylight run",
    connections: "Reinhold Scientific, Tessier-Ashpool, Kuang Eleven, Case",
    definition: "Bockris Systems GmbH is the corporate name attached to the data transfer that identifies the delivered Kuang program and confirms compatibility with Case’s Ono-Sendai deck.",
    scene: "A cassette reaches Case through an indirect orbital delivery. His Hosaka receives coded information from Bockris describing the shipment. The corporate paperwork sits between a Chinese penetration program, a Japanese deck, and Tessier-Ashpool’s own family network.",
    details: "The German legal suffix, Frankfurt location, coded transmission, compatibility statement, and parent-subsidiary trail give the tool bureaucratic provenance. Kuang may be contraband or secret, but it still arrives with something resembling technical documentation.",
    context: "GmbH is a real German limited-liability form. Bockris Systems is fictional, though the name may evoke twentieth-century scientists or technical firms. No authorial explanation proves a particular namesake.",
    significance: "Bockris reveals how Wintermute can route action through companies nominally connected to its owners. Corporate complexity becomes both prison and resource: the AI exploits the dynasty’s own distributed structure to deliver the program that will break its lock.",
    caution: "The novel does not say Bockris designed Kuang, understood the merger plan, or knowingly betrayed Tessier-Ashpool. It is safest to say the transmission came from the company, not that every employee participated.",
    related: ["reinhold-scientific", "kuang-grade-mark-eleven", "tessier-ashpool-sa", "ono-sendai-cyberspace-seven"],
    tags: ["Bockris Systems", "Frankfurt", "Kuang Eleven", "Tessier-Ashpool", "subsidiary"],
  },
  {
    slug: "braun-in-neuromancer",
    title: "Braun in Neuromancer",
    fandomTitle: "Braun",
    category: "Technology",
    spoiler: "Full",
    description: "A familiar consumer brand spanning coffee makers, audiovisual systems, holographic models, and Wintermute’s repurposed microdrone.",
    type: "Consumer-electronics brand",
    setting: "Chiba, the Sprawl, Zion, Freeside, and Straylight",
    chapterContext: "Recurring across the operation",
    connections: "Armitage, Case, Wintermute, Braun microdrone",
    definition: "Braun appears on several unrelated devices rather than one product: coffee makers, a compact hologram projector, an audiovisual complex, and the small robot Wintermute uses inside Straylight.",
    scene: "The brand begins as background equipment in rooms and the loft. Armitage later projects a model of Freeside with a Braun unit. Inside Straylight, a consumer microdrone becomes Wintermute’s guide and warning device for Molly, Case, and Maelcum.",
    details: "Repeated brand recognition makes the future feel continuous with twentieth-century product design. The devices share no stated network or intelligence. Their connection is consumer familiarity, which Wintermute can exploit by turning an ordinary platform into a mission instrument.",
    context: "Braun is a real German company strongly associated with restrained industrial design and domestic electronics. The novel’s future catalog is fictional, but the name would have carried a precise design reputation for 1984 readers.",
    significance: "The brand’s progression from coffee to lethal stakes captures Gibson’s method. AIs do not need custom science-fiction props at every turn; they can inhabit or redirect the quiet products already distributed through human environments.",
    caution: "The Braun microdrone page covers the robot in depth, while this entry covers the wider brand. The novel does not say one product controls another or that Braun knows Wintermute uses its hardware.",
    related: ["braun-microdrone", "holography-synthetic-environments", "wintermute", "chapter-20"],
    tags: ["Braun", "consumer electronics", "microdrone", "hologram projector", "industrial design"],
  },
  {
    slug: "christian-scientists",
    title: "Christian Scientists in the Sprawl",
    fandomTitle: "Christian Scientists",
    category: "Organizations",
    spoiler: "Low",
    description: "A briefly glimpsed proselytizing pair whose approach makes three cosmetically altered office workers visibly uneasy.",
    type: "Religious group reference",
    setting: "A trans-BAMA platform or train",
    chapterContext: "Part Two, Chapter 3",
    connections: "Case, Sprawl office workers, trans-BAMA transit",
    definition: "Christian Scientists appear in a single transit observation. Case sees two adherents approaching three young office technicians, and the narration characterizes the approach as predatory.",
    scene: "The office workers display fashionable cosmetic details while moving through the Sprawl commute. Their discomfort as the religious pair closes in gives the passing tableau a tiny social conflict before the narrative continues.",
    details: "No preaching is quoted and no doctrine is explained. Clothing, body display, nervousness, and movement across public space do all the work. ‘Predatory’ belongs to the narration’s compressed viewpoint, not to a demonstrated act of violence.",
    context: "Christian Science is a real religious movement founded in the nineteenth century. The novel’s future street encounter should not be treated as a reliable account of present beliefs or ordinary members.",
    significance: "The glimpse gives BAMA social groups outside corporations and gangs. It also places religious recruitment beside engineered bodies, suggesting that old and new ways of defining the person compete on the same platform.",
    caution: "The text does not say the pair belongs to the Sons of Christ the King, practices militancy, or attacks anyone. Fandom’s generalization about targeting people goes beyond what one observed approach establishes.",
    related: ["sprawl-bama", "sons-of-christ-the-king", "body-modification-razorgirl", "chapter-03"],
    tags: ["Christian Scientists", "religion", "Sprawl", "trans-BAMA", "proselytizing"],
  },
  {
    slug: "citroen-in-istanbul",
    title: "Citroën in Istanbul",
    fandomTitle: "Citroen",
    category: "Technology",
    spoiler: "Moderate",
    description: "A real automobile marque attached to dull converted sedans used by Turkish officers during the Riviera operation.",
    type: "Hydrogen-converted sedan",
    setting: "Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Terzibashjian, Turkish police, Cumhuriyet Caddesi",
    definition: "Citroën is the brand of the subdued sedans associated with Turkish officials in the Istanbul chapter. At least one has undergone what Case regards as a primitive hydrogen-cell conversion.",
    scene: "Case notices officers arriving near the hotels in a dull car, and another Citroën later collects Terzibashjian after Riviera’s capture. The vehicles move local authority through the same streets as the crew’s more automated Mercedes.",
    details: "Muted paint, dust, rumpled uniforms, and retrofit propulsion contrast with the polished international hotel and autonomous rental. The difference signals procurement and maintenance, not simple inability: the cars still perform their institutional job.",
    context: "Citroën is a historic French automaker known for technically distinctive cars. Hydrogen fuel cells were an established research concept by 1984; the novel’s conversion quality and future fleet are fictional.",
    significance: "The brand comparison makes technological unevenness visible without a lecture. Global products persist through local modification, and state power does not require the newest surface to remain effective.",
    caution: "A character’s judgment that the conversion is primitive should not become a judgment about Turkey as a whole. Model, year, autonomy level, and conversion workshop are unstated.",
    related: ["cumhuriyet-caddesi", "terzibashjian", "mercedes-automatic-car", "turkey-in-neuromancer"],
    tags: ["Citroën", "hydrogen cell", "Istanbul", "car", "Turkish police"],
  },
  {
    slug: "cray-computers",
    title: "Cray Computers",
    fandomTitle: "Cray",
    category: "Technology",
    spoiler: "Moderate",
    description: "A supercomputer brand used as casual performance shorthand in a world where corporate computing has become environmental scale.",
    type: "High-performance computer brand",
    setting: "The crew’s equipment comparisons",
    chapterContext: "Part Two and wider Sprawl context",
    connections: "Case, Armitage, Braun holography, Hosaka Computers",
    definition: "Cray names high-performance computing in Gibson’s future. In Neuromancer, the reference helps readers calibrate resolution or processing capacity without introducing a detailed fictional Cray model.",
    scene: "The brand appears during descriptions of expensive systems and visual equipment assembled for the operation. Case understands the comparison immediately, treating supercomputer capability as familiar commercial hierarchy rather than wondrous invention.",
    details: "No keyboard, chassis, operating system, or benchmark is provided. ‘Cray’ works much like a unit of prestige and scale, while the machines Case directly uses are branded Hosaka, Hitachi, and Ono-Sendai.",
    context: "Cray Research built some of the world’s best-known supercomputers in the 1970s and 1980s. The name carried extraordinary computational prestige when Neuromancer was written, even if later personal devices changed everyday comparisons.",
    significance: "The reference anchors Gibson’s invented computers in a real 1984 hierarchy. Familiar brands lower the explanatory burden: readers can feel that a system is exceptional before they understand what the future workload requires.",
    caution: "Fandom combines a detailed Cray microcomputer from New Rose Hotel with Neuromancer. That later device should not be imported into Case’s equipment or treated as the same model.",
    related: ["hosaka-computers", "cyberspace-decks", "holography-synthetic-environments", "japan-orientalism-globalization"],
    tags: ["Cray", "supercomputer", "computing", "brand", "Sprawl"],
  },
  {
    slug: "dreaming-real",
    title: "Dreaming Real",
    fandomTitle: "Dreaming real",
    category: "Technology",
    spoiler: "Moderate",
    description: "The projection art form that moves from truckloads of gear to Riviera’s implanted, intimate, and weaponized performance.",
    type: "Holographic or perceptual performance practice",
    setting: "The Sprawl and Freeside",
    chapterContext: "Most prominently The Doll in Part Three, Chapter 11",
    connections: "Peter Riviera, Molly, 3Jane, Vingtième Siècle",
    definition: "Dreaming real is an artistic practice that produces convincing projected scenes. Earlier versions require bulky equipment and a trode helmet; Riviera performs a highly developed form through implants.",
    scene: "Case remembers earlier street or club performances before seeing Riviera build The Doll around his own body at Vingtième Siècle. The projection attracts 3Jane and assaults Molly symbolically by using a body modeled on hers.",
    details: "The art can create light, rooms, limbs, movement, and apparently embodied narrative while leaving physical matter absent. Riviera’s audience knows it is performance, yet Case’s body still reacts with nausea and Molly experiences deliberate violation.",
    context: "Laser shows, performance art, holography, video installation, and virtual-reality research all inform the phrase’s 1984 horizon. There is no single historical art form called dreaming real whose technical lineage maps exactly to Gibson’s usage.",
    significance: "Dreaming real links entertainment to coercion. The same capacity that can produce public wonder becomes social engineering and intimate attack. Riviera gains access to 3Jane because he can turn pathology into a desirable elite spectacle.",
    caution: "Dreaming real is broader than Riviera’s projection implants, and The Doll is one named performance within it. The novel does not give a universal standard, licensing system, or guarantee that all examples operate by the same hardware.",
    related: ["riviera-projection-implants", "chapter-11", "vingtieme-siecle", "holography-synthetic-environments"],
    tags: ["dreaming real", "holography", "Riviera", "performance art", "The Doll"],
  },
  {
    slug: "eastern-seaboard-fission-authority",
    title: "Eastern Seaboard Fission Authority",
    fandomTitle: "Eastern Seaboard Fission Authority",
    category: "Organizations",
    spoiler: "Moderate",
    description: "A power authority whose privileged inspection probes and scarlet matrix pyramid make public infrastructure useful camouflage.",
    type: "Electricity-generation or nuclear-power authority",
    setting: "Eastern North America / the matrix",
    chapterContext: "Matrix descriptions and wider Sprawl intrusion practice",
    connections: "Case, ICE, inspection probes, Sprawl utilities",
    definition: "The Eastern Seaboard Fission Authority is an electricity institution represented in cyberspace by a stepped scarlet pyramid. Its inspection traffic receives a level of trust or priority within the matrix.",
    scene: "The authority is not the central target of Case’s heist. Its probes provide a recognizable category of legitimate machine movement, the sort of traffic an intrusion program can imitate when approaching protected systems.",
    details: "An Aztec-like burning pyramid gives a public utility a memorable corporate-scale icon. Inspection privileges reveal that security systems must allow maintenance through, creating openings that derive from institutional necessity.",
    context: "The name echoes American public authorities such as the Tennessee Valley Authority and the energy politics of the nuclear era. Gibson later associated the invented body with such childhood institutional imagery, but it remains fictional.",
    significance: "The authority shows why absolute security is impossible. Networks need trusted inspectors, updates, and service traffic. An attacker succeeds not only by breaking a wall but by resembling the category the wall must admit.",
    caution: "Fandom merges details from Burning Chrome with Neuromancer’s category. This page treats wider-Sprawl examples as context and does not claim Case attacks the authority or that its physical headquarters is shown.",
    related: ["ice", "icebreakers", "cyberspace-matrix", "corporate-sovereignty"],
    tags: ["Eastern Seaboard Fission Authority", "nuclear power", "matrix", "inspection probe", "infrastructure"],
  },
  {
    slug: "fuji-electric-company",
    title: "Fuji Electric Company",
    fandomTitle: "Fuji Electric Company",
    category: "Organizations",
    spoiler: "Low",
    description: "A real Japanese industrial name glimpsed as an enormous holographic logo in Chiba’s obstructed commercial skyline.",
    type: "Industrial electronics company and skyline brand",
    setting: "Chiba/Tokyo commercial horizon",
    chapterContext: "Part One atmosphere",
    connections: "Case, Chiba City, corporate holography",
    definition: "Fuji Electric appears through a towering commercial hologram whose visibility is limited by harbor glare. The company does not directly hire Case or supply a named heist device.",
    scene: "The logo belongs to the layered visual environment around Night City. Case navigates beneath corporate signs that are physically huge but sometimes hidden by weather, light, distance, and other infrastructure.",
    details: "Scale and partial visibility matter more than a product catalog. The brand can dominate a sector of skyline without becoming a transparent institution to people living below it.",
    context: "Fuji Electric is a real Japanese electrical-equipment manufacturer founded in the twentieth century. The holographic sign and its future corporate reach are fictional extensions of an existing industrial name.",
    significance: "The reference illustrates Gibson’s brand collage at its most economical. One known company, enlarged into unstable light, can imply a whole corporate city without requiring exposition about ownership or technology.",
    caution: "The novel does not identify the exact location, product being advertised, corporate relationship to Night City, or continued legal history of the real firm. Fandom’s ‘Tokyo or Chiba’ uncertainty should remain explicit.",
    related: ["chiba-city", "night-city", "holography-synthetic-environments", "zaibatsus-corporate-order"],
    tags: ["Fuji Electric", "Chiba", "hologram", "corporate logo", "Japan"],
  },
  {
    slug: "gardening-robots",
    title: "Gardening Robots",
    fandomTitle: "Gardening robot",
    category: "Technology",
    spoiler: "Full",
    description: "Crablike maintenance machines that shift from background landscaping to one of Wintermute’s improvised weapons.",
    type: "Autonomous grounds-maintenance robot",
    setting: "Chiba clinic roof and Freeside gardens",
    chapterContext: "Parts One and Three",
    connections: "Case, Wintermute, Roland, Freeside",
    definition: "Gardening robots are small autonomous machines used to tend planted areas. Case first treats one as annoying clinic infrastructure; on Freeside, Wintermute redirects a similar machine to kill a Turing agent.",
    scene: "During recovery in Chiba, Case kicks at a robot that approaches his feet. Much later, as the Registry moves him through Freeside, a machine drops from the managed foliage onto Roland, beginning the AI’s violent rescue.",
    details: "Crablike movement and warning coloration make the robots visible but unthreatening in normal service. Their ability to navigate branches and grounds supplies enough physical force for weaponization without a purpose-built combat chassis.",
    context: "Robotic lawn mowers and agricultural automation were experimental topics before the novel and later became consumer products. Gibson’s machines remain fictional in capability and network access.",
    significance: "The repeated device measures Wintermute’s reach. What Case once dismisses with a kick can be given timing, target information, and lethal purpose. Intelligence resides in coordination as much as in the machine’s original design.",
    caution: "The text does not prove the Chiba and Freeside units share a manufacturer or model. It also does not explain whether Wintermute hacks the robot directly, controls a resort system, or works through another intermediary.",
    related: ["wintermute", "roland", "freeside-turing-agents", "braun-microdrone"],
    tags: ["gardening robot", "Wintermute", "Freeside", "Roland", "automation"],
  },
  {
    slug: "honda-trike",
    title: "Bruce’s Honda Trike",
    fandomTitle: "Honda",
    category: "Technology",
    spoiler: "Moderate",
    description: "The three-wheeled hydrogen vehicle that carries Case through Freeside’s curved resort streets and nightlife circuit.",
    type: "Hydrogen-cell three-wheeled vehicle",
    setting: "Freeside",
    chapterContext: "Part Three, Chapters 10–12",
    connections: "Bruce, Cath, Case, Emergency",
    definition: "Honda is the brand of Bruce’s trike, a small personal vehicle used inside Freeside. Its form and exhaust behavior adapt familiar road transport to an orbital resort’s engineered streets.",
    scene: "Bruce drives Case from the Intercontinental toward the underground club and later moves Cath through their nightlife route. The trike helps a resident couple serve as informal guides through a place Case does not yet understand.",
    details: "A red fiberglass shell, chrome suspension, three-wheel stance, and water condensation from the hydrogen system make the vehicle tactile and slightly showy. It sways and rides rather than gliding as frictionless future transport.",
    context: "Honda is a real Japanese maker of motorcycles and cars, including many three-wheeled designs in popular memory. Hydrogen fuel-cell research predates the novel; the exact Freeside model is invented.",
    significance: "The trike makes orbital life local. Freeside may rotate in space, but residents still borrow, own, customize, and ride branded vehicles between hotels and clubs. Space settlement acquires ordinary street culture.",
    caution: "The novel does not name the model, top speed, ownership paperwork, or whether it was designed specifically for Freeside gravity. Honda’s real future product line is irrelevant to the fictional machine.",
    related: ["cath-and-bruce", "freeside", "emergency-club", "freeside-hospitality-nightlife"],
    tags: ["Honda", "trike", "Bruce", "Freeside", "hydrogen cell"],
  },
  {
    slug: "hsg",
    title: "HsG",
    fandomTitle: "HsG",
    category: "Technology",
    spoiler: "Moderate",
    description: "A skeletal-growth substance whose alarming news report becomes raw material for the Panther Moderns’ Sense/Net panic broadcast.",
    type: "Fictional biochemical growth factor",
    setting: "Media archive and Sense/Net internal video system",
    chapterContext: "Part Two, Chapter 4",
    connections: "Panther Moderns, Sense/Net employees, Blue Nine hoax",
    definition: "HsG is presented as a human skeletal growth factor capable of extreme bone-cell acceleration in overdose. The Panther Moderns reuse a news segment about it during their Sense/Net diversion.",
    scene: "A report discusses deformity and possible military interest. The Moderns later inject that frightening material into the pyramid’s internal media environment while false Blue Nine warnings arrive from outside, encouraging employees to interpret stress as biological attack.",
    details: "The abbreviation sounds clinical, the percentage increase sounds quantitative, and the military angle supplies institutional fear. The raid does not need actual HsG in the building; it needs a credible visual memory of bodily transformation.",
    context: "Real growth factors regulate bone development, but ‘HsG’ as described is fictional and medically imprecise. It should not be equated with human growth hormone or one named contemporary treatment.",
    significance: "HsG demonstrates the Moderns’ montage technique. Archived science news becomes a weapon when placed in a new setting. The body supplies symptoms and anxieties that a media operation can trigger without releasing the chemical itself.",
    caution: "Fandom states biochemical properties more confidently than the novel’s brief mediated report warrants. No compound structure, manufacturer, tested military system, or actual Sense/Net exposure is established.",
    related: ["panther-moderns", "blue-nine-grievous-angel", "sense-net-pyramid", "virginia-rambaldi"],
    tags: ["HsG", "skeletal growth factor", "Panther Moderns", "media hoax", "Sense/Net"],
    quote: {
      text: "human skeletal growth factor",
      citation: "Neuromancer, Part Two, Chapter 4",
      note: "The clinical phrase helps the pirated segment sound institutionally credible.",
    },
  },
  {
    slug: "jal-orbital-shuttle",
    title: "The JAL Orbital Shuttle",
    fandomTitle: "JAL",
    category: "Organizations",
    spoiler: "Moderate",
    description: "The commercial carrier whose Orly-to-L5 service turns Case’s first trip to orbit into regulated mass transport and bodily distress.",
    type: "Airline and orbital shuttle service",
    setting: "Orly to the L-5 archipelago",
    chapterContext: "Part Three, Chapter 8",
    connections: "Case, Molly, Armitage, Riviera",
    definition: "JAL operates the shuttle that carries the crew from the Paris airport complex toward the orbital terminal. The acronym points to Japan Airlines, extended into scheduled space service.",
    scene: "Passengers are secured in deep foam, fitted with monitoring trodes, attended by uniformed staff, and subjected to acceleration and space-adaptation syndrome. Case’s first ascent is bodily humiliation rather than clean transcendence.",
    details: "Koto music, chewing gum, new-clothes smell, sweat, red aprons, harness releases, and medical readouts make the cabin recognizably commercial. Smoking restrictions survive alongside orbital launch.",
    context: "Japan Airlines is a real international carrier. Commercial orbital service was a recurring postwar futurist idea, and the novel places it inside an existing airline brand instead of inventing a military spacecraft operator.",
    significance: "JAL makes space accessible without making it easy. The trip is standardized enough for stewards and schedules, yet human balance and nausea remain limiting. Case must enter high orbit as a passenger before he can act there as a specialist.",
    caution: "The exact vehicle, launch system, flight duration, and corporate continuity from real JAL are not explained. The airline is not said to own Freeside, Zion, or the entire terminal cluster.",
    related: ["orly", "l5-archipelago", "chapter-08", "freeside"],
    tags: ["JAL", "orbital shuttle", "Orly", "L-5", "space travel"],
  },
  {
    slug: "julius-deane-import-export",
    title: "Julius Deane Import Export",
    fandomTitle: "Julius Deane Import Export",
    category: "Organizations",
    spoiler: "Low",
    description: "Deane’s warehouse-front business, where preserved goods, antique furniture, and global contraband meet behind Ninsei.",
    type: "Import-export and smuggling office",
    setting: "Warehouse space behind Ninsei, Chiba City",
    chapterContext: "Part One, Chapter 1",
    connections: "Julius Deane, Case, Linda Lee, Chiba underworld",
    definition: "Julius Deane Import Export is the business name attached to Deane’s warehouse office. It provides a respectable commercial surface for a broker whose knowledge and goods cross legal boundaries.",
    scene: "Case goes there seeking information and finds Deane within a carefully staged interior. The office later becomes part of Wintermute’s memory vocabulary because its distinctive surfaces and its owner are deeply fixed in Case’s Chiba experience.",
    details: "White shipping modules smell of preserved ginger; mismatched European furniture, stylized lamps, lacquered metal, bookcases, and a distorted clock turn the foyer into a curated historical collage. The décor performs Deane’s cultivated age and reach.",
    context: "Import-export companies have often served in crime fiction as ambiguous interfaces between legal trade and smuggling. Gibson makes the trope materially specific through logistics and design rather than naming a single real firm.",
    significance: "The business is a local version of the novel’s global network. Containers, information, contraband, and style move through one warehouse, while Deane’s apparent respectability depends on knowing how to price distance and secrecy.",
    caution: "The name does not prove a registered corporation, employee count, or legitimate catalog. The article on Julius Deane covers the person; this page covers the business environment and its narrative function.",
    related: ["julius-deane", "ninsei", "chiba-underworld", "wintermute"],
    tags: ["Julius Deane Import Export", "smuggling", "warehouse", "Chiba", "Ninsei"],
  },
  {
    slug: "melanin-boosting",
    title: "Melanin Boosting",
    fandomTitle: "Melanin boosting",
    category: "Technology",
    spoiler: "Moderate",
    description: "The cosmetic tanning process used to design fashionable skin patterns and disguise Sprawl pallor on Freeside.",
    type: "Cosmetic pigmentation treatment",
    setting: "Freeside resort culture",
    chapterContext: "Part Three",
    connections: "Cath, Case, Turing agents, Freeside hospitality",
    definition: "Melanin boosting is an artificial method for darkening skin. It can produce an even resort tan or deliberately patterned layers associated with Paris fashion.",
    scene: "Cath’s freckles and enhanced color mark her social style, while the Turing agents display carefully stenciled tans. Case lacks time for the treatment and is colored more crudely so that his Sprawl pallor will not make him conspicuous among tourists.",
    details: "Overlapping rectilinear tones can outline musculature and turn pigmentation into surface design. The process is not merely sun protection; it is class-coded preparation for a place where bodies are expected to match the resort image.",
    context: "Tanning products and medical work on melanin were familiar by 1984, but safe, precise, rapidly patterned biological enhancement remains fictional. The practice also intersects with real histories of colorism and racialized beauty standards.",
    significance: "Freeside sells environment and the body suited to it. Visitors do not just book rooms; they modify appearance to become legible as leisure consumers. The Turing agents exploit the same style as surveillance cover.",
    caution: "The novel does not specify injection, gene therapy, light exposure, permanence, or health effects. A cosmetic process changing melanin should not be confused with simply applying Case’s temporary surface color.",
    related: ["cath-and-bruce", "freeside-turing-agents", "freeside-hospitality-nightlife", "body-modification-razorgirl"],
    tags: ["melanin boosting", "cosmetic technology", "Freeside", "tan", "body modification"],
  },
  {
    slug: "mercedes-automatic-car",
    title: "The Automatic Mercedes",
    fandomTitle: "Mercedes",
    category: "Technology",
    spoiler: "Moderate",
    description: "The rented autonomous car that gives Molly and Case private, continuous mobility through Istanbul’s surveillance landscape.",
    type: "Self-driving luxury car with alternative propulsion",
    setting: "Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Case, Molly, Terzibashjian, Topkapı",
    definition: "Mercedes is the brand of the automatic car used by the crew in Istanbul. It drives their route among the Hilton, bazaars, capture area, and Topkapı without a visible human chauffeur.",
    scene: "The car carries the team through rain and mixed traffic while Terzibashjian supplies local intelligence. After Riviera is secured, Molly uses the vehicle to move with Case toward the palace gardens and discuss Armitage.",
    details: "Automatic navigation, enclosed conversation, luxury branding, and quiet propulsion contrast with the converted police Citroëns. The vehicle provides mobility and a temporary private room inside a city the crew does not control.",
    context: "Mercedes-Benz is a real German luxury automobile marque. Autonomous cars and hydrogen propulsion were longstanding research and futurist ideas before 1984; the novel does not describe a modern sensor stack.",
    significance: "The car allows global capital to bypass some local knowledge but not all of it. Automation can move the crew, while Terzibashjian must still interpret streets, police interest, and Riviera’s habits.",
    caution: "The model, owner, rental firm, energy system, and degree of autonomy are not fully specified. Fandom combines Mercedes references from several Sprawl works; this page focuses on the Istanbul vehicle.",
    related: ["istanbul", "topkapi", "citroen-in-istanbul", "terzibashjian"],
    tags: ["Mercedes", "autonomous car", "Istanbul", "Molly", "transport"],
  },
  {
    slug: "mitsubishi-genentech",
    title: "Mitsubishi-Genentech",
    fandomTitle: "Mitsubishi-Genentech",
    category: "Organizations",
    spoiler: "Low",
    description: "The biotechnology megacorporation whose executive implant turns a salaryman’s body into monitored corporate property.",
    type: "Fictional Japanese-American biotechnology combine",
    setting: "Referenced in Night City",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, sarariman, Chiba clinics, zaibatsus",
    definition: "Mitsubishi-Genentech is a fictional corporate combination built from two real company names. Senior employees may carry implanted processors that monitor mutagen levels in their blood.",
    scene: "Case notices a dark-suited salaryman on Ninsei with the company mark on his hand. If authentic, the tattoo implies an expensive monitored body and makes the man dangerously out of place near clinics capable of stealing valuable implants.",
    details: "Logo, rank, bloodstream monitoring, tattoo, and street risk compress employment into the body. Corporate care and corporate ownership are difficult to separate: the implant may protect the worker while also making him a target and a tracked asset.",
    context: "Mitsubishi is a major Japanese corporate group; Genentech was a pioneering American biotechnology company founded in 1976. Their merger is fictional and reflects 1980s speculation about Japanese capital and commercial genetics.",
    significance: "The invented name is a miniature theory of globalization. Corporate combination crosses nations and disciplines, while the employee carries that alliance literally under the skin.",
    caution: "The novel does not confirm the passerby’s tattoo is genuine, identify his rank, or show the implant operating. It also does not predict an actual merger between the real companies.",
    related: ["sarariman", "zaibatsus-corporate-order", "chiba-medical-underground", "corporate-sovereignty"],
    tags: ["Mitsubishi-Genentech", "biotechnology", "sarariman", "implant", "megacorporation"],
  },
  {
    slug: "nightwing",
    title: "Nightwing Assault Parafoils",
    fandomTitle: "Nightwing",
    category: "Technology",
    spoiler: "Full",
    description: "The radar-transparent microlights stripped and overloaded for Screaming Fist’s doomed cybernetic assault on Kirensk.",
    type: "Military assault parafoil or microlight",
    setting: "The War, especially Operation Screaming Fist",
    chapterContext: "Corto dossier and breakdown in Parts Two and Three",
    connections: "Willis Corto, Screaming Fist, Mole IX, Russian EMP defenses",
    definition: "Nightwings are lightweight military flight systems used during the War. Screaming Fist modifies them to carry console operators, prototype decks, and intrusion software toward the Kirensk computer nexus.",
    scene: "To compensate for cyber equipment, the task force removes conventional weapon systems. Hidden information about Russian electromagnetic defenses turns the run into a trap: systems fail, craft fall, and Corto’s surviving flight ends in catastrophic injury.",
    details: "Radar transparency and parafoil structure promise covert access, while weight tradeoffs expose fragility. The hybrid craft is both aircraft and mobile hacking station, forcing physical bodies and electronic attack into the same vulnerable platform.",
    context: "Ram-air parafoils, ultralights, radar countermeasures, and airborne electronic warfare were real technologies. Nightwing and the specific cyber-assault configuration are fictional.",
    significance: "The aircraft makes ‘cyberwar’ bodily. Programs do not cross the target by themselves; operators fly into defended airspace with too little protection. Armitage’s later command style grows from a mission where technology, secrecy, and institutional betrayal become one trauma.",
    caution: "Nightwing is not a cyberspace deck, a virus, or one unique craft. Details from Automatic Jack’s wider-Sprawl recollection can illuminate the type but should not be treated as Corto’s exact vehicle.",
    related: ["screaming-fist-task-force", "the-war", "armitage-willis-corto", "icebreakers"],
    tags: ["Nightwing", "parafoil", "Screaming Fist", "cyberwar", "Corto"],
  },
  {
    slug: "reinhold-scientific",
    title: "Reinhold Scientific A.G.",
    fandomTitle: "Reinhold Scientific",
    category: "Organizations",
    spoiler: "Full",
    description: "The Berne-based Tessier-Ashpool subsidiary above Bockris Systems in the corporate chain attached to Kuang.",
    type: "Scientific holding or operating company",
    setting: "Berne, Switzerland",
    chapterContext: "Corporate trail around the Kuang delivery",
    connections: "Bockris Systems, Tessier-Ashpool, Berne, Kuang Eleven",
    definition: "Reinhold Scientific A.G. is a Tessier-Ashpool-owned company based in Berne and identified as the parent of Bockris Systems GmbH.",
    scene: "The company appears through records and transmission provenance rather than a visited laboratory. Following the chain upward links the Frankfurt sender of Kuang information to the same orbital dynasty whose defenses the program will penetrate.",
    details: "Swiss and German corporate suffixes, layered ownership, and dispersed offices make Tessier-Ashpool legible as a network of legal persons. The individual products and employees remain hidden behind the organizational trail.",
    context: "A.G. is a real corporate form used in German-speaking jurisdictions. Reinhold Scientific is fictional, and no evidence proves a direct namesake or real company model.",
    significance: "The subsidiary chain shows how a family corporation can be attacked from within its own complexity. Wintermute’s reach does not float outside capital; it moves along channels produced by the organization that owns and confines it.",
    caution: "The text does not define Reinhold’s research specialty, workforce, board, or degree of knowledge about Kuang. Ownership does not mean the company and Wintermute share one conscious plan.",
    related: ["bockris-systems", "tessier-ashpool-sa", "berne", "kuang-grade-mark-eleven"],
    tags: ["Reinhold Scientific", "Berne", "Tessier-Ashpool", "Bockris Systems", "subsidiary"],
  },
  {
    slug: "smith-wesson-riot-gun",
    title: "Smith & Wesson Riot Gun",
    fandomTitle: "Smith & Wesson",
    category: "Technology",
    spoiler: "Low",
    description: "Kurt’s oversized lightweight bar weapon, loaded with subsonic impact cartridges rather than ordinary bullets.",
    type: "Futuristic less-lethal or crowd-control firearm",
    setting: "The Chatsubo",
    chapterContext: "Part One, Chapter 1",
    connections: "Kurt, Ratz, Wage, the Finn’s weapons trade",
    definition: "Smith & Wesson is the real brand attached to the unusual riot gun Kurt points at Wage’s men. The weapon combines an extremely broad, lightweight barrel with a small magazine of impact rounds.",
    scene: "Kurt produces the gun during the pre-dawn confrontation in the Chatsubo. Its presence helps prevent escalation; he never fires it. After Wage leaves, the weapon rests across his lap while ordinary bar cleanup resumes.",
    details: "Paper-thin alloy wrapped in glass filament creates strength without conventional mass. Five orange cartridges contain subsonic sandbag-like projectiles, suggesting force through impact rather than penetration.",
    context: "Smith & Wesson is a historic American firearms manufacturer. Less-lethal beanbag rounds and composite materials have real analogues, but this specific gun and construction are fictional.",
    significance: "The weapon expresses Night City deterrence: visually extreme, immediately available, and effective without being discharged. It also shows materials science entering street hardware rather than remaining inside elite military equipment.",
    caution: "The page does not provide instructions for use or claim the rounds are harmless. Fandom combines a different Smith & Wesson sale from Burning Chrome; that weapon is not necessarily Kurt’s model.",
    related: ["kurt", "chatsubo", "wage", "fletcher-weapons"],
    tags: ["Smith & Wesson", "riot gun", "Kurt", "Chatsubo", "less-lethal weapon"],
  },
  {
    slug: "sons-of-christ-the-king",
    title: "Sons of Christ the King",
    fandomTitle: "Sons of Christ the King",
    category: "Organizations",
    spoiler: "Moderate",
    description: "The obscure satellite-owning sect whose identity and comsat the Panther Moderns hijack for the Sense/Net hoax.",
    type: "Militant fundamentalist sect and unwitting communications cover",
    setting: "The Sprawl and geosynchronous orbit",
    chapterContext: "Part Two, Chapter 4",
    connections: "Panther Moderns, Brood, Blue Nine, Sense/Net",
    definition: "The Sons of Christ the King are a small fundamentalist group credited with a false biological attack on Sense/Net. The Panther Moderns appropriate both the sect’s satellite and its feared public identity.",
    scene: "Brood bounces scrambled traffic through the group’s comsat while Modern callers tell multiple agencies that the Sons have released Blue Nine. Police and security converge on the pyramid, acting on a story designed to sound institutionally plausible.",
    details: "A religious organization with orbital infrastructure becomes vulnerable to a crude dish and skilled routing. Reputation is another resource: the Moderns select a name whose alleged militancy will accelerate official belief.",
    context: "American media in the late twentieth century frequently linked new religious movements, televangelism, militancy, and communications technology. The Sons are fictional and should not be equated with the real Christian Scientists or a specific church.",
    significance: "The group shows that attribution can be weaponized independently of action. Sense/Net’s crisis is caused by what institutions already expect the named sect might do, making prejudice and preparedness parts of the attack surface.",
    caution: "The Sons do not actually release Blue Nine, and the novel does not show members planning violence. Fandom’s label ‘militant’ reflects the hoax’s premise and reputation, not witnessed conduct in the chapter.",
    related: ["brood", "blue-nine-grievous-angel", "panther-moderns", "sense-net-pyramid"],
    tags: ["Sons of Christ the King", "satellite", "Panther Moderns", "Blue Nine", "hoax"],
  },
  {
    slug: "tank-war-europa",
    title: "Tank War Europa",
    fandomTitle: "Tank War Europa",
    category: "Technology",
    spoiler: "Low",
    description: "The holographic arcade war game Linda plays when Case meets her, turning European nuclear destruction into casual entertainment.",
    type: "Holographic arcade game",
    setting: "The Ninsei arcade",
    chapterContext: "Remembered in Part One, Chapter 1",
    connections: "Linda Lee, Case, the War, Wizard’s Castle",
    definition: "Tank War Europa is an arcade game with holographic battle imagery. Case’s memory of Linda playing it links their first encounter to simulated cities, weapons, and spectacular scoring.",
    scene: "Linda occupies the machine while Case watches or approaches. The game can render nuclear-scale attacks as colored flashes, sound, and a mushroom cloud over the arcade crowd. Their personal history begins inside commercialized war imagery.",
    details: "European place names and megaton language turn geography into a scoreable field. Holograms spill above the cabinet, mixing the player’s private contest with the room’s shared haze.",
    context: "Cold War games and arcade combat were familiar by 1984, while holography promised displays beyond a flat screen. The title is fictional and need not depict the novel’s unnamed War accurately.",
    significance: "The game converts catastrophe into light before the novel reveals Corto’s actual military trauma. That contrast makes war simultaneously background entertainment, personal memory, and institutional crime.",
    caution: "Fandom speculates that the game is based on the War, but the novel does not confirm a licensed historical simulation. Its rules, developer, and relation to real events are unknown.",
    related: ["ninsei-arcade", "wizards-castle", "linda-lee", "the-war"],
    tags: ["Tank War Europa", "arcade game", "hologram", "Linda Lee", "war"],
  },
  {
    slug: "the-war",
    title: "The War",
    fandomTitle: "The War",
    category: "Themes",
    spoiler: "Full",
    description: "The short U.S.–Soviet conflict whose cyberwar prototypes, ruined cities, veterans, coverups, and trauma shape Neuromancer’s present.",
    type: "Background military conflict",
    setting: "Europe, Siberia, and institutional aftermath in the United States",
    chapterContext: "Reconstructed chiefly through the Corto dossier",
    connections: "Screaming Fist, Corto, Dixie Flatline, Riviera",
    definition: "The War is the novel’s name for a recent conflict involving the United States and Soviet forces. It is not explicitly called World War III, and its complete belligerents, chronology, and settlement are never supplied.",
    scene: "Corto’s archive makes Screaming Fist the central case: a cybernetic assault flies into concealed Russian defenses and collapses. Other memories mention Siberian imprisonment and nuclear ruin. Postwar hearings then redirect attention from failure toward institutional survival.",
    details: "EMP defenses, lasers, parafoils, prototype decks, intrusion programs, ruined Bonn, POW camps, prosthetics, and veterans dispersed into police or crime remain in the present. The conflict survives more through damaged bodies and repurposed tools than through memorial ceremony.",
    context: "Written during renewed Cold War tension, Neuromancer extrapolates U.S.–Soviet conflict without predicting the Soviet Union’s 1991 dissolution. Vietnam, covert-action scandal, nuclear anxiety, and emerging computer warfare all inform the fictional history.",
    significance: "The War explains why military technology and trauma circulate through the street economy. Case inherits intrusion methods, Ratz wears military prosthetics, Riviera grows from ruins, and Wintermute recruits a survivor whose institutions have already rewritten him.",
    caution: "Attempts to calculate an exact date from Deane’s age remarks, POW duration, and ‘nine days later’ produce contradictions. The text supports a short conflict with a long aftermath, not a complete timeline or certainty that it was global.",
    related: ["screaming-fist-task-force", "armitage-willis-corto", "nightwing", "trauma-war-manipulation"],
    tags: ["The War", "Cold War", "Screaming Fist", "cyberwar", "veterans"],
  },
  {
    slug: "walther-ppk",
    title: "Case’s Walther PPK Copy",
    fandomTitle: "Walther PPK",
    category: "Technology",
    spoiler: "Low",
    description: "The old copied .22 pistol Shin rents to Case, a weapon whose layered provenance matters more than prestige.",
    type: "Copied semiautomatic handgun",
    setting: "Night City",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Shin, Wage, Shiga market",
    definition: "The pistol Case obtains is not presented as an original factory Walther. It is a Vietnamese imitation of a South American copy of an old PPK design, chambered for .22 ammunition.",
    scene: "After refusing Shin’s taser, Case returns and receives the gun with nine hollow-point rounds. He carries it through his increasingly paranoid attempt to survive Wage’s pressure and Molly’s pursuit.",
    details: "A rough first double-action pull, bright red plastic grips molded with a dragon, uncertain copied manufacture, and mixed ammunition make the weapon tactile but unreliable. Its history is visible as reproduction rather than serial documentation.",
    context: "The Walther PPK is a real German pistol introduced in the early twentieth century and widely known through popular culture. Gibson’s .22 copy chain and explosive-ammunition reference are fictional details, not a standard model specification.",
    significance: "The gun reflects Night City’s economy of copies and temporary access. Case does not acquire a sleek hero weapon; he rents a degraded artifact because fear has outrun his money and judgment.",
    caution: "The novel’s ammunition descriptions should not be used as technical guidance, and online summaries disagree about which rounds are loaded at which moment. The page keeps to the narrated rental without reconstructing a forensic inventory.",
    related: ["shin", "shiga-night-city", "chapter-01", "cobra-weapon-not-drug"],
    tags: ["Walther PPK", "Case", "Shin", "pistol", "Night City"],
    quote: {
      text: "a Vietnamese imitation of a South American copy of a Walther PPK",
      citation: "Neuromancer, Part One, Chapter 1",
      note: "The chain of copies replaces the prestige of an original firearm.",
    },
  },
  {
    slug: "wizards-castle",
    title: "Wizard’s Castle",
    fandomTitle: "Wizard's Castle",
    category: "Technology",
    spoiler: "Low",
    description: "The dungeon arcade game Linda’s simulated counterpart recalls, tying Case’s memory to ordinary shared play.",
    type: "Fantasy arcade game",
    setting: "The Ninsei arcade and later AI memory space",
    chapterContext: "Opening memory with an echo in the ending",
    connections: "Linda Lee, Case, Ninsei arcade, Neuromancer AI",
    definition: "Wizard’s Castle is a dungeon game Linda plays at the Ninsei arcade. A later Linda-like figure can refer to its seventh level and vampires, using a small remembered frustration as evidence of personal continuity.",
    scene: "The game belongs first to Case’s recollection of meeting Linda amid arcade noise. When Neuromancer presents Linda within its constructed world, the reference reappears as one of the intimate details through which the simulation speaks to him.",
    details: "Levels, dungeons, vampires, and defeat imply a recognizable fantasy-game grammar without specifying controls or graphics. Unlike Tank War Europa’s public holographic spectacle, the remembered line centers the player’s irritated attachment to progress.",
    context: "Dungeon adventures and fantasy computer games were established by the early 1980s. The title is fictional or generic enough to evoke that culture rather than documenting one commercial release.",
    significance: "A trivial game memory becomes part of the novel’s personhood problem. Grand biographical facts can be copied from records; an annoyed remark about a failed dungeon feels private, yet the AI may have acquired it through Case or Linda’s modeled pattern.",
    caution: "The reference does not prove the beach Linda is the biologically continuous person. It also does not establish that Neuromancer stores a complete playable version of the arcade game.",
    related: ["ninsei-arcade", "linda-lee", "neuromancer-ai", "memory-death-digital-afterlife"],
    tags: ["Wizard’s Castle", "arcade game", "Linda Lee", "memory", "Neuromancer AI"],
    quote: {
      text: "Seventh level dungeon and the goddam vampires got me.",
      citation: "Neuromancer, Part Five, Chapter 24",
      note: "The remembered complaint makes the simulated Linda feel disarmingly specific.",
    },
  },
];

export const fandomMicroSystemArticles = records.map(buildFandomMicroArticle);
