import { buildFandomMicroArticle, type FandomMicroRecord } from "./fandom-micro-builder";

const records: FandomMicroRecord[] = [
  {
    slug: "ninsei-arcade",
    title: "The Ninsei Arcade",
    fandomTitle: "Arcade",
    category: "Places",
    spoiler: "Low",
    description: "The crowded game hall where Case remembers meeting Linda and later uses the offices above it to evade Molly.",
    type: "Arcade and mixed-use commercial building",
    setting: "Ninsei, Night City",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Linda Lee, Molly, Matsuga",
    definition: "The arcade is a noisy public game hall on Ninsei with a second floor of cheap office cubicles. It is both a place from Case’s history with Linda Lee and the physical maze through which he tries to lose an apparent pursuer.",
    scene: "Past and present overlap there. Case recalls Linda absorbed in holographic games, then climbs the unpainted stairs while Molly follows him. He alerts a rent-a-cop, kicks a misleading door, breaks into Matsuga’s abandoned office, and exits through its rear window into the alley.",
    details: "Sweat, discarded cups, cigarette ends, fluorescent corridors, blue-lacquered doors, roaring machines, and overlapping holograms crowd the building. A travel agency sits beside illicit or vanished businesses. The upstairs is not a sleek virtual palace but cheap rentable space resting above entertainment noise.",
    context: "Video arcades were prominent urban spaces in the early 1980s, and holographic display was a familiar futurist extension. Gibson combines that recognizable venue with mixed-use Japanese streetscape rather than predicting a specific game technology.",
    significance: "The arcade joins Case’s lost intimacy to his survival reflexes. A place where Linda once played becomes a route he can read under pressure. It also literalizes the novel’s movement from game imagery to lethal systems: simulated tanks glow below while real pursuit crosses the offices above.",
    caution: "The building has no stated proper name, and ‘the arcade’ should not be confused with the whole of Ninsei. The exact floor plan beyond the narrated route, the operator of the games, and Matsuga’s reason for leaving are unknown.",
    related: ["ninsei", "matsuga", "linda-lee", "tank-war-europa"],
    tags: ["Ninsei arcade", "Night City", "Linda Lee", "holographic games", "Matsuga"],
    quote: {
      text: "Holograms twisted and shuddered to the roaring of the games.",
      citation: "Neuromancer, Part One, Chapter 1",
      note: "The machines fill the room with unstable light before the chase moves upstairs.",
    },
  },
  {
    slug: "baltimore",
    title: "Baltimore in the Sprawl",
    fandomTitle: "Baltimore",
    category: "Places",
    spoiler: "Moderate",
    description: "The old Sprawl hub where Molly recovers inside Dr. Gerald Chin’s discreet modular clinic.",
    type: "City absorbed into BAMA",
    setting: "The Boston–Atlanta Metropolitan Axis",
    chapterContext: "After the Sense/Net extraction in Part Two",
    connections: "Molly, Case, Gerald Chin, New York",
    definition: "Baltimore survives as a named urban hub inside the continuous Sprawl. Neuromancer does not offer a citywide tour; it concentrates on a medical building where Molly has her broken leg treated away from ordinary authorities.",
    scene: "Case travels to the old hub and finds two floors occupied by a medical team and a rack of long capsules. Half bear Gerald Chin’s elaborate mark. He meets Molly during recovery, eats crab with her, discusses Wintermute, and continues north through BAMA.",
    details: "Modular architecture and capsule rooms turn medicine into dense, semi-anonymous infrastructure. The familiar local food keeps the city geographically specific even when boundaries between former cities have blurred beneath domes, rail, and continuous development.",
    context: "Baltimore is a real Chesapeake city with a strong association with blue crab and a distinct metropolitan history. Gibson projects it into BAMA without claiming that the named clinic or urban merger existed in 1984.",
    significance: "Baltimore interrupts the operation’s glamorous technological line with recuperation. The crew’s success depends on places where an injured infiltrator can disappear, be repaired, and reenter the network. The city is therefore a support node rather than a postcard backdrop.",
    caution: "The novel does not say all of Baltimore resembles the clinic, that Gerald Chin owns the whole building, or that the city has lost every independent civic institution. BAMA’s continuity does not erase local names or memories.",
    related: ["gerald-chin", "sprawl-bama", "molly", "sense-net-pyramid"],
    tags: ["Baltimore", "Sprawl", "Gerald Chin", "clinic", "BAMA"],
  },
  {
    slug: "berne",
    title: "Berne",
    fandomTitle: "Berne",
    category: "Places",
    spoiler: "Full",
    description: "The Swiss location of Wintermute’s physical mainframe and the banking-sector matrix cube Case probes from orbit.",
    type: "Swiss city and matrix sector",
    setting: "Earth; represented inside the matrix",
    chapterContext: "Part Three, Chapter 9",
    connections: "Wintermute, Case, Dixie Flatline, Tessier-Ashpool",
    definition: "Berne is the terrestrial home of Wintermute’s mainframe. For Case it is encountered primarily as a location in cyberspace near the geometric forms of Swiss banking rather than as a walked city.",
    scene: "Aboard Marcus Garvey, Case and Dixie approach the defended Berne construct for reconnaissance. Wintermute’s response overwhelms the run, interrupts Case’s bodily signs, and places him inside a memory-built Night City where the AI finally explains part of its design.",
    details: "The physical server’s exact building is withheld. In the matrix, banking structures create a cool, vertical, twilight geometry around the target. Geographic and corporate location collapse into one navigable visual field for the cowboy.",
    context: "Bern is Switzerland’s federal city; the English spelling ‘Berne’ was widely used. Switzerland’s banking reputation supplies an immediate cultural association, but Wintermute, its mainframe, and the surrounding data architecture are fictional.",
    significance: "Berne demonstrates that an AI experienced as voice and hallucination still has hardware somewhere. The distant city fixes Wintermute to legal jurisdiction, corporate ownership, and a targetable machine even while its influence reaches Case in orbit.",
    caution: "Berne is not Wintermute itself, and the matrix cube is a representation rather than a literal building floating over Switzerland. Reinhold Scientific’s address and the AI core should also not be assumed to occupy one facility.",
    related: ["wintermute-berne-core", "wintermute", "switzerland-in-neuromancer", "chapter-09"],
    tags: ["Berne", "Wintermute", "Swiss banking", "matrix", "mainframe"],
  },
  {
    slug: "beyoglu",
    title: "Beyoğlu",
    fandomTitle: "Beyoglu",
    category: "Places",
    spoiler: "Moderate",
    description: "The layered Istanbul district through which the crew moves between airport hotels, markets, and Riviera’s capture.",
    type: "Istanbul district",
    setting: "European side of Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Case, Molly, Armitage, Terzibashjian",
    definition: "Beyoğlu is a real Istanbul district used as part of the crew’s terrestrial route. The novel presents selected streets, housing, shops, and weather rather than a complete account of the district.",
    scene: "An automatic car carries Case and Molly through rainy streets toward Cumhuriyet Caddesi and the Hilton. Later movement around the bazaars and the capture of Riviera gives the city’s roads operational importance: surveillance and extraction depend on navigating distinct old and modern zones.",
    details: "Patchwork tenements, corrugated materials, dark shopfronts, apartment blocks, arcologies, and Greek and Armenian jewelers occupy the same visual field. The mixture resists a single ‘ancient’ or ‘futuristic’ Istanbul, though Case’s outsider perspective remains selective.",
    context: "Historically known as Pera in European accounts, Beyoğlu has long been associated with embassies, commerce, minority communities, and entertainment. Modern scholarship and municipal sources help locate the name, while Gibson’s future streets remain fictional.",
    significance: "The district gives the Riviera episode texture and distance from the Sprawl. Technology is unevenly distributed: automated cars and implants cross streets where older trades and buildings persist. That unevenness is central to the novel’s future, not an error to smooth away.",
    caution: "The book’s descriptions come through visiting characters and should not be generalized into claims about Turkish culture. Exact routes are difficult to reconstruct, and Fandom’s attempts to force every street into a present-day map can exceed the prose.",
    related: ["istanbul", "cumhuriyet-caddesi", "spice-bazaar", "turkey-in-neuromancer"],
    tags: ["Beyoğlu", "Istanbul", "Turkey", "Riviera", "urban geography"],
  },
  {
    slug: "brooklyn",
    title: "Brooklyn",
    fandomTitle: "Brooklyn",
    category: "Places",
    spoiler: "Low",
    description: "The enclosed Sprawl borough the Finn invokes to explain why Istanbul’s open vistas make him uncomfortable.",
    type: "Borough within New York and BAMA",
    setting: "The Sprawl",
    chapterContext: "Part Two, Chapter 7",
    connections: "The Finn, Istanbul, New York, Case",
    definition: "Brooklyn appears through the Finn’s preference for crowded, enclosed urban space. It is a home-scale comparison, not a major action setting in Neuromancer.",
    scene: "In Istanbul, the Finn reacts uneasily to a cityscape that feels too open. Brooklyn becomes his counterexample: dense, closed, and comfortable. The remark briefly reveals how thoroughly Sprawl architecture has trained his bodily sense of safety.",
    details: "The description is relational rather than architectural. No Brooklyn street, landmark, or home is shown. Its significance comes from compression into a felt quality—crowding and enclosure—that the Finn carries abroad.",
    context: "Brooklyn is a real New York borough with highly varied neighborhoods. The Finn’s line is one fictional character’s preference and should not be mistaken for a comprehensive urban description.",
    significance: "A single borough name gives the Finn an implied geography beyond his shop. It also reverses a common tourist expectation: openness is not freedom to him. Dense built space offers cover, orientation, and the ordinary pressure of home.",
    caution: "The novel does not state that the Finn was born in Brooklyn, lives there during the heist, or speaks for every Sprawl resident. It offers a comparison, not a biography or census.",
    related: ["the-finn", "new-york-in-the-sprawl", "sprawl-bama", "istanbul"],
    tags: ["Brooklyn", "Finn", "Sprawl", "New York", "urban density"],
  },
  {
    slug: "china-in-neuromancer",
    title: "China in Neuromancer",
    fandomTitle: "China",
    category: "Places",
    spoiler: "Full",
    description: "A dispersed national reference associated with Kuang software, weapons supply chains, and characters’ uneven technological stereotypes.",
    type: "Country and source label",
    setting: "Mentioned from Chiba, the Sprawl, and the matrix run",
    chapterContext: "Across the novel, most importantly the Kuang delivery",
    connections: "Kuang Eleven, Case, Armitage, Shin",
    definition: "China is not a sustained visited setting in Neuromancer. It appears through the Chinese origin assigned to the Kuang icebreaker, ammunition, copied goods, border travel, and remarks about medical expertise.",
    scene: "The most consequential reference arrives when the Kuang Grade Mark Eleven program is delivered for the final run. Earlier street objects and dialogue attach ‘Chinese’ to nerve-splicing reputations and inexpensive ammunition, building a scattered field of technical and commercial associations.",
    details: "The Kuang cassette is advanced, specialized, and compatible with Case’s Japanese deck. This directly complicates any simple hierarchy in which the novel’s China is merely behind Japan. Street dialogue contains bias; the performance of the program supplies stronger evidence about capability.",
    context: "In 1984, China was commonly framed in Western media through economic opening, manufacturing, and Cold War geopolitics. Gibson’s references reflect that historical imagination but do not constitute a forecast of the present People’s Republic or a neutral cultural survey.",
    significance: "China widens the heist’s supply chain. The decisive software is not produced by the crew or by Tessier-Ashpool’s Western-Japanese corporate world. It arrives from another technical network, reminding readers that the operation is assembled across jurisdictions and languages.",
    caution: "Character remarks comparing China and Japan are perspectives, not authoritative worldbuilding facts. ‘Chinese’ does not identify a state agency, named manufacturer, or exact development site for Kuang, and Fandom’s broad country summary should be read critically.",
    related: ["kuang-grade-mark-eleven", "shin", "walther-ppk", "japan-orientalism-globalization"],
    tags: ["China", "Kuang Eleven", "technology", "weapons", "globalization"],
  },
  {
    slug: "copenhagen-grid",
    title: "The Copenhagen Grid",
    fandomTitle: "Copenhagen",
    category: "Places",
    spoiler: "Moderate",
    description: "The low-security university sector where pirates post stolen Bell Europa access codes in luminous public view.",
    type: "City-linked matrix sector",
    setting: "Copenhagen’s academic grid in cyberspace",
    chapterContext: "Part Two, Chapter 5",
    connections: "Case, Dixie Flatline, Bell Europa, Armitage’s London database",
    definition: "Copenhagen appears as a coordinate in the matrix rather than a street visited by Case. Its university fringe is a pirate exchange where stolen corporate entry codes are written into relatively weakly protected academic space.",
    scene: "Dixie directs Case to the board, where he locates a current Bell Europa code. The pair uses that commercial access as one step toward Armitage’s London database, turning an apparently chaotic academic border into practical infrastructure for a covert search.",
    details: "Arts-faculty outlines and colored glyphs make the board visibly untidy beside corporate geometry. Bell Europa changes codes, pirates steal replacements, and the cycle repeats. Security failure is social and procedural, not the result of one magical program.",
    context: "Copenhagen is a real city with major universities and telecommunications networks. The public code board is fictional, though it echoes bulletin-board systems, shared credentials, phreaking culture, and the porous boundaries of early academic networking.",
    significance: "The episode shows a commons used for illicit interoperability. Case reaches a private military history through knowledge circulating among anonymous pirates. Academic openness becomes cover and connective tissue rather than simply a target.",
    caution: "The matrix representation is not a literal map of Copenhagen, and the novel does not identify a particular university. ‘Pirate’s paradise’ is Dixie’s characterization, not evidence that all academic systems are unprotected.",
    related: ["bell-europa", "london-grid", "dixie-flatline", "cyberspace-matrix"],
    tags: ["Copenhagen", "matrix", "pirate board", "Bell Europa", "academic grid"],
  },
  {
    slug: "cumhuriyet-caddesi",
    title: "Cumhuriyet Caddesi",
    fandomTitle: "Cumhuriyet Caddesi",
    category: "Places",
    spoiler: "Low",
    description: "The rainy Istanbul avenue linking the crew’s Hilton base to a streetscape of hotels, police cars, and voiceprinter scribes.",
    type: "Major Istanbul avenue",
    setting: "Beyoğlu/Şişli corridor, Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Case, Molly, Istanbul Hilton, Terzibashjian",
    definition: "Cumhuriyet Caddesi is the real avenue on which Gibson places the Istanbul Hilton and part of the crew’s arrival route. Its name means Republic Avenue.",
    scene: "Case and Molly travel through rain in an automatic Mercedes. Outside the hotels, letter writers shelter with voiceprinters wrapped in plastic while a converted Citroën brings uniformed officers. The avenue frames their first close observation of Istanbul’s mixed technologies.",
    details: "Luxury lodging, automated transport, coin-operated systems, human scribes, plastic sheeting, and police vehicles coexist. The contrast is not simply old versus new; every device is adapted to a different institution, price, and weather exposure.",
    context: "Cumhuriyet Caddesi and the Hilton are real parts of Istanbul. Street alignments and airport functions have changed since 1984, so a present-day map can clarify names but cannot prove the fictional route’s exact turns.",
    significance: "The avenue compresses the chapter’s approach to globalization into a moving view. Case sees familiar brands and unfamiliar practices at once, while the operation depends on a hotel network and local state contact that never become culturally transparent to him.",
    caution: "The scene is focalized through outsiders and contains dated assumptions. It should not support a claim that Istanbul as a whole is technologically ‘behind,’ nor should every vehicle or scribe be treated as representative of Turkey.",
    related: ["istanbul-hilton", "beyoglu", "citroen-in-istanbul", "istanbul"],
    tags: ["Cumhuriyet Caddesi", "Istanbul", "Hilton", "voiceprinter", "street"],
  },
  {
    slug: "grand-bazaar",
    title: "The Grand Bazaar",
    fandomTitle: "Grand Bazaar",
    category: "Places",
    spoiler: "Moderate",
    description: "The monumental Istanbul market whose exterior landmarks orient the crew on the way to Riviera’s smaller Spice Bazaar circuit.",
    type: "Historic covered market",
    setting: "Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Case, Molly, Terzibashjian, Spice Bazaar",
    definition: "The Grand Bazaar, or Kapalıçarşı, is a real Istanbul market briefly incorporated into the crew’s route. It is distinct from the Spice Bazaar where Riviera’s dealer is located.",
    scene: "The automatic car passes the area while Molly, Case, and Terzibashjian move toward the capture. The narration registers scrapyards, damaged statuary, transport, hides, and commercial density outside rather than staging the arrest inside the Grand Bazaar itself.",
    details: "Broken fluted stone, headless figures, a gutted locomotive, carts, and goods form a salvage landscape beside a famous historic complex. The view refuses a preserved museum image; infrastructure and antiquity are reworked into one active economy.",
    context: "The Grand Bazaar dates to the Ottoman period and remains one of Istanbul’s major commercial sites. Its present relation to the Spice Bazaar can expose possible route compression in the novel, but fiction is not required to function as turn-by-turn cartography.",
    significance: "The brief reference enlarges the chase beyond one picturesque market. Riviera’s capture takes place inside a city where monumental commerce, salvage, tourism, state surveillance, and illicit supply overlap.",
    caution: "Fandom sometimes treats the Grand and Spice bazaars as consecutive stops in a fully recoverable itinerary. The prose names both but does not provide enough coordinates to resolve every movement or explain later urban change.",
    related: ["spice-bazaar", "istanbul", "terzibashjian", "beyoglu"],
    tags: ["Grand Bazaar", "Kapalıçarşı", "Istanbul", "market", "Riviera"],
  },
  {
    slug: "istanbul-hilton",
    title: "Istanbul Hilton",
    fandomTitle: "Istanbul Hilton",
    category: "Places",
    spoiler: "Moderate",
    description: "The crew’s polished Istanbul base, where old payment systems and global hotel conventions surround the Riviera operation.",
    type: "International hotel",
    setting: "Cumhuriyet Caddesi, Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Armitage, Case, Molly, the Finn",
    definition: "The Istanbul Hilton is the team’s lodging and coordination point during the search for Peter Riviera. It is a fictionalized future use of a real international hotel site rather than an invented Chiba Hilton counterpart.",
    scene: "Case and Molly arrive to find Armitage and the Finn waiting. Terzibashjian briefs them there, keys and rooms organize the team, and preparations continue after the capture. The lobby also stages small encounters among Riviera, Armitage, and tourists before departure.",
    details: "Pale carpet, velour seating, a questionable-antiquities shop, magnetic room keys, payphones, and a vending console that accepts coins create a luxury interior whose technology feels old beside the crew’s implants and deck.",
    context: "Hilton opened a landmark Istanbul hotel in the 1950s as an emblem of international tourism and modern architecture. Gibson uses the global brand to give Case an immediately legible but culturally incomplete refuge.",
    significance: "The hotel makes international operations mundane. Wintermute’s crew does not occupy a secret fortress; it uses rooms, lobbies, shops, phones, and bookings. Corporate hospitality becomes logistical infrastructure connecting local intelligence to global transit.",
    caution: "The suite layout, room numbers, and staff beyond the narrated details are not specified. The real hotel’s current appearance or policies do not establish the novel’s future version.",
    related: ["cumhuriyet-caddesi", "istanbul", "terzibashjian", "peter-riviera"],
    tags: ["Istanbul Hilton", "Hilton", "Istanbul", "hotel", "Riviera operation"],
  },
  {
    slug: "l5-archipelago",
    title: "The L-5 Archipelago",
    fandomTitle: "L-5 archipelago",
    category: "Places",
    spoiler: "Moderate",
    description: "The orbital region containing Freeside, Zion, transit terminals, and the traffic through which the final operation is assembled.",
    type: "Cluster of habitats and terminals near an Earth–Moon Lagrange region",
    setting: "High orbit",
    chapterContext: "Part Three onward",
    connections: "Freeside, Zion, JAL, Marcus Garvey",
    definition: "The L-5 archipelago is the novel’s collective name for an inhabited orbital zone. It includes separate communities and facilities rather than one island-shaped station.",
    scene: "A JAL shuttle carries the crew from Orly to an orbital terminal. Instead of proceeding directly into Freeside’s resort, they connect with Zion and acclimatize before using tug, yacht, taxis, and docks during the Straylight run.",
    details: "The word archipelago makes separated structures read as islands joined by traffic. Terminals, data exchange, taxis, rotational habitats, freefall zones, and improvised tugs form a geography defined by engineered movement rather than roads or natural terrain.",
    context: "L5 is one of the stable triangular Lagrange regions in the Earth–Moon system and was prominent in 1970s space-colonization proposals. Gibson uses that existing concept while avoiding a detailed orbital-mechanics specification.",
    significance: "The archipelago prevents ‘space’ from functioning as empty distance. It is settled, commercial, religious, and unequal. Freeside and Zion share the region but embody radically different forms of ownership, labor, and memory.",
    caution: "The novel does not provide exact coordinates, station count, travel times for every route, or proof that each named habitat sits precisely at the mathematical L5 point. Freeside, Zion, and the terminal should remain distinct places.",
    related: ["freeside", "zion-cluster", "jal-orbital-shuttle", "marcus-garvey-tug"],
    tags: ["L-5", "Lagrange point", "Freeside", "Zion", "orbital archipelago"],
  },
  {
    slug: "london-grid",
    title: "The London Grid",
    fandomTitle: "London",
    category: "Places",
    spoiler: "Full",
    description: "The matrix sector hiding Armitage’s private archive of Screaming Fist records and Corto’s reconstructed identity.",
    type: "City-linked matrix sector and database location",
    setting: "London in cyberspace",
    chapterContext: "Part Two, Chapter 6",
    connections: "Armitage, Case, Dixie Flatline, Bell Europa",
    definition: "London is important to the plot chiefly because Armitage keeps a private database in its matrix grid. Case does not walk through the physical city during Neuromancer’s present action.",
    scene: "Using access obtained through Bell Europa and coordinates supplied by the Panther Moderns, Case and Dixie reach the database. A Hosaka sifts its files, revealing Screaming Fist, congressional manipulation, Corto’s violence, and the visual evidence connecting Corto to Armitage.",
    details: "The archive mixes police, espionage, news, print, audio, and video records. Its secrecy lies in location and access, not in having one uniform data type. The city name functions as a coordinate within a transnational information landscape.",
    context: "London was already a global telecommunications and finance center in 1984. Gibson projects that role into the matrix without naming a real data center, company, or municipal network.",
    significance: "The London grid holds the operation’s suppressed human history. Reaching it allows Case to convert vague distrust into a causal account of Armitage’s instability. The route also shows piracy as chained access: Copenhagen credentials open one door toward another city’s private archive.",
    caution: "The database is not the whole London grid, and its location does not prove Armitage lives in London or that Wintermute’s core is there. Physical and matrix geography must not be collapsed.",
    related: ["armitage-willis-corto", "copenhagen-grid", "bell-europa", "chapter-06"],
    tags: ["London", "matrix grid", "Armitage", "Corto dossier", "database"],
  },
  {
    slug: "los-angeles",
    title: "Los Angeles in Neuromancer",
    fandomTitle: "Los Angeles",
    category: "Places",
    spoiler: "Moderate",
    description: "A lightly sketched node in Molly and Armitage’s recruitment travels and in Zion’s founding diaspora.",
    type: "City reference",
    setting: "North America, outside the main narrated route",
    chapterContext: "Reported backstory",
    connections: "Molly, Armitage, Zion founders, Sense/Net",
    definition: "Los Angeles is mentioned rather than staged at length. Molly recalls traveling there with Armitage, and one of Zion’s original orbital workers came from the city.",
    scene: "During her account of Armitage’s strange movements, Molly says he could abruptly redirect their itinerary from Los Angeles toward Macau and China. The reference establishes a recruitment period already operating across continents before Case joins.",
    details: "No streetscape or hotel interior receives sustained description. Los Angeles functions as a network node attached to air travel, Sense/Net corporate reach, and the terrestrial origin of one founder who refuses return to Babylon.",
    context: "The real city’s aerospace, media, and Pacific connections made it a legible future-world waypoint in 1984. The novel does not specify which industry explains Armitage’s visit.",
    significance: "The sparse mention gives scale to Wintermute’s preparation. Case enters a plan whose people have already crossed Los Angeles, Macau, Zhongshan, and Chiba, while Zion’s history turns the same city into a point of departure for a different social project.",
    caution: "Fandom combines references from several Sprawl stories on one city page. This entry isolates Neuromancer’s evidence and does not import New Rose Hotel events into Case’s plot.",
    related: ["molly", "armitage-willis-corto", "zion-founders-elders", "sense-net"],
    tags: ["Los Angeles", "Armitage", "Molly", "Zion", "travel"],
  },
  {
    slug: "new-jersey",
    title: "New Jersey in Neuromancer",
    fandomTitle: "New Jersey",
    category: "Places",
    spoiler: "Moderate",
    description: "The Sprawl location from which Brood routes the Panther Moderns’ hijacked satellite link during the Sense/Net raid.",
    type: "State absorbed into the Sprawl’s operational geography",
    setting: "BAMA",
    chapterContext: "Part Two, Chapter 4",
    connections: "Brood, Panther Moderns, Sons of Christ the King, Sense/Net",
    definition: "New Jersey appears in Neuromancer as the terrestrial base of the Moderns’ link operator. It is one point in a communications path that rises to a geosynchronous satellite and returns to the heist team.",
    scene: "Brood uses a crude dish in New Jersey to send scrambled signals through the Sons of Christ the King’s satellite. Those signals coordinate Molly, Case, and the timed disinformation campaign against the Sense/Net pyramid.",
    details: "The physical location is reduced to practical radio geometry: a dish, a satellite path, and a link man. New Jersey’s position within dense BAMA makes it nearby in social terms while orbital relaying lets it remain remote from the target.",
    context: "New Jersey has a long telecommunications and industrial history, including Bell Labs, but the novel does not state that historical connection as Brood’s reason for operating there. Wider Gibson stories use the state for unrelated events.",
    significance: "The location makes the heist distributed. Case is not simply connected to Molly; both depend on an operator in another jurisdiction using a satellite owned by an uninvolved sect. Infrastructure becomes a temporary coalition assembled without consent.",
    caution: "No town, building, or exact dish design is supplied. Events from Burning Chrome and The Gernsback Continuum should not be merged into this page merely because Fandom’s New Jersey entry covers multiple works.",
    related: ["brood", "sons-of-christ-the-king", "panther-moderns", "sprawl-bama"],
    tags: ["New Jersey", "Brood", "satellite", "Panther Moderns", "BAMA"],
  },
  {
    slug: "new-york-in-the-sprawl",
    title: "New York in the Sprawl",
    fandomTitle: "New York",
    category: "Places",
    spoiler: "Moderate",
    description: "A former city still named inside BAMA, containing the Finn’s shop, Sense/Net’s corporate presence, and matrix landmarks.",
    type: "Metropolitan region within BAMA",
    setting: "The Sprawl",
    chapterContext: "Part Two and later references",
    connections: "The Finn, Sense/Net, Brooklyn, New York Public Library",
    definition: "New York remains a meaningful name within the continuous Boston–Atlanta axis. Neuromancer uses several of its boroughs and institutions without pausing to define a surviving municipal boundary.",
    scene: "Case and Molly move through the Sprawl to the Finn’s Manhattan-area shop, the Sense/Net operation targets a pyramid in the metropolitan network, and Case later brushes the library’s matrix ICE while switching between cyberspace and Molly’s sensorium.",
    details: "Physical transit, corporate architecture, old borough names, hacker shops, libraries, and satellite footprints occupy different layers of one metropolitan environment. The city survives as memory and address inside a larger built continuum.",
    context: "New York’s financial, media, and communications concentration made it central to cyberpunk urban imagination. Gibson extrapolates density and regional expansion; BAMA is not a historical planning proposal that came to pass.",
    significance: "The city gathers several forms of information power: commercial media, public knowledge, informal repair, and orbital communications. None owns the whole network, which is why the heist can move among them.",
    caution: "Fandom’s phrase ‘perhaps also the Sense/Net Pyramid’ signals uncertainty about exact placement. This page preserves that uncertainty and does not assign every Sprawl landmark a modern street address.",
    related: ["sprawl-bama", "the-finn", "sense-net-pyramid", "new-york-public-library"],
    tags: ["New York", "Sprawl", "BAMA", "Sense/Net", "Manhattan"],
  },
  {
    slug: "new-york-public-library",
    title: "New York Public Library",
    fandomTitle: "New York Public Library",
    category: "Organizations",
    spoiler: "Moderate",
    description: "A public information institution represented by relatively simple ICE, used by Case as a matrix landmark while riding Molly’s simstim.",
    type: "Public library and matrix data system",
    setting: "New York / the matrix",
    chapterContext: "Part Two, Chapter 4",
    connections: "Case, Molly, simstim, cyberspace",
    definition: "The New York Public Library appears as a recognizable institutional construct in the matrix. Case does not conduct a library research session; he uses its ICE as a nearby surface while moving between his deck and Molly’s live sensorium.",
    scene: "After switching away from Molly’s feed, Case drops toward the library’s defenses and automatically counts possible openings. He then returns to her sensorium. The moment shows professional habit continuing even during an emotionally and tactically divided interface session.",
    details: "The ICE is described as primitive relative to high-security corporate targets. Public status does not mean no protection, but the visual wall is a modest landmark rather than black ICE designed to kill an intruder.",
    context: "The NYPL is a real public institution founded in the nineteenth century. Its future matrix presence is fictional, though libraries were early adopters of computerized catalogs and networked information access.",
    significance: "A public library helps make cyberspace more than a field of corporate towers. Shared civic knowledge has a representation there, and Case’s reflexive scan reveals how a cowboy reads any protected surface for weakness.",
    caution: "The novel does not say Case enters, damages, or steals from the library. Counting windows is not the same as launching a full intrusion, and the matrix wall should not be confused with the physical landmark building.",
    related: ["cyberspace-matrix", "simstim-sensorium", "chapter-04", "new-york-in-the-sprawl"],
    tags: ["New York Public Library", "NYPL", "ICE", "matrix", "public information"],
  },
  {
    slug: "orly",
    title: "Orly",
    fandomTitle: "Orly",
    category: "Places",
    spoiler: "Moderate",
    description: "The aging Paris airport complex where terrestrial travel hands the crew to JAL’s orbital shuttle system.",
    type: "Airport and shuttle-transfer site",
    setting: "Outside Paris",
    chapterContext: "Parts Two and Three",
    connections: "Case, Molly, Armitage, JAL",
    definition: "Orly is the real Paris airport adapted in the novel as a transfer point for both ordinary international flights and launches toward the L-5 archipelago.",
    scene: "The crew passes through Orly during terrestrial travel and later returns from Istanbul. Old terminals give way to shuttle pads protected by wet-concrete blast deflectors. From there they board JAL for orbit.",
    details: "Weathered architecture, multilingual graffiti, launch infrastructure, and airline procedure coexist. Spaceflight does not erase airport waiting, signage, security, or the smell and discomfort of mass transit; it extends the terminal system upward.",
    context: "Paris Orly was a major international gateway before Charles de Gaulle became dominant. Gibson’s use of an older airport for orbital service produces a layered future in which obsolete and advanced infrastructure remain connected.",
    significance: "Orly is the seam between the novel’s terrestrial chase and orbital endgame. The transition occurs through commercial travel rather than a secret rocket base, making access to space feel expensive and bodily difficult but institutionally routine.",
    caution: "The launch pads, orbital route, and future terminal layout are fictional. Changes to real Orly since 1984 do not correct or invalidate the novel’s imagined facility.",
    related: ["jal-orbital-shuttle", "l5-archipelago", "paris-in-neuromancer", "chapter-08"],
    tags: ["Orly", "Paris", "airport", "JAL", "orbital shuttle"],
  },
  {
    slug: "paris-in-neuromancer",
    title: "Paris in Neuromancer",
    fandomTitle: "Paris",
    category: "Places",
    spoiler: "Moderate",
    description: "A transit, craft, fashion, and legal reference point connecting Riviera’s route, the jeweled head, and Turing authority.",
    type: "European city and matrix/cultural reference",
    setting: "France",
    chapterContext: "Across the Istanbul and Freeside movement",
    connections: "Orly, Riviera, Turing agents, Tessier-Ashpool head",
    definition: "Paris is not one extended action setting in Neuromancer. It appears through flights, institutions, luxury craft, style labels, and the French-speaking agents who detain Case.",
    scene: "The crew moves through Paris-area transit on the way to and from Istanbul and orbit. Smith’s provenance search attributes the head’s enamel work to a Paris specialist, while Freeside fashion and the Registry agents continue the city’s association with designed surfaces.",
    details: "Airports, craft networks, cosmetic tanning, leather, cigarettes, and legal interrogation form a scattered Parisian field. These are markers circulating globally, not a complete portrait of the physical city.",
    context: "Paris’s longstanding associations with luxury goods, fashion, diplomacy, and aviation make the references legible. Gibson uses brand-like cultural shorthand whose limitations deserve attention rather than treating it as neutral national essence.",
    significance: "Paris helps connect traditional handcraft to advanced systems. The same world that produces matrix law and orbital travel still values enamel specialists and fashion codes, undercutting any clean break between historical craft and cybernetic modernity.",
    caution: "Fandom’s Paris page combines multiple Gibson works. This entry includes only Neuromancer-relevant material and does not treat every French object or agent as proof of a unified Paris institution.",
    related: ["orly", "turing-registry", "cloisonne-head-terminal", "michele"],
    tags: ["Paris", "France", "Orly", "craft", "Turing Registry"],
  },
  {
    slug: "rio",
    title: "Rio de Janeiro",
    fandomTitle: "Rio",
    category: "Places",
    spoiler: "Full",
    description: "The Brazilian city and matrix sector anchoring Neuromancer’s physical core behind dense white ICE.",
    type: "City, matrix sector, and AI hardware location",
    setting: "Brazil / cyberspace",
    chapterContext: "Revealed from Part Three through the ending",
    connections: "Neuromancer AI, Dixie Flatline, Case, Wintermute",
    definition: "Rio is the earthly location associated with the second Tessier-Ashpool intelligence. The name can mean the physical city, its busy matrix sector, or—by conversational shorthand—the remote AI system situated there.",
    scene: "Dixie recounts flatlining against a dense white construct in the Rio sector. Later Case encounters the AI as a boy on a beach and learns its complementary relation to Wintermute. The final run links the Berne and Rio systems through human and software action.",
    details: "Government and commercial forms make the sector visually active around the defended cube. The AI’s beach is not a literal Rio shoreline; it is a constructed environment that draws on place, memory, and identity while hardware remains elsewhere.",
    context: "Rio de Janeiro is a real global city whose beach imagery is immediately recognizable. The novel uses that association without identifying an actual neighborhood, data center, or corporation capable of hosting Neuromancer.",
    significance: "Separating city, core, matrix icon, and beach prevents a common reading error. Neuromancer can present itself through an environment while remaining legally and materially tied to Brazilian hardware. Place persists beneath apparent disembodiment.",
    caution: "The Fandom Rio page also draws on Johnny Mnemonic and other corporate references. Those are wider-Sprawl context, not proof that every Rio mainframe or alias concerns Neuromancer.",
    related: ["neuromancer-ai", "neuromancer-rio-core", "neuromancers-beach", "dixie-flatline"],
    tags: ["Rio de Janeiro", "Neuromancer AI", "matrix", "Brazil", "AI core"],
  },
  {
    slug: "shiga-night-city",
    title: "Shiga Market in Night City",
    fandomTitle: "Shiga",
    category: "Places",
    spoiler: "Low",
    description: "The market area where Case negotiates with Shin among sushi, mutant fish, insects, horseradish tins, and hidden weapons.",
    type: "Named Night City market area",
    setting: "Chiba / Night City",
    chapterContext: "Part One, Chapter 1",
    connections: "Case, Shin, Wage, Walther PPK",
    definition: "Shiga is the name attached to the market zone where Case seeks a weapon. It should not automatically be equated with a journey to modern Shiga Prefecture; the prose locates the encounter within his immediate Chiba movements.",
    scene: "Case meets Shin behind a sushi stall, rejects a taser, leaves, and returns for an old pistol. The repeated visit gives his fear of Wage a measurable duration while the market continues operating around the illegal exchange.",
    details: "Blue mutant carp, mantises, crickets in bamboo, food preparation, bulk horseradish containers, money, and weapons share a tight commercial space. Biotechnology appears as ordinary inventory beside older forms of urban market life.",
    context: "Shiga is also the name of a real Japanese prefecture east of Kyoto, which creates ambiguity in English-language fan summaries. No long intercity trip fits the opening’s narrated sequence, so a local market or transferred name is the safer reading.",
    significance: "The setting makes contraband part of a larger retail ecology rather than a separate criminal warehouse. Case’s access comes through knowing whom to ask behind an ordinary stall.",
    caution: "The exact geographic status of ‘Shiga’ is not explained, and modern maps cannot resolve it with certainty. This page labels the ambiguity instead of asserting that Case travels hundreds of kilometers during the scene.",
    related: ["shin", "walther-ppk", "night-city", "chapter-01"],
    tags: ["Shiga", "Night City", "market", "Shin", "Chiba"],
  },
  {
    slug: "shinjuku",
    title: "Shinjuku",
    fandomTitle: "Shinjuku",
    category: "Places",
    spoiler: "Low",
    description: "A Tokyo underworld coordinate associated with Snake Man, invoked more than physically explored in Case’s Chiba crisis.",
    type: "Tokyo ward and underworld reference",
    setting: "Tokyo",
    chapterContext: "Opening black-market dealings",
    connections: "Snake Man, Case, the Japanese underworld",
    definition: "Shinjuku is a real Tokyo ward attached to Snake Man’s criminal world. Neuromancer does not give Case an extended narrated visit there during the opening Chiba sequence.",
    scene: "Case reaches Snake Man by phone while trying to sell pituitary glands and raise cash. Shinjuku supplies the remote urban coordinate behind the voice, contrasting with Case’s immediate confinement in Night City.",
    details: "The novel’s broader Japanese cityscape uses stations, neon, communications, and underworld contacts as a connected commercial night. The specific deal, however, arrives as disembodied talk rather than street description.",
    context: "Shinjuku was already famous by 1984 for its enormous station, skyscraper district, nightlife, and entertainment areas. Later Gibson stories use it more extensively; those descriptions should not be pasted into Neuromancer’s brief reference.",
    significance: "The name expands Case’s market beyond the port without giving him freedom. He can call across the metropolitan system, but remote connection cannot solve an unreliable buyer’s cash-flow problem.",
    caution: "Most of the detailed Shinjuku material on Fandom comes from New Rose Hotel. This page separates that later story from what Neuromancer establishes about Snake Man and Case.",
    related: ["snake-man", "chiba-underworld", "night-city", "japan-orientalism-globalization"],
    tags: ["Shinjuku", "Tokyo", "Snake Man", "underworld", "Japan"],
  },
  {
    slug: "sikkim-steel-combine",
    title: "Sikkim and the Steel Combine",
    fandomTitle: "Sikkim",
    category: "Places",
    spoiler: "Moderate",
    description: "A Himalayan name attached to pink matrix spheres, showing how remote industry becomes navigable visual form for Case.",
    type: "Country/region reference and industrial matrix construct",
    setting: "Cyberspace",
    chapterContext: "A conversation between Case and Dixie",
    connections: "Case, Dixie Flatline, matrix industry",
    definition: "Sikkim appears through a steel combine represented in the matrix by a complex of pink spheres. The physical works and political arrangement behind that label are not visited.",
    scene: "While talking with Dixie, Case strikes controls restlessly and shifts near the Sikkim construct. When contact resumes, the same coordinates provide a recognizable point in the data landscape.",
    details: "Pink spheres do not visually imitate a steel mill. They are an interface abstraction chosen or standardized to make ownership and relation perceptible. Shape and color become navigational identity rather than industrial realism.",
    context: "Sikkim was an independent Himalayan kingdom until becoming an Indian state in 1975. Calling it a country may reflect the novel’s language, an alternate future, or loose usage; the text does not explain a later political change.",
    significance: "The tiny reference gives the matrix global industrial density. Case can drift from personal conversation to a distant steel enterprise with a few movements, making economic geography immediately adjacent without making it culturally known.",
    caution: "The novel does not name the combine, describe its products, or establish that Sikkim is sovereign in Case’s era. The pink spheres are a representation, not literal architecture.",
    related: ["cyberspace-matrix", "dixie-flatline", "console-cowboys", "zaibatsus-corporate-order"],
    tags: ["Sikkim", "steel combine", "matrix", "pink spheres", "industry"],
  },
  {
    slug: "spice-bazaar",
    title: "The Spice Bazaar",
    fandomTitle: "Spice Bazaar",
    category: "Places",
    spoiler: "Moderate",
    description: "The old Istanbul market where software, perfume, animals, drugs, and Riviera’s routine occupy one dense commercial system.",
    type: "Historic market and illicit supply zone",
    setting: "Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Ali, Peter Riviera, Molly, the Finn",
    definition: "The Spice Bazaar—also called the Egyptian Bazaar—is the central setting for locating and capturing Riviera. Gibson overlays a real Ottoman market with future software sales, suspended advertising, and an illicit drug circuit.",
    scene: "Terzibashjian and the crew track Riviera toward Ali’s shop near the bazaar. Molly waits outside the dealer’s alley and captures him as he emerges. She later returns for the supply on which his management depends.",
    details: "Soot-darkened roofing, green ironwork, steam, spices, software, perfume, animals, cafes, and a preserved horse crowd the route. The Finn’s fascination with the horse turns an extinct animal into a market relic touched by passersby.",
    context: "The real Mısır Çarşısı dates to the seventeenth century and remains an active Istanbul market. The novel’s species extinction, software stalls, ads, and criminal arrangements are future inventions.",
    significance: "The bazaar makes information and chemicals ordinary commodities beside traditional goods. Riviera’s advanced implant does not free him from supply; it embeds him in one of the city’s oldest commercial forms.",
    caution: "The prose does not authorize every historical claim repeated in Fandom summaries, and the name of the Ottoman patron is often misstated online. Real-world history is used here only to orient the fictional scene.",
    related: ["ali", "peter-riviera", "istanbul", "grand-bazaar"],
    tags: ["Spice Bazaar", "Istanbul", "Riviera", "Ali", "market"],
  },
  {
    slug: "switzerland-in-neuromancer",
    title: "Switzerland in Neuromancer",
    fandomTitle: "Switzerland",
    category: "Places",
    spoiler: "Full",
    description: "The banking and AI-law jurisdiction that anchors Wintermute in Berne and gives numbered accounts recurring power.",
    type: "Country, jurisdiction, and financial network",
    setting: "Europe and the matrix",
    chapterContext: "Across the Smith story, Berne probe, and Turing arrest",
    connections: "Wintermute, Berne, Turing Registry, Tessier-Ashpool",
    definition: "Switzerland appears through banking, corporate addresses, AI citizenship, numbered accounts, and the Berne mainframe. It functions as a legal-financial environment rather than a tourist setting visited in detail.",
    scene: "The clone who retrieves the head pays Smith from a Swiss account; Wintermute’s hardware is associated with Berne; Turing agents discuss a prospective proceeding connected to the AI. These references link money, ownership, and machine personhood.",
    details: "Cool geometric bank forms in cyberspace turn the country’s financial reputation into visible terrain. Legal status remains divided: an AI can receive a limited form of citizenship while also being owned, regulated, and threatened with automatic destruction.",
    context: "Swiss banking secrecy and international finance were powerful cultural shorthand in 1984. The novel’s AI law and exact account mechanisms are fictional, while later changes to real secrecy rules should not be projected backward.",
    significance: "Switzerland makes the AI conflict institutional. Wintermute is neither a free-floating ghost nor merely a corporate program; it has hardware, nationality-like status, owners, accounts, and regulators whose categories do not resolve its personhood.",
    caution: "Zurich is not Switzerland’s capital—Bern is the federal city—and Fandom’s claim otherwise is incorrect. The novel does not provide a complete Swiss AI statute or confirm every jurisdictional step the agents describe.",
    related: ["berne", "zurich", "turing-registry", "wintermute"],
    tags: ["Switzerland", "Berne", "banking", "AI law", "Wintermute"],
  },
  {
    slug: "topkapi",
    title: "Topkapı Palace",
    fandomTitle: "Topkapi",
    category: "Places",
    spoiler: "Moderate",
    description: "The palace garden where Molly and Case decompress after Riviera’s capture and compare the present operation with Armitage’s hidden past.",
    type: "Historic palace and museum",
    setting: "Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Molly, Case, Armitage, the Finn",
    definition: "Topkapı is a real Ottoman palace complex used as a quiet post-capture setting. The novel filters its history through Molly’s irreverent explanation and Case’s operational anxiety.",
    scene: "At dawn, Molly brings Case through the grounds after Riviera has been taken. Among ponds, stone paths, relics, and gardens, Case explains what the London archive revealed about Corto and Armitage.",
    details: "Carp, water plants, an iron deer, octagonal paving, jewels, weapons, and a displayed relic make the museum both serene and crowded with preserved power. Molly compares it to the Finn’s shop, converting imperial collection into a form Case can understand.",
    context: "Topkapı served Ottoman sultans for centuries and later became a museum. Molly’s description of a royal private sexual space is blunt character speech, not a complete historical account of the harem or palace administration.",
    significance: "The garden creates a rare reflective interval. Imperial objects surround a conversation about a modern military conspiracy, suggesting that institutions preserve violence and legitimacy through collections, stories, and controlled access.",
    caution: "The scene does not prove Molly has scholarly expertise, and her relic claims should not be repeated as neutral museum catalog data. Present-day visitor routes also cannot fix every fictional movement.",
    related: ["istanbul", "armitage-willis-corto", "the-finn", "chapter-07"],
    tags: ["Topkapı", "Istanbul", "Molly", "Case", "museum"],
    quote: {
      text: "Sort of a private whorehouse for the King.",
      citation: "Neuromancer, Part Two, Chapter 7",
      note: "Molly reduces palace history to provocative street-language shorthand.",
    },
  },
  {
    slug: "toulon",
    title: "Toulon",
    fandomTitle: "Toulon",
    category: "Places",
    spoiler: "Full",
    description: "The French institutional setting where Corto’s catatonia becomes an experiment in computer-mediated psychotherapy.",
    type: "City associated with a government psychiatric institution",
    setting: "Southern France",
    chapterContext: "Armitage/Corto dossier in Part Two, Chapter 6",
    connections: "Willis Corto, Wintermute, Paris clinicians, student programmers",
    definition: "Toulon appears in the dossier as the location near which a government institution runs an experimental cybernetic treatment program. Corto arrives there after becoming catatonic in Paris.",
    scene: "Selected patients receive microcomputers and help from students, with programming used inside a model for treating schizophrenia. Wintermute reaches Corto through this arrangement, studies his obsessions, and constructs the stable Armitage persona.",
    details: "The treatment is described institutionally rather than clinically: random selection, computers, students, models, and one apparent success. The absence of a detailed medical protocol makes the AI’s intervention difficult to separate from the official experiment.",
    context: "Toulon is a real French Mediterranean port with major naval importance. The psychiatric facility and successful computer-mediated cure are fictional, though 1970s–80s research did explore cybernetics, computing, and mental-health models.",
    significance: "Toulon is where political damage becomes machine opportunity. The state’s failed subject is made functional, but functionality means a persona usable by Wintermute. Cure, control, and recruitment become impossible to separate.",
    caution: "The novel does not name the institution, doctors, students, software, or diagnosis beyond the dossier’s terms. It should not be treated as evidence about real schizophrenia treatment or about any actual Toulon hospital.",
    related: ["armitage-willis-corto", "wintermute", "congressional-aide", "chapter-06"],
    tags: ["Toulon", "Corto", "psychotherapy", "Wintermute", "France"],
  },
  {
    slug: "turkey-in-neuromancer",
    title: "Turkey in Neuromancer",
    fandomTitle: "Turkey",
    category: "Places",
    spoiler: "Moderate",
    description: "The national frame for the Istanbul episode, where global hotels, old markets, secret policing, and uneven infrastructure intersect.",
    type: "Country and political-cultural setting",
    setting: "Primarily Istanbul",
    chapterContext: "Part Two, Chapter 7",
    connections: "Terzibashjian, Riviera, Case, Molly",
    definition: "Turkey is represented through a short Istanbul mission rather than a national survey. The chapter combines recognizable locations with a fictional future involving secret-police pressure, dissident networks, automated cars, and older payment systems.",
    scene: "Armitage’s team meets Terzibashjian, follows Riviera through hotels and bazaars, captures him outside a dealer’s shop, and departs through Yeşilköy for Paris. The country becomes operational through local language, surveillance, currency, streets, and contacts.",
    details: "Coins, voiceprinters, hydrogen conversions, global hotel brands, multilingual commerce, police vehicles, software stalls, and historic markets coexist. The uneven field is observed by visitors whose judgments are often impatient or dismissive.",
    context: "Turkey in the early 1980s had recently experienced a military coup and major political repression, while Istanbul was a rapidly changing metropolis. That context can illuminate the secret-police atmosphere but does not make the fictional operation documentary realism.",
    significance: "The episode tests the crew outside systems Case knows. Technical sophistication is not distributed on one scale: Riviera’s implants, an automatic Mercedes, paper communication, and old market architecture are all effective in different domains.",
    caution: "Fandom calls the country ‘backwards and sluggish,’ but that is an overgeneralization built from outsider impressions and selected objects. This page treats orientalist framing as part of the reading problem, not as a canonical national fact.",
    related: ["istanbul", "terzibashjian", "spice-bazaar", "yesilkoy"],
    tags: ["Turkey", "Istanbul", "globalization", "secret police", "Riviera"],
  },
  {
    slug: "yenisehir-palas-oteli",
    title: "Yenişehir Palas Oteli",
    fandomTitle: "Yenishehir Palas Oteli",
    category: "Places",
    spoiler: "Moderate",
    description: "The Istanbul hotel where Riviera performs for tourists while local police attention makes the management nervous.",
    type: "Performance hotel",
    setting: "Istanbul",
    chapterContext: "Riviera surveillance in Part Two, Chapter 7",
    connections: "Peter Riviera, Terzibashjian, Turkish police",
    definition: "Yenişehir Palas Oteli is a hotel on Riviera’s Istanbul performance circuit. Terzibashjian treats it as touristic and useful for surveillance rather than as the crew’s own base.",
    scene: "Riviera presents his projection work there before the capture sequence. Interest from Turkish police places pressure on management and helps define the performer as already entangled with official and illicit networks.",
    details: "The novel gives the hotel less architectural detail than the Hilton or Vingtième Siècle. Its function is social: a venue where a foreign or marginal performer can attract guests, income, and unwanted attention.",
    context: "Hotels with the Yenişehir or Palas naming pattern exist in Turkey, but present listings do not prove a direct model. Fandom’s search for an exact Ankara namesake is suggestive, not confirmation of authorial intent.",
    significance: "The venue shows Riviera’s projection implants operating as livelihood before they become a weapon and an access strategy. Performance, policing, and drug supply create the routine that Terzibashjian can map.",
    caution: "The hotel’s exact modern counterpart, address, clientele, and show content are not established. It should not be conflated with the Istanbul Hilton or the later Freeside restaurant performance.",
    related: ["peter-riviera", "terzibashjian", "istanbul-hilton", "dreaming-real"],
    tags: ["Yenişehir Palas Oteli", "Istanbul", "Riviera", "hotel", "performance"],
  },
  {
    slug: "yesilkoy",
    title: "Yeşilköy",
    fandomTitle: "Yesilkoy",
    category: "Places",
    spoiler: "Moderate",
    description: "The Istanbul airport district from which the assembled crew leaves Turkey for Paris and the orbital stage of the mission.",
    type: "Istanbul district and airport reference",
    setting: "European Istanbul",
    chapterContext: "End of Part Two, Chapter 7",
    connections: "Case, Molly, Armitage, Riviera",
    definition: "Yeşilköy is the district historically associated with Istanbul’s major international airport. In the novel it names the departure point for the team’s flight to Paris after Riviera’s capture.",
    scene: "Armitage books Case, Molly, Riviera, and himself onto a Turkish airline flight out of Yeşilköy. The airport closes the Istanbul operation and turns the dangerous captive into a passenger moving through ordinary international procedure.",
    details: "The scene emphasizes schedule, booking, packing, drug supply, and group management more than terminal architecture. Mobility depends on documentation and an airline system that can absorb a coerced recruit without exposing the plan.",
    context: "Yeşilköy housed what became Atatürk Airport, Istanbul’s main commercial airport for decades. Commercial passenger operations shifted to the new Istanbul Airport in 2019, a later real-world change irrelevant to the novel’s future route.",
    significance: "The district is a hinge between local capture and global transport. Wintermute’s elaborate plan repeatedly relies on ordinary systems—hotels, taxis, and airlines—that work precisely because no dramatic technology marks the crew as exceptional.",
    caution: "The book’s spelling omits Turkish diacritics, and current airport status should not be used to rename the fictional departure. The exact flight procedures and terminal are not described.",
    related: ["istanbul", "orly", "turkey-in-neuromancer", "peter-riviera"],
    tags: ["Yeşilköy", "Istanbul", "airport", "Turkey", "Riviera"],
  },
  {
    slug: "zurich",
    title: "Zurich",
    fandomTitle: "Zurich",
    category: "Places",
    spoiler: "Full",
    description: "The financial and craft reference point linking numbered accounts, matrix banking geometry, and the makers of the jeweled head.",
    type: "Swiss city, banking center, and provenance node",
    setting: "Switzerland / cyberspace",
    chapterContext: "Smith’s head story and wider matrix references",
    connections: "Smith, Tessier-Ashpool, cloisonné head, Swiss banks",
    definition: "Zurich appears through two kinds of specialized trust: artisans there help construct Tessier-Ashpool’s ornate terminal, and accounts associated with Swiss banking move money without revealing an ordinary personal identity.",
    scene: "Smith’s provenance work traces part of the head’s fabrication to two Zurich craftspeople. When the clone retrieves the object, payment arrives through a numbered Swiss account. The exchange joins connoisseurship, coercion, and finance.",
    details: "In the matrix, Swiss commercial banking appears as cool geometric intricacy. In the physical object, Zurich signifies fine handwork. The city therefore sits on both sides of Gibson’s historical collage: computational abstraction and patient luxury craft.",
    context: "Zurich is Switzerland’s largest city and a major global financial center, but it is not the national capital. Numbered accounts are real financial instruments; the instant recovery payment and matrix scenery belong to the fiction.",
    significance: "The city helps explain Tessier-Ashpool power as coordination rather than simple ownership. The family can commission specialists across Europe, protect the result with private force, and settle a dangerous transaction through international banking.",
    caution: "The novel does not name the artisans, bank, account holder, or workshop. Fandom’s wider Zurich material from Burning Chrome is useful Sprawl context but not part of Smith’s Neuromancer encounter.",
    related: ["smith", "cloisonne-head-terminal", "switzerland-in-neuromancer", "tessier-ashpool-sa"],
    tags: ["Zurich", "Swiss banking", "talking head", "artisans", "Tessier-Ashpool"],
  },
];

export const fandomMicroPlaceArticles = records.map(buildFandomMicroArticle);
