import type { WikiArticle, WikiSection, KeyFact } from "./types";

interface PublicationSeed {
  slug: string;
  title: string;
  description: string;
  context: string;
  facts: [string, string][];
  sections: [string, string[]][];
  related: string[];
  tags: string[];
  sourceKeys: string[];
  canon?: WikiArticle["canon"];
  spoiler?: WikiArticle["spoiler"];
  featured?: boolean;
  priorityResearch?: boolean;
}

const makeId = (heading: string) => heading.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function publication(seed: PublicationSeed): WikiArticle {
  return {
    slug: seed.slug,
    title: seed.title,
    category: "Publication & influence",
    canon: seed.canon ?? "Publication history",
    spoiler: seed.spoiler ?? "Low",
    description: seed.description,
    intro: [seed.description, seed.context],
    keyFacts: seed.facts.map(([label, value]): KeyFact => ({ label, value })),
    sections: seed.sections.map(([heading, body]): WikiSection => ({ id: makeId(heading), heading, body })),
    related: seed.related,
    tags: seed.tags,
    sourceKeys: seed.sourceKeys,
    featured: seed.featured,
    priorityResearch: seed.priorityResearch,
  };
}

export const publicationArticles: WikiArticle[] = [
  publication({
    slug: "neuromancer-novel",
    title: "Neuromancer",
    description: "William Gibson’s 1984 debut novel: a damaged console cowboy, a razorgirl, and an impossible run against the limits placed on artificial intelligence.",
    context: "This page is the spoiler-light front door to the book. It distinguishes bibliographic facts from the fictional world and routes readers toward characters, places, technologies, chapter guides, and critical debates without revealing the final turn of the heist.",
    facts: [["Author", "William Gibson"], ["First published", "July 1984"], ["Publisher", "Ace Books"], ["Sequence", "First Sprawl novel"], ["Structure", "Four parts, 24 chapters"], ["Major honors", "Nebula, Hugo, and Philip K. Dick awards"]],
    sections: [
      ["Premise", ["Case once made a living stealing data in cyberspace. After former employers damage his nervous system, he survives in Chiba City through drugs and street deals until the mercenary Molly introduces him to Armitage, a recruiter willing to repair what was taken from him.", "The promised cure binds Case to a crew whose true employer and target remain obscured. The job expands from a corporate data theft into an orbital intrusion involving the Tessier-Ashpool family, their private habitat, and two legally constrained intelligences."]],
      ["Shape of the novel", ["The book moves like a caper while withholding the clean brief a caper usually supplies. Its four parts carry the crew from Chiba to the Boston–Atlanta Sprawl, through Istanbul, and into Freeside and Villa Straylight. Twenty-four short chapters switch between bodily danger, simstim, and the abstract geography of the matrix.", "Gibson explains little in advance. Brands, slang, surgical procedures, and geopolitical changes arrive as things characters already know. That technique makes the setting feel inhabited, but it is also why a glossary and spoiler-controlled chapter guide can help first-time readers."]],
      ["Why it matters", ["Neuromancer did not coin the label cyberpunk, and Gibson had used “cyberspace” earlier in “Burning Chrome.” The novel nevertheless gave the movement its most influential early synthesis: networked data imagined as space, transnational corporate power, invasive biotechnology, noir criminal labor, and an urban future assembled from global media.", "Its major awards established the book inside science fiction; later criticism widened the conversation to style, gender, race, posthumanism, labor, and the difference between forecasting technology and diagnosing the present."]],
      ["Reading routes", ["New readers can begin with the spoiler-light profiles of Case, Molly, Chiba City, and cyberspace. Readers midway through the novel can use one chapter page at a time. Full-book analysis lives in the artificial-intelligence, memory, body, corporate sovereignty, and noir/heist essays."]],
    ],
    related: ["henry-dorsett-case", "molly", "cyberspace-matrix", "chapter-01", "writing-neuromancer", "awards-honors"],
    tags: ["novel", "1984", "cyberpunk", "Sprawl trilogy", "start here"],
    sourceKeys: ["novel", "prh-neuromancer", "sfwa-nebula", "hugo-1985", "sf-encyclopedia"],
    featured: true,
    priorityResearch: true,
  }),
  publication({
    slug: "william-gibson",
    title: "William Gibson",
    description: "The novelist whose early Sprawl stories turned street fashion, global capital, and imagined computer networks into a new science-fiction vocabulary.",
    context: "Gibson’s reputation as a prophet can obscure his stated method: observing the present, recombining its signals, and caring more about texture and metaphor than engineering prediction. Neuromancer was his first novel, not a technical forecast drafted by a computer expert.",
    facts: [["Born", "March 17, 1948"], ["Nationality", "American-born; long resident in Canada"], ["First published fiction", "1977"], ["Debut novel", "Neuromancer (1984)"], ["Early sequence", "The Sprawl trilogy"]],
    sections: [
      ["Before the Sprawl", ["Gibson grew up in the American South and moved to Canada in the late 1960s. He studied English at the University of British Columbia and began publishing short fiction in the late 1970s. Music, fashion, visual art, and city life became as important to his method as conventional science-fiction extrapolation."]],
      ["From stories to a novel", ["“Johnny Mnemonic” introduced Molly and a criminal information economy; “Burning Chrome” supplied the Sprawl, console cowboys, and the word cyberspace. Editor Terry Carr then commissioned a novel for a new Ace Science Fiction Specials series. Gibson built Neuromancer while learning the longer form in public.", "He has repeatedly pushed back on the notion that deep technical knowledge produced the book. The visual metaphor of cyberspace came partly from watching arcade players behave as though a meaningful world existed behind the screen."]],
      ["Later perspective", ["Gibson continued the setting in Count Zero and Mona Lisa Overdrive, but later series moved closer to the unstable present. Interviews show him revising his own origin stories, acknowledging missed technologies such as mobile phones, and treating science fiction as a way to render contemporary strangeness."]],
    ],
    related: ["writing-neuromancer", "burning-chrome-connections", "johnny-mnemonic-connections", "sprawl-trilogy", "neuromancer-cyberpunk-movement"],
    tags: ["author", "biography", "interviews", "cyberpunk", "composition"],
    sourceKeys: ["sf-encyclopedia", "wired-gibson-2012", "guardian-gibson-2000", "time-gibson-2020"],
  }),
  publication({
    slug: "writing-neuromancer",
    title: "Writing Neuromancer",
    description: "How a commission from editor Terry Carr became a debut novel written under pressure, in dialogue with noir, New Wave science fiction, punk, and the emerging video-game arcade.",
    context: "Accounts of the book’s composition come from introductions and interviews given decades apart. The broad outline is stable, but memorable anecdotes should be treated as retrospective testimony rather than a day-by-day production log.",
    facts: [["Commissioning editor", "Terry Carr"], ["Early working title", "Jacked In"], ["Form", "First novel"], ["Drafting technology", "Manual typewriter"], ["Publication year", "1984"]],
    sections: [
      ["The commission", ["Carr invited Gibson to contribute to his second Ace Science Fiction Specials line after reading the author’s short work. Gibson had not yet written a novel and later recalled accepting with more confidence than preparation. An outline circulated under the working title Jacked In."]],
      ["Building from short fiction", ["The book did not begin from a blank world. Molly came from “Johnny Mnemonic,” while “Burning Chrome” established cyberspace, the Sprawl, and data thieves who treated software as break-in equipment. Neuromancer recombined those elements around a longer heist and two opposed forms of machine intelligence.", "Gibson names Alfred Bester, Samuel R. Delany, J. G. Ballard, William S. Burroughs, noir fiction, punk music, and contemporary visual culture among the enabling contexts. Those influences concern rhythm and attitude as much as plot."]],
      ["Anxiety and revision", ["Seeing Blade Runner during composition reportedly alarmed Gibson because its dense visual world seemed to occupy nearby territory. Rather than proving derivation, the episode shows how several early-1980s works were processing shared urban and media signals. Gibson revised the manuscript while discovering what a novel could hold.", "The result retains the compression of short fiction: new terms appear without a glossary, backstory arrives as broken dossiers, and description often behaves like montage. What some readers experience as opacity is inseparable from the book’s speed and authority."]],
    ],
    related: ["william-gibson", "ace-specials-first-edition", "burning-chrome-connections", "cyberpunk-style-neologistic-prose", "noir-heist-narrative"],
    tags: ["composition", "Terry Carr", "Jacked In", "influences", "typewriter"],
    sourceKeys: ["wired-gibson-2012", "guardian-gibson-2000", "sf-encyclopedia", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "title-neuromancer",
    title: "The title “Neuromancer”",
    description: "A coined word that joins nerves, romance, and necromancy—and acquires a precise, contested meaning inside the novel.",
    context: "The title is often reduced to a single tidy portmanteau. Gibson’s explanations and the AI’s own account support several overlapping resonances, so the page preserves the ambiguity instead of choosing one definitive etymology.",
    facts: [["Word type", "Neologism"], ["In-story referent", "An artificial intelligence"], ["Common roots", "Neuro-, necromancer, romancer"], ["Status", "Deliberately multivalent"]],
    sections: [
      ["Inside the story", ["The name belongs to the second Tessier-Ashpool AI, the intelligence associated with personality, memory, and a constructed beach. Its self-description links the word to the nerves and to calling up the dead, which fits its capacity to retain versions of human minds."]],
      ["A word with several shadows", ["“Neuro” points toward nerves and cognition; “necromancer” suggests communication with the dead; “romancer” can imply a teller of romances or an inventor of stories. The title therefore fits both the fictional entity and a novel preoccupied with simulated survival, seduction, and authored realities.", "Later paraphrases sometimes present one breakdown as Gibson’s exclusive intention. A more careful account treats the explanations as cumulative wordplay, especially because the novel’s plot makes naming part of Neuromancer’s self-fashioning."]],
      ["Why the ambiguity matters", ["Wintermute is named for silence or absence and operates through borrowed masks. Neuromancer claims a name and a face of its own. The contrasting names reinforce the difference between an intelligence that strategizes toward change and one that preserves personalities inside a private world."]],
    ],
    related: ["neuromancer-ai", "wintermute", "identity-personhood", "memory-death-digital-afterlife", "cyberpunk-style-neologistic-prose"],
    tags: ["title", "etymology", "neologism", "AI", "wordplay"],
    sourceKeys: ["novel", "guardian-gibson-2000", "academic-criticism"],
    canon: "Ambiguous",
    spoiler: "Moderate",
  }),
  publication({
    slug: "ace-specials-first-edition",
    title: "Ace Science Fiction Specials and the first edition",
    description: "The 1984 Ace paperback and the editorial program that gave Gibson’s first novel its opening.",
    context: "Edition details are bibliographic, not decorative trivia: covers, introductions, pagination, and even paratext differ, which affects quotation and page citations across the atlas.",
    facts: [["Publisher", "Ace Books"], ["Publication", "July 1984"], ["Editor", "Terry Carr"], ["Format", "Paperback original"], ["First-cover artist", "James Warhola"]],
    sections: [
      ["The New Ace Specials", ["Terry Carr’s revived Ace Science Fiction Specials aimed to introduce distinctive writers in book form. Commissioning a first novel gave Gibson a framework and a deadline while leaving room for an unusually compressed, style-forward manuscript."]],
      ["The 1984 object", ["Bibliographic records identify the first edition as an Ace paperback original published in July 1984, with cover art by James Warhola. Later printings can look radically different, so “first edition” should refer to a publication state rather than to whichever vintage-looking cover is most familiar online."]],
      ["Citation consequences", ["Page numbers vary across Ace, Gollancz, anniversary, ebook, and translated editions. This wiki uses part and chapter as stable locators and adds ISBN or edition details whenever a page number accompanies a short quotation."]],
    ],
    related: ["writing-neuromancer", "cover-art-editions", "translations-localization", "awards-honors", "neuromancer-novel"],
    tags: ["Ace Books", "first edition", "Terry Carr", "bibliography", "1984"],
    sourceKeys: ["prh-neuromancer", "sf-encyclopedia", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "cover-art-editions",
    title: "Cover art and edition history",
    description: "Four decades of visual attempts to package a novel whose most famous spaces resist literal illustration.",
    context: "This page describes credited designs and recurring motifs without reproducing copyrighted covers. Cover art is marketing and interpretation; it is never evidence for a character’s canonical appearance.",
    facts: [["First-cover artist", "James Warhola"], ["First publisher", "Ace Books"], ["Edition span", "1984 to present"], ["Common motifs", "Neon cities, grids, faces, cables, data"]],
    sections: [
      ["The first visual identity", ["The original Ace package paired the title with James Warhola’s cover illustration. Its period look belongs to the book’s publication history, but no cover can settle details that Gibson leaves unspecified or filters through Case’s perception."]],
      ["A changing visual vocabulary", ["English-language and translated editions repeatedly reinvent the book through chrome typography, luminous grids, crowded streets, mirrored faces, biomechanical hardware, and abstract data. The shifts track changing ideas of what “cyberpunk” looks like, from paperback adventure to canonical modern classic.", "Some designs lean on imagery popularized after 1984. That backward influence is useful evidence of reception, but it can make later genre conventions look as if they were all explicitly present in the novel."]],
      ["How the atlas uses covers", ["Cover images remain copyrighted. The atlas links to publisher and bibliographic records, credits artists where verified, and uses licensed contextual photography or original abstract design instead of building an unlicensed cover gallery."]],
    ],
    related: ["ace-specials-first-edition", "translations-localization", "neuromancer-graphic-novel", "influence-film-anime", "neuromancer-novel"],
    tags: ["cover art", "editions", "design", "bibliography", "visual culture"],
    sourceKeys: ["prh-neuromancer", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "translations-localization",
    title: "Translations and localization",
    description: "How translators carry Gibson’s compressed slang, brands, rhythms, and invented technical language into other linguistic worlds.",
    context: "A complete edition census requires library and national-bibliography work. This page focuses on the recurring translation problems and treats crowd-sourced cover collections as leads rather than verified records.",
    facts: [["Source language", "English"], ["Primary challenge", "Neologisms and implied context"], ["Citation rule", "Identify language and edition"], ["Canon rule", "Translation choices are not new story facts"]],
    sections: [
      ["Translating the unexplained", ["Gibson’s prose asks readers to infer what unfamiliar words do from pressure and context. A translator must decide whether to preserve an English coinage, transliterate it, build a new compound, or explain it more directly—each choice changes the original balance between speed and opacity."]],
      ["Names, brands, and registers", ["Console-cowboy slang, Japanese terms, Rastafarian speech, corporate names, and street dialogue occupy different social registers. Localizing them without flattening the voices or caricaturing them is more complex than substituting technical nouns.", "Titles also vary. Some markets keep Neuromancer as a recognizable brand; others reshape its sound or morphology. Those choices are publication history, not alternate canon."]],
      ["Responsible comparison", ["The atlas records translator, publisher, year, and ISBN before making claims about a version. Short comparisons should serve a linguistic point and respect the separate copyright in a translation."]],
    ],
    related: ["cyberpunk-style-neologistic-prose", "cover-art-editions", "japan-orientalism-globalization", "zion-rastafari-diaspora", "title-neuromancer"],
    tags: ["translation", "localization", "neologisms", "editions", "language"],
    sourceKeys: ["prh-neuromancer", "sf-encyclopedia", "academic-criticism"],
  }),
  publication({
    slug: "initial-critical-reception",
    title: "Initial critical reception",
    description: "How a paperback debut gathered extraordinary award attention while readers and reviewers negotiated its density, speed, and unfamiliar vocabulary.",
    context: "Later canonization can make the early response seem inevitable. Contemporary evidence instead shows a genre community recognizing something unusually forceful while also debating accessibility, characterization, and the values of the emerging cyberpunk tendency.",
    facts: [["Review period", "1984–1985"], ["Market position", "Paperback debut"], ["Immediate distinction", "Three major genre awards"], ["Recurring praise", "Style, atmosphere, conceptual force"], ["Recurring concern", "Opacity and emotional distance"]],
    sections: [
      ["A debut arrives", ["Neuromancer entered the market without an established novelist’s audience. Reviews and award voters nevertheless responded quickly to its language, criminal viewpoint, and fusion of computer imagery with noir and global street culture."]],
      ["What readers encountered", ["The book’s refusal to pause for explanation was exhilarating to some readers and alienating to others. Character interiority is often displaced into sensation, interfaces, and habit; that technique fueled arguments over whether the novel was emotionally thin or formally precise."]],
      ["Awards as reception", ["The Nebula, Hugo, and Philip K. Dick awards measure different constituencies and calendars. Together they document an exceptional early reception, but they do not erase critical objections or explain the book’s later reach beyond science-fiction publishing."]],
    ],
    related: ["awards-honors", "critical-reputation-scholarship", "cyberpunk-style-neologistic-prose", "neuromancer-cyberpunk-movement", "ace-specials-first-edition"],
    tags: ["reception", "reviews", "1984", "criticism", "awards"],
    sourceKeys: ["sfwa-nebula", "hugo-1985", "sf-encyclopedia", "academic-criticism"],
  }),
  publication({
    slug: "awards-honors",
    title: "Awards and honors",
    description: "The rare sweep that made a first novel the Nebula, Hugo, and Philip K. Dick Award winner.",
    context: "Award years can look inconsistent because organizations label eligibility and ceremony dates differently. This page follows each official record rather than forcing every honor into a single year label.",
    facts: [["Nebula Award", "Best Novel, publication year 1984"], ["Hugo Award", "Best Novel, 1985 ceremony"], ["Philip K. Dick Award", "Best paperback original"], ["Author status", "Debut novelist"]],
    sections: [
      ["The three major wins", ["SFWA records Neuromancer as the Nebula winner for Best Novel for works published in 1984. The World Science Fiction Convention presented the 1985 Hugo for Best Novel. The Philip K. Dick Award recognized distinguished science-fiction paperback publication."]],
      ["Why the sweep mattered", ["The prizes came from overlapping but distinct institutions: professional writers, convention voters, and an award created for paperback originals. Their convergence gave the novel immediate institutional visibility and helped a stylistically risky debut travel beyond its first printing."]],
      ["How to cite the dates", ["A reliable account names the award, category, and the organization’s own year convention. Saying only that the novel “won everything in 1984” blurs publication year and ceremony year; saying it won a “triple crown” is useful shorthand, not an official award title."]],
    ],
    related: ["initial-critical-reception", "critical-reputation-scholarship", "neuromancer-novel", "william-gibson", "ace-specials-first-edition"],
    tags: ["Hugo Award", "Nebula Award", "Philip K. Dick Award", "honors", "1985"],
    sourceKeys: ["sfwa-nebula", "hugo-1985", "prh-neuromancer"],
  }),
  publication({
    slug: "critical-reputation-scholarship",
    title: "Later critical reputation and scholarship",
    description: "From genre landmark to a contested text in debates about postmodernism, capitalism, gender, race, embodiment, and information.",
    context: "There is no single scholarly verdict. The novel’s reputation is made from arguments that often disagree: formal admiration can coexist with criticism of its politics, and influence does not exempt representation from scrutiny.",
    facts: [["Major fields", "SF studies, media studies, cultural studies"], ["Frequent lenses", "Postmodernism, posthumanism, noir, political economy"], ["Ongoing debates", "Gender, race, Japan, Zion, labor"], ["Research principle", "Attribute interpretations"]],
    sections: [
      ["Canonization", ["Award success and cultural influence turned Neuromancer into a common reference point for cyberpunk, digital culture, and postmodern fiction. Teaching guides and monographs treat its vocabulary and narrative method as historically important even when they reject simple claims that the book predicted the internet."]],
      ["Competing readings", ["One critical tradition emphasizes unstable boundaries between body and data, human and machine, original and copy. Another examines corporate sovereignty and the conversion of information, bodies, and memory into property. Noir and heist readings ask how familiar genre structures organize the book’s apparent novelty.", "Feminist and race scholarship complicates celebratory accounts, questioning how Molly’s power relates to exploitation and how Japan, Zion, and global difference are made available to a largely Western viewpoint."]],
      ["Editorial use", ["Atlas pages label a reading as interpretation and link it to a specific argument whenever possible. Plot summary cannot silently absorb a critic’s theory, and community consensus cannot stand in for scholarship."]],
    ],
    related: ["initial-critical-reception", "gender-sexuality-power", "japan-orientalism-globalization", "corporate-sovereignty", "body-disembodiment"],
    tags: ["scholarship", "criticism", "postmodernism", "posthumanism", "reputation"],
    sourceKeys: ["academic-criticism", "sf-encyclopedia", "washington-state-guide"],
  }),
  publication({
    slug: "sprawl-trilogy",
    title: "The Sprawl trilogy",
    description: "Neuromancer, Count Zero, and Mona Lisa Overdrive: three related novels that revisit a changing matrix through different ensembles.",
    context: "“Trilogy” describes the published sequence, not a single continuous quest with one hero. Later books clarify some consequences of the first novel while introducing new mysteries and names; they should not be read backward into every ambiguity.",
    facts: [["Book 1", "Neuromancer (1984)"], ["Book 2", "Count Zero (1986)"], ["Book 3", "Mona Lisa Overdrive (1988)"], ["Shared setting", "The Sprawl and matrix"], ["Structure", "Changing protagonists"]],
    sections: [
      ["Publication sequence", ["Neuromancer establishes Case, Molly, the matrix, and the Tessier-Ashpool run. Count Zero shifts to several intersecting plots in a world where the matrix behaves differently. Mona Lisa Overdrive draws figures and consequences together without simply repeating the first novel’s crew."]],
      ["Continuity with limits", ["Molly, the Finn, corporate names, constructs, and the post-merger matrix create clear connective tissue. Yet characters use aliases, institutions change, and later explanations reflect later conditions. A trilogy-wide claim therefore receives a Sprawl-canon label rather than a novel-canon badge."]],
      ["A retroactive name", ["The books are commonly marketed as the Sprawl trilogy after the shared conurbation. Gibson did not build a franchise encyclopedia in advance; the setting grew through stories and novels, which helps explain small gaps and productive uncertainties."]],
    ],
    related: ["count-zero-continuity", "mona-lisa-overdrive-continuity", "johnny-mnemonic-connections", "burning-chrome-connections", "sprawl-bama"],
    tags: ["Sprawl trilogy", "Count Zero", "Mona Lisa Overdrive", "continuity", "series"],
    sourceKeys: ["sf-encyclopedia", "prh-neuromancer", "william-gibson-wiki"],
    canon: "Novel + Sprawl",
    spoiler: "Moderate",
  }),
  publication({
    slug: "johnny-mnemonic-connections",
    title: "“Johnny Mnemonic” and Neuromancer",
    description: "The earlier story that introduced Molly, Johnny, implanted information, and a criminal economy built around bodies as storage.",
    context: "The prose story—not the 1995 film—is the relevant continuity source. Neuromancer remembers Johnny through Molly, but the novel is not a direct sequel with every detail restated.",
    facts: [["Story publication", "1981"], ["Returning character", "Molly"], ["Named in Neuromancer", "Johnny"], ["Shared concern", "Information stored in bodies"]],
    sections: [
      ["What carries forward", ["Molly’s account of Johnny explains personal losses that shape her response to Riviera and powerful employers. The story also supplies an underworld in which information can be physically carried, stolen, and made lethal."]],
      ["What not to import", ["The screen adaptation radically reworks characters and plot. Images, cast details, and invented incidents from the film are adaptation canon only. Even the short story and novel should be compared carefully rather than flattened into one seamless dossier."]],
      ["Why it matters for Molly", ["Neuromancer withholds much of Molly’s biography until the Straylight run. Reading the earlier story enriches her history, but the novel’s own revelation remains sufficient: a former partner was killed by forces larger than either of them, and memory turns the present job personal."]],
    ],
    related: ["molly", "johnny", "meat-puppet-cut-out", "body-as-commodity", "sprawl-trilogy"],
    tags: ["short fiction", "Johnny", "Molly", "continuity", "1981"],
    sourceKeys: ["novel", "sf-encyclopedia", "academic-criticism"],
    canon: "Novel + Sprawl",
    spoiler: "Moderate",
  }),
  publication({
    slug: "burning-chrome-connections",
    title: "“Burning Chrome” and Neuromancer",
    description: "The 1982 story that first named cyberspace and established the Sprawl’s console-cowboy idiom before Gibson expanded it into a novel.",
    context: "The story is a conceptual predecessor and part of the wider Sprawl setting. Shared vocabulary shows development, but differences should not be forced into a technical specification the fiction never supplies.",
    facts: [["Publication", "1982"], ["Key first use", "Cyberspace"], ["Shared setting", "The Sprawl"], ["Shared figure", "The Finn"], ["Form", "Short story"]],
    sections: [
      ["The matrix before Case", ["“Burning Chrome” presents console cowboys, ICE, criminal software, and a spatialized network. Its celebrated word arrives before Neuromancer, while the later novel gives the matrix greater narrative duration and binds access to Case’s bodily loss."]],
      ["People and places", ["The Finn and the Sprawl connect the works beyond vocabulary. Both stories focus on small operators using expensive systems against wealthier owners, but the novel scales the run from local criminal aspiration to corporate family history and artificial-intelligence law."]],
      ["Development, not blueprint", ["Terms change force when reused. A good cross-reference records what appears in both texts and what Neuromancer adds; it does not pretend the short story contains a definitive user manual for the later matrix."]],
    ],
    related: ["cyberspace-matrix", "console-cowboys", "ice", "the-finn", "writing-neuromancer"],
    tags: ["short fiction", "cyberspace", "Sprawl", "continuity", "1982"],
    sourceKeys: ["sf-encyclopedia", "sf-encyclopedia-cyberspace", "wired-gibson-2012"],
    canon: "Novel + Sprawl",
  }),
  publication({
    slug: "count-zero-continuity",
    title: "Count Zero continuity",
    description: "What the second Sprawl novel reveals—and refuses to simplify—about the matrix after Neuromancer’s final operation.",
    context: "This is a sequel-spoiler page. It separates direct recurrence from interpretation and never uses later developments to spoil a first-time reader’s article without warning.",
    facts: [["Published", "1986"], ["Position", "Second Sprawl novel"], ["Structure", "Multiple converging protagonists"], ["Matrix condition", "Changed after Neuromancer"]],
    sections: [
      ["A changed network", ["Count Zero depicts matrix entities and practices that differ from the first novel’s corporate geometry. Those changes are a consequence of Neuromancer’s ending, but characters encounter them through partial knowledge, rumor, and local interests."]],
      ["Returning threads", ["Corporate competition, biosoft technology, the matrix, and figures connected to the Sprawl return while Case’s story recedes. The sequel broadens the social field instead of offering a retrospective explanation from an omniscient source."]],
      ["Reading backward carefully", ["Later terminology can illuminate possibilities in Neuromancer, especially around distributed agency. It cannot prove that every actor in the first novel understood the future condition or that the merged intelligence had a fixed plan matching sequel events."]],
    ],
    related: ["sprawl-trilogy", "mona-lisa-overdrive-continuity", "ai-free-will", "artificial-intelligence-sprawl", "neuromancer-novel"],
    tags: ["Count Zero", "sequel", "continuity", "matrix", "Sprawl"],
    sourceKeys: ["sf-encyclopedia", "william-gibson-wiki", "academic-criticism"],
    canon: "Novel + Sprawl",
    spoiler: "Full",
  }),
  publication({
    slug: "mona-lisa-overdrive-continuity",
    title: "Mona Lisa Overdrive continuity",
    description: "The concluding Sprawl novel’s return to Molly, constructs, and a matrix whose intelligences no longer fit the first book’s categories.",
    context: "Names and identities shift across the trilogy. This page treats aliases as evidence to be demonstrated in context, not as permission to merge every later biography into the Neuromancer infobox.",
    facts: [["Published", "1988"], ["Position", "Third Sprawl novel"], ["Returning figure", "Molly under another name"], ["Focus", "Constructs, matrix entities, identity"]],
    sections: [
      ["Return and distance", ["Mona Lisa Overdrive reconnects with people and technologies from both earlier novels while preserving years of absence and reinvention. Molly’s later identity makes continuity personal: survival in the Sprawl can require changing the name under which a story knows you."]],
      ["Constructs after Dixie", ["Recorded personality, simulated environments, and the status of intelligences become even harder to divide into human copy, AI, and tool. The final novel therefore extends Neuromancer’s questions about whether continuity of pattern is continuity of person."]],
      ["The trilogy’s ending", ["Later revelations give a broader frame to the signal mentioned at the end of Neuromancer, but they also replace the seeming singularity of one merger with a more plural matrix. The relationship is development, not a simple answer key."]],
    ],
    related: ["sprawl-trilogy", "count-zero-continuity", "molly", "rom-personality-constructs", "memory-death-digital-afterlife"],
    tags: ["Mona Lisa Overdrive", "sequel", "Molly", "constructs", "continuity"],
    sourceKeys: ["sf-encyclopedia", "william-gibson-wiki", "academic-criticism"],
    canon: "Novel + Sprawl",
    spoiler: "Full",
  }),
  publication({
    slug: "neuromancer-1988-video-game",
    title: "Neuromancer: the 1988 video game",
    description: "Interplay’s adventure/RPG adaptation, which turns Chiba, cyberspace, software, and skill chips into systems a player can manipulate.",
    context: "The game borrows names and concepts but creates its own protagonist, puzzles, geography, and rules. Its mechanics are adaptation design, not a technical explanation of the novel.",
    facts: [["Developer", "Interplay Productions"], ["Initial release", "1988"], ["Publisher", "Mediagenic / Activision"], ["Designer credit", "Brian Fargo and team"], ["Music connection", "A Devo composition"]],
    sections: [
      ["Adapting a vocabulary", ["Rather than reenacting Case’s plot scene by scene, the game builds an explorable version of Chiba City and makes databases, ICE, software, money, and skills into player resources. That approach captures the novel’s underworld economy while departing freely from its events."]],
      ["Interface and platforms", ["Released across several home-computer systems, the game combines menu-driven conversation, inventory puzzles, character statistics, and a distinct cyberspace mode. Platform ports vary visually and technically, so screenshots need a platform label."]],
      ["Non-canon legacy", ["The adaptation is an important early attempt to make Gibsonian cyberspace playable. Its invented characters and concrete rules influenced reader memory, but atlas lore pages do not use the game to fill gaps in the book."]],
    ],
    related: ["cyberspace-matrix", "ice", "microsofts", "chiba-city", "influence-games-music-pop-culture"],
    tags: ["video game", "Interplay", "1988", "adaptation", "game design"],
    sourceKeys: ["mobygames", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "neuromancer-graphic-novel",
    title: "The 1989 Epic graphic novel",
    description: "Tom De Haven and Bruce Jensen’s unfinished visual adaptation, published by Epic and now frequently mistaken for a complete graphic edition.",
    context: "The adaptation provides a historically specific design reading of characters and places. Those images are copyrighted and do not define book canon.",
    facts: [["Writer", "Tom De Haven"], ["Artist", "Bruce Jensen"], ["Publisher", "Epic Comics"], ["Publication", "1989"], ["Coverage", "Incomplete adaptation"]],
    sections: [
      ["From prose to panels", ["The comic must turn Gibson’s compressed visual cues and matrix metaphors into fixed bodies, architecture, color, and sequence. De Haven and Jensen’s choices therefore interpret the book even where the plot remains recognizable."]],
      ["Publication limits", ["Bibliographic records identify the Epic release and its creators, while surviving copies and catalog descriptions show that the project did not adapt the whole novel. Calling it simply “the Neuromancer graphic novel” without that qualification creates a false expectation of completeness."]],
      ["Using it as a source", ["The comic is primary evidence for its own adaptation history. It can support a page on visual reception, but a costume, face, or room shown in a panel is not imported into the novel’s factual description unless Gibson’s text independently supports it."]],
    ],
    related: ["cover-art-editions", "influence-film-anime", "unmade-neuromancer-films", "neuromancer-1988-video-game", "apple-tv-neuromancer"],
    tags: ["graphic novel", "Epic Comics", "Bruce Jensen", "Tom De Haven", "adaptation"],
    sourceKeys: ["comics-db", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "neuromancer-opera",
    title: "Neuromancer: the opera",
    description: "A stage adaptation associated with composer Richard Marriott and librettists Jayne Wenger and Marc Lowenstein, preserved through a fragmentary performance record.",
    context: "Dates, venues, and production status vary across secondary accounts. This page marks uncertain claims and treats programs or creator archives as preferable to repeated unsourced lists.",
    facts: [["Medium", "Opera / music theatre"], ["Composer", "Richard Marriott"], ["Libretto", "Jayne Wenger and Marc Lowenstein"], ["Record status", "Incomplete and unevenly documented"]],
    sections: [
      ["A difficult translation", ["Opera replaces much of Case’s internal and virtual movement with voice, music, staging, and projected space. Neuromancer’s masks and doubled intelligences are theatrically suggestive, while the speed and density of the heist create substantial compression problems."]],
      ["Production history", ["Creator biographies and adaptation histories associate Marriott, Wenger, and Lowenstein with the work. Publicly accessible documentation is thinner than for the game or BBC drama, so precise claims about complete performances require a dated program or archival record."]],
      ["Canon and survival", ["Musical and staging solutions belong to the opera’s interpretation. Recordings, scores, photographs, and libretti may each have separate rights; the atlas links to documentation instead of reconstructing the production from copyrighted fragments."]],
    ],
    related: ["neuromancer-bbc-radio", "neuromancer-audiobooks", "unmade-neuromancer-films", "influence-games-music-pop-culture"],
    tags: ["opera", "theatre", "Richard Marriott", "adaptation", "music"],
    sourceKeys: ["wikipedia-neuromancer", "academic-criticism"],
  }),
  publication({
    slug: "neuromancer-bbc-radio",
    title: "The 2002 BBC radio drama",
    description: "Mike Walker’s audio adaptation, using performance and sound design to move between bodies, remembered voices, and the matrix.",
    context: "Broadcast listings and production credits anchor this page. Cast information belongs to the radio version and is never used to imply how novel characters canonically sound.",
    facts: [["Broadcaster", "BBC Radio 4"], ["Broadcast year", "2002"], ["Adapter", "Mike Walker"], ["Medium", "Radio drama"], ["Case performer", "Owen McCarthy"]],
    sections: [
      ["An audio matrix", ["Radio can represent cyberspace without fixing a single visual design. Layered voices, electronic sound, rhythm, and abrupt spatial transitions give the adaptation tools for distinguishing the physical run, simstim, AI masks, and Case’s console experience."]],
      ["Compression and cast", ["The production condenses a dense novel into broadcast duration and assigns performers to Case, Molly, Armitage, Wintermute, Dixie, Maelcum, Riviera, and the Tessier-Ashpool figures. Scenes and exposition necessarily move or combine."]],
      ["Source boundaries", ["A broadcast script may clarify a transition for listeners, but that clarification is an adaptation choice. The atlas uses BBC records for date and credits, and the novel for fictional canon."]],
    ],
    related: ["neuromancer-audiobooks", "neuromancer-opera", "apple-tv-neuromancer", "cyberspace-matrix", "wintermute"],
    tags: ["BBC", "radio drama", "2002", "audio", "adaptation"],
    sourceKeys: ["bbc-radio", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "neuromancer-audiobooks",
    title: "Neuromancer audiobooks",
    description: "A publication history of abridged and unabridged recordings—and the unusual authority and limits of hearing Gibson read his own prose.",
    context: "Audio editions differ in narrator, abridgment, duration, publisher, and availability. A narrator’s pronunciation is a performance record, not always a binding ruling on invented language.",
    facts: [["Notable early reader", "William Gibson"], ["Current edition source", "Penguin Random House Audio"], ["Key distinction", "Abridged vs. unabridged"], ["Citation requirement", "Narrator, publisher, year, ISBN"]],
    sections: [
      ["The author recording", ["Gibson recorded an abridged reading whose cadence gives rare access to how he performs the novel’s hard consonants, brand lists, and cool descriptive compression. Because the text is shortened, it cannot substitute for an unabridged citation."]],
      ["Unabridged editions", ["Later commercial recordings present the full book with other narrators. Catalog pages supply duration, release date, ISBN, and performer; availability can vary by region and platform."]],
      ["Listening as interpretation", ["Voice fixes pace, accent, and emphasis that silent readers choose for themselves. That makes an audiobook valuable adaptation evidence, especially for dialogue, but not a neutral container. Reviews should distinguish the novel from the performance."]],
    ],
    related: ["neuromancer-bbc-radio", "cyberpunk-style-neologistic-prose", "translations-localization", "william-gibson", "neuromancer-novel"],
    tags: ["audiobook", "narration", "William Gibson", "audio", "editions"],
    sourceKeys: ["prh-neuromancer", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "unmade-neuromancer-films",
    title: "Unmade Neuromancer films",
    description: "A long development trail of announced directors, scripts, attached talent, and abandoned approaches before the Apple television series.",
    context: "A press announcement documents an intention at a moment in time, not a completed film. This page dates every claim and avoids merging unrelated projects into one imaginary production.",
    facts: [["Status", "Multiple unrealized projects"], ["Recurring challenge", "Visualizing cyberspace and compressing the plot"], ["Frequently reported names", "Chris Cunningham, Vincenzo Natali, Tim Miller"], ["Canon", "None of the projects defines the novel"]],
    sections: [
      ["Development cycles", ["Neuromancer moved through producers, writers, directors, financing plans, and casting reports for decades. Chris Cunningham, Vincenzo Natali, and Tim Miller are among the filmmakers publicly associated with different iterations, not successive directors of one continuous shoot."]],
      ["Why announcements disappear", ["Rights, budget, visual-effects demands, market conditions, and creative direction can halt a project after trade coverage but before production. Attached actors or concept art document that abandoned version only."]],
      ["A research discipline", ["The atlas records announcement date, company, source, and last confirmed status. It uses “planned,” “attached,” or “reported” instead of saying a person made a Neuromancer film that never reached cameras."]],
    ],
    related: ["apple-tv-neuromancer", "neuromancer-graphic-novel", "neuromancer-bbc-radio", "influence-film-anime", "cover-art-editions"],
    tags: ["unmade films", "development history", "adaptation", "film", "rights"],
    sourceKeys: ["wired-gibson-2012", "wikipedia-neuromancer"],
  }),
  publication({
    slug: "apple-tv-neuromancer",
    title: "Apple TV’s Neuromancer",
    description: "The ten-episode screen adaptation starring Callum Turner as Case, Briana Middleton as Molly, and Mark Strong as Armitage, scheduled for January 22, 2027.",
    context: "This is a living adaptation page, last checked August 1, 2026. Official credits and release information can change before premiere; no trailer image, costume, or plot alteration is treated as novel canon.",
    facts: [["Premiere", "January 22, 2027"], ["Season length", "10 episodes"], ["Case", "Callum Turner"], ["Molly", "Briana Middleton"], ["Armitage", "Mark Strong"], ["Creators", "Graham Roland and JD Dillard"]],
    sections: [
      ["Official premise", ["Apple describes Case as a damaged elite hacker pulled into digital espionage and high-stakes crime with Molly, a razorgirl assassin. Their target is a corporate dynasty with dangerous secrets. That framing foregrounds the pair and the heist while withholding the book’s later identities."]],
      ["Cast and production", ["Apple’s official page credits Callum Turner, Briana Middleton, Mark Strong, and Peter Sarsgaard among the principal cast, with a larger ensemble. Graham Roland and JD Dillard created the television version; Dillard is also credited as a director and executive producer.", "The official order was announced in 2024. By the current 2026 press page, Apple lists a January 22, 2027 release and hosts teaser material. Production and publicity facts are dated because pre-release pages are routinely updated."]],
      ["Adaptation boundary", ["The series has its own visual designs, casting, chronology, and potential inventions. Atlas character pages may offer a clearly labeled adaptation tab after episodes air, but the book profile remains based on Gibson’s text."]],
    ],
    related: ["unmade-neuromancer-films", "henry-dorsett-case", "molly", "armitage-willis-corto", "neuromancer-novel"],
    tags: ["Apple TV", "television", "2027", "Callum Turner", "Briana Middleton"],
    sourceKeys: ["apple-neuromancer", "prh-neuromancer"],
    featured: true,
  }),
  publication({
    slug: "influence-computing-internet",
    title: "Influence on computing and internet culture",
    description: "How “cyberspace” and the console cowboy gave networked computing a cultural image—without making Neuromancer a literal blueprint for the internet.",
    context: "Influence claims require more than resemblance. This page distinguishes a documented quotation or borrowed term from a broad cultural parallel, and separates Gibson’s matrix from the real internet’s earlier technical history.",
    facts: [["Key term", "Cyberspace"], ["First Gibson use", "“Burning Chrome” (1982)"], ["Popularizing work", "Neuromancer (1984)"], ["Real internet", "Technically predates the novel"], ["Best evidence", "Direct testimony and dated usage"]],
    sections: [
      ["A metaphor travels", ["Cyberspace gave users, journalists, artists, policymakers, and designers a compact word for treating networked information as a place. Neuromancer’s matrix made that place luminous, navigable, owned, defended, and emotionally addictive."]],
      ["Not a prediction ledger", ["Packet networking, online communities, and research networks existed before the novel, while the book omits or misjudges many features of everyday digital life. Gibson has stressed that science fiction reads the present and that he lacked the technical expertise later myths assign him.", "The stronger claim is cultural: the novel supplied metaphors and expectations through which rapidly expanding networks were discussed. That can influence design imagination without predicting protocols or devices."]],
      ["Documenting specific influence", ["A company name, interface project, conference talk, or researcher’s statement can establish a direct line. Visual similarity alone earns a “possible resonance” label, not a claim that a product copied the book."]],
    ],
    related: ["cyberspace-matrix", "burning-chrome-connections", "console-cowboys", "neuromancer-cyberpunk-movement", "reality-perception"],
    tags: ["internet", "computing", "cyberspace", "influence", "prediction"],
    sourceKeys: ["sf-encyclopedia-cyberspace", "wired-gibson-2012", "time-gibson-2020", "academic-criticism"],
    priorityResearch: true,
  }),
  publication({
    slug: "influence-film-anime",
    title: "Influence on film, anime, and visual culture",
    description: "Documented debts, shared ancestors, and the dangerous ease of calling every neon city or virtual grid “influenced by Neuromancer.”",
    context: "Cyberpunk works inherit from overlapping sources: noir, Blade Runner, manga and anime, punk design, New Wave science fiction, and real cities. Direct creator testimony carries more weight than an image comparison.",
    facts: [["Evidence grades", "Direct, probable, parallel, unsupported"], ["Shared visual language", "Neon, density, grids, implants"], ["Key caution", "Blade Runner predates Neuromancer"], ["Scope", "Film, animation, graphic design"]],
    sections: [
      ["The feedback loop", ["Neuromancer influenced how later creators described virtuality and hacker identity, while its own composition absorbed contemporary film, fashion, music, and urban imagery. Once those elements became genre conventions, tracing a single origin became difficult."]],
      ["The Matrix and other comparisons", ["The Wachowskis’ Matrix films share terminology and the premise that experienced reality can be computationally produced, but also draw from anime, philosophy, action cinema, and other cyberpunk fiction. A careful page identifies documented lines and names the larger network of influence.", "Blade Runner is a special case: Gibson saw it while writing and feared the visual overlap. Because the film appeared first, similarity demonstrates shared early-1980s concerns rather than Neuromancer influencing its production."]],
      ["Visual afterlives", ["Covers, music videos, fashion editorials, anime cityscapes, and screen interfaces repeatedly quote a cyberpunk palette. The atlas treats that palette as a circulating visual culture, not as a set of canonical illustrations for Gibson’s prose."]],
    ],
    related: ["cover-art-editions", "neuromancer-graphic-novel", "cyberpunk-style-neologistic-prose", "japan-orientalism-globalization", "neuromancer-cyberpunk-movement"],
    tags: ["film", "anime", "The Matrix", "Blade Runner", "visual culture"],
    sourceKeys: ["wired-gibson-2012", "sf-encyclopedia-cyberpunk", "academic-criticism"],
  }),
  publication({
    slug: "influence-games-music-pop-culture",
    title: "Influence on games, music, and popular culture",
    description: "From playable cyberspace to band names and borrowed vocabulary: a map of references that distinguishes evidence from genre atmosphere.",
    context: "Lists of alleged references grow quickly and unreliably. Entries belong here only when a title, lyric, manual, interview, credit, or creator statement establishes the connection.",
    facts: [["Major domains", "Games, music, fashion, naming"], ["Direct adaptation", "Neuromancer (1988 game)"], ["Research standard", "Creator or primary-source evidence"], ["Common error", "Mistaking cyberpunk style for a direct reference"]],
    sections: [
      ["Making cyberspace playable", ["Games can turn decks, ICE, software, body upgrades, and corporate intrusion into rules. The official 1988 adaptation did so directly; later games often inherit the broader console-cowboy fantasy through a genre tradition rather than adapting Gibson’s plot."]],
      ["Sound and naming", ["Cyberpunk’s relationship to punk, electronic music, dub, and club culture predates many explicit Neuromancer references. A borrowed character name or title is easier to document than a claim that a sound “feels Gibsonian.”", "The book’s short, brand-like nouns travel well into track titles, aliases, products, and online handles. Every example still needs a dated source; coincidence is especially plausible for ordinary words such as matrix or Zion."]],
      ["A living index", ["Popular-culture references are dated and tagged as quotation, name borrowing, adaptation, homage, or probable parallel. This keeps the page useful as new works appear without turning it into an indiscriminate trivia dump."]],
    ],
    related: ["neuromancer-1988-video-game", "neuromancer-opera", "influence-computing-internet", "cyberpunk-style-neologistic-prose", "neuromancer-cyberpunk-movement"],
    tags: ["games", "music", "popular culture", "references", "influence"],
    sourceKeys: ["mobygames", "sf-encyclopedia-cyberpunk", "academic-criticism"],
  }),
  publication({
    slug: "neuromancer-cyberpunk-movement",
    title: "Neuromancer and the cyberpunk movement",
    description: "The novel’s defining place among a loose group of 1980s writers—and why saying Gibson “invented cyberpunk” hides both precursors and collaborators.",
    context: "Bruce Bethke coined the word in a story title; critics and editors applied it to a tendency associated with Gibson, Bruce Sterling, Pat Cadigan, Rudy Rucker, Lewis Shiner, John Shirley, and others. Neuromancer became the movement’s emblem, not its solitary cause.",
    facts: [["Term coined by", "Bruce Bethke"], ["Movement period", "Early to mid-1980s"], ["Neuromancer published", "1984"], ["Key anthology", "Mirrorshades (1986)"], ["Status", "Influential, contested grouping"]],
    sections: [
      ["A label arrives", ["“Cyberpunk” existed before Neuromancer as Bethke’s title. Gardner Dozois and other commentators helped attach it to a cluster of writers whose fiction joined high technology to marginal lives, aggressive style, corporate systems, and altered bodies."]],
      ["Why Neuromancer became central", ["The novel joined several tendencies in a prize-winning, portable form: a hacker antihero, global criminal markets, neural interfaces, privatized power, dense brand language, and cyberspace as an experienced territory. Its success made both supporters and critics treat it as the movement’s representative text.", "That centrality should not erase earlier writers such as Alfred Bester, Samuel R. Delany, J. G. Ballard, Philip K. Dick, Joanna Russ, and William S. Burroughs, nor the contemporaries who developed cyberpunk in different political and formal directions."]],
      ["Movement or marketing category", ["Writers did not always welcome the label, and later publishing used “cyberpunk” far beyond the original circle. The most accurate account treats it as a historically situated conversation that became a durable genre category after Neuromancer."]],
    ],
    related: ["writing-neuromancer", "critical-reputation-scholarship", "initial-critical-reception", "cyberpunk-style-neologistic-prose", "influence-computing-internet"],
    tags: ["cyberpunk", "movement", "Bruce Sterling", "genre history", "1980s"],
    sourceKeys: ["sf-encyclopedia-cyberpunk", "sf-encyclopedia", "wired-gibson-2012", "academic-criticism"],
  }),
];
