export interface SourceRecord {
  key: string;
  title: string;
  publisher: string;
  url?: string;
  kind: "Primary text" | "Official" | "Interview" | "Reference" | "Scholarship" | "Community";
  note: string;
}

export const sources: SourceRecord[] = [
  {
    key: "book-neuromancer-1984",
    title: "Neuromancer",
    publisher: "William Gibson; Ace, 1984",
    kind: "Primary text",
    note: "Primary-text key used by the character and location dossiers. Chapter locators are preferred to edition-specific pagination.",
  },
  {
    key: "novel",
    title: "Neuromancer",
    publisher: "William Gibson; Ace, 1984",
    kind: "Primary text",
    note: "The novel is the primary authority for fictional events. Chapter references are preferred because pagination varies by edition.",
  },
  {
    key: "prh-neuromancer",
    title: "Neuromancer — edition record",
    publisher: "Penguin Random House",
    url: "https://www.penguinrandomhouse.com/books/293994/neuromancer-by-william-gibson/",
    kind: "Official",
    note: "Publisher metadata and current edition information.",
  },
  {
    key: "sf-encyclopedia",
    title: "William Gibson",
    publisher: "The Encyclopedia of Science Fiction",
    url: "https://sf-encyclopedia.com/entry/gibson_william",
    kind: "Reference",
    note: "Bibliographic and genre context for Gibson and the Sprawl sequence.",
  },
  {
    key: "sfe-gibson",
    title: "William Gibson",
    publisher: "The Encyclopedia of Science Fiction",
    url: "https://sf-encyclopedia.com/entry/gibson_william",
    kind: "Reference",
    note: "Stable alias used in the article corpus for Sprawl bibliography and author context.",
  },
  {
    key: "sf-encyclopedia-cyberpunk",
    title: "Cyberpunk",
    publisher: "The Encyclopedia of Science Fiction",
    url: "https://sf-encyclopedia.com/entry/cyberpunk",
    kind: "Reference",
    note: "Reference history of the movement and Neuromancer's place within it.",
  },
  {
    key: "sfe-cyberpunk",
    title: "Cyberpunk",
    publisher: "The Encyclopedia of Science Fiction",
    url: "https://sf-encyclopedia.com/entry/cyberpunk",
    kind: "Reference",
    note: "Stable alias used in the article corpus for the movement and its terminology.",
  },
  {
    key: "sf-encyclopedia-cyberspace",
    title: "Cyberspace",
    publisher: "The Encyclopedia of Science Fiction",
    url: "https://sf-encyclopedia.com/entry/cyberspace",
    kind: "Reference",
    note: "Terminology history and science-fiction context.",
  },
  {
    key: "sfwa-nebula",
    title: "Neuromancer — Nebula Awards record",
    publisher: "Science Fiction and Fantasy Writers Association",
    url: "https://nebulas.sfwa.org/nominated-work/neuromancer/",
    kind: "Official",
    note: "Official record of the 1984 Best Novel win.",
  },
  {
    key: "hugo-1985",
    title: "1985 Hugo Awards",
    publisher: "World Science Fiction Society",
    url: "https://www.thehugoawards.org/hugo-history/1985-hugo-awards/",
    kind: "Official",
    note: "Official Best Novel award record.",
  },
  {
    key: "wired-gibson-2012",
    title: "William Gibson on Why Sci-Fi Writers Are (Thankfully) Almost Always Wrong",
    publisher: "WIRED",
    url: "https://www.wired.com/2012/09/interview-with-william-gibson/",
    kind: "Interview",
    note: "Gibson reflects on the novel's origins and on science fiction as a reading of the present.",
  },
  {
    key: "guardian-gibson-2000",
    title: "William Gibson online: the transcript",
    publisher: "The Guardian",
    url: "https://www.theguardian.com/books/2000/mar/24/sciencefictionfantasyandhorror.williamgibson",
    kind: "Interview",
    note: "Long-form reader interview covering influences, networks, and Gibson's changing relationship to technology.",
  },
  {
    key: "time-gibson-2020",
    title: "William Gibson on the Invention of ‘Cyberspace’",
    publisher: "TIME",
    url: "https://time.com/5770124/author-william-gibson-new-book-interview/",
    kind: "Interview",
    note: "Later account of the word's coinage and the limits of prediction narratives.",
  },
  {
    key: "openfiction-chapters",
    title: "Neuromancer chapter index",
    publisher: "OpenFiction",
    url: "https://openfiction.org/books/PM4H49UkyQHyYG0-EGTVn/neuromancer/chapters",
    kind: "Reference",
    note: "A chapter-level orientation aid. Plot claims are checked against the novel.",
  },
  {
    key: "gmu-notes",
    title: "Neuromancer teaching notes",
    publisher: "George Mason University",
    url: "https://mason.gmu.edu/~dtaciuch/neuronotes/",
    kind: "Scholarship",
    note: "Teaching notes useful for vocabulary, chapter structure, and interpretive questions.",
  },
  {
    key: "washington-state-guide",
    title: "Study guide to Neuromancer",
    publisher: "Washington State University",
    url: "https://public.wsu.edu/~brians/science_fiction/neuromancer.html",
    kind: "Scholarship",
    note: "Academic reading guide focused on allusions, terminology, and historical context.",
  },
  {
    key: "wsu-neuromancer-guide",
    title: "Study guide to Neuromancer",
    publisher: "Paul Brians, Washington State University",
    url: "https://public.archive.wsu.edu/brians/public_html/science_fiction/neuromancer.html",
    kind: "Scholarship",
    note: "Archived academic reading guide for allusions, vocabulary, and chapter-level orientation.",
  },
  {
    key: "ebsco-neuromancer",
    title: "Neuromancer by William Gibson",
    publisher: "EBSCO Research Starters",
    url: "https://www.ebsco.com/research-starters/literature-and-writing/neuromancer-william-gibson",
    kind: "Reference",
    note: "Structured overview of the novel's plot, characters, locations, and reception.",
  },
  {
    key: "story-johnny-mnemonic-1981",
    title: "“Johnny Mnemonic”",
    publisher: "William Gibson; Omni, 1981",
    kind: "Primary text",
    note: "Wider-Sprawl primary source for Johnny and Molly. The prose story—not its film adaptation—is the relevant continuity text.",
  },
  {
    key: "jstor-cybernetic-deconstructions",
    title: "Cybernetic Deconstructions",
    publisher: "Scholarly criticism via JSTOR",
    url: "https://www.jstor.org/stable/j.ctv1168ch3.40",
    kind: "Scholarship",
    note: "Critical account of postmodernism and unstable boundaries among humans, machines, and representations.",
  },
  {
    key: "jstor-network-and-archive",
    title: "The Network and the Archive",
    publisher: "Andrew Strombeck; Science Fiction Studies",
    url: "https://www.jstor.org/stable/25746410",
    kind: "Scholarship",
    note: "Analysis of Straylight, the Zion cluster, networks, archives, and imperial management.",
  },
  {
    key: "academic-criticism",
    title: "Neuromancer criticism and scholarship",
    publisher: "Selected scholarly literature",
    kind: "Scholarship",
    note: "A grouped citation used where the page synthesizes several established critical approaches; individual readings are identified in the research ledger.",
  },
  {
    key: "wikipedia-neuromancer",
    title: "Neuromancer",
    publisher: "Wikipedia contributors",
    url: "https://en.wikipedia.org/wiki/Neuromancer",
    kind: "Reference",
    note: "Discovery source for bibliographic leads; stronger records are preferred for final claims.",
  },
  {
    key: "william-gibson-wiki",
    title: "William Gibson Wiki",
    publisher: "Fandom community",
    url: "https://williamgibson.fandom.com/wiki/Neuromancer",
    kind: "Community",
    note: "Community-maintained cross-reference used for discovery, never as the sole authority for ambiguous canon.",
  },
  {
    key: "reddit-discussions",
    title: "Reader discussions of Neuromancer",
    publisher: "Reddit communities",
    url: "https://www.reddit.com/r/Neuromancer/",
    kind: "Community",
    note: "Used only to document recurring reader questions and interpretations, not factual canon.",
  },
  {
    key: "apple-neuromancer",
    title: "Neuromancer — official series page",
    publisher: "Apple TV Press",
    url: "https://www.apple.com/tv-pr/originals/neuromancer/",
    kind: "Official",
    note: "Current release date, credited cast and crew, official premise, and publicity material.",
  },
  {
    key: "mobygames",
    title: "Neuromancer (1988) credits and release data",
    publisher: "MobyGames",
    url: "https://www.mobygames.com/game/687/neuromancer/",
    kind: "Reference",
    note: "Platform, credit, and release history for the Interplay game.",
  },
  {
    key: "comics-db",
    title: "William Gibson's Neuromancer — publication record",
    publisher: "Grand Comics Database",
    url: "https://www.comics.org/issue/400174/",
    kind: "Reference",
    note: "Issue-level record for the Epic graphic adaptation.",
  },
  {
    key: "bbc-radio",
    title: "Neuromancer radio adaptation",
    publisher: "BBC Genome / BBC Radio 4",
    url: "https://genome.ch.bbc.co.uk/search/0/20?q=Neuromancer",
    kind: "Official",
    note: "Broadcast-history discovery record for the 2002 radio drama.",
  },
  {
    key: "who-mycotoxins",
    title: "Mycotoxins",
    publisher: "World Health Organization",
    url: "https://www.who.int/news-room/fact-sheets/detail/mycotoxins",
    kind: "Official",
    note: "Authoritative definition of mycotoxins as toxic compounds naturally produced by certain molds, plus documented routes and health effects.",
  },
  {
    key: "fda-mycotoxins",
    title: "Mycotoxins",
    publisher: "U.S. Food and Drug Administration",
    url: "https://www.fda.gov/food/natural-toxins-food/mycotoxins",
    kind: "Official",
    note: "Regulatory overview showing that mycotoxin is a broad family of fungal toxins rather than a single compound or living infection.",
  },
  {
    key: "ncbi-t2-guidelines",
    title: "Guidelines for T-2 Toxin",
    publisher: "National Academies Press via NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK224203/",
    kind: "Scholarship",
    note: "Scientific history and toxicology of T-2, used only to contextualize—not identify—the novel’s unnamed wartime agent.",
  },
  {
    key: "fao-mycotoxin-history",
    title: "Mycotoxin prevention and control in foodgrains — An introduction to mycotoxins",
    publisher: "Food and Agriculture Organization of the United Nations",
    url: "https://www.fao.org/4/x5036e/x5036e04.htm",
    kind: "Official",
    note: "Historical context for trichothecene contamination and alimentary toxic aleukia in the Soviet Union.",
  },
  {
    key: "usda-t2-review",
    title: "T-2 toxin, a trichothecene mycotoxin: Review of toxicity, metabolism, and analytical methods",
    publisher: "U.S. Department of Agriculture, Agricultural Research Service",
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=265406",
    kind: "Scholarship",
    note: "Peer-reviewed toxicology record demonstrating the real compound’s broad biological effects; it is not treated as Case’s canonical toxin.",
  },
  {
    key: "ncbi-mycotoxins-review",
    title: "Mycotoxins",
    publisher: "Clinical Microbiology Reviews via PubMed Central",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC164220/",
    kind: "Scholarship",
    note: "Peer-reviewed overview of the yellow-rain controversy, including the pollen and honeybee evidence that challenged claims of a trichothecene attack.",
  },
];

export const sourceByKey = new Map(sources.map((source) => [source.key, source]));
